const lang_fr = {
  close:"Fermer",
  loadingmodel:"Chargement de l'objet",
  menistartpage:"Page d'accueil",
menifind:"Trouver des objets, des histoires ...",
meniadd:"Ajouter ou modifier une description",
meniask:"Poser une question sur l'objet",
meniupload:"Donner des photos pour le modèle 3D",
menishare:"Partager un objet ou une histoire",
meniar:"Réalité augmentée...",
meniaron:"Activer la réalité augmentée",
menimarker:"Impression de marqueurs RA",
menisupport:"Contact et assistance",
meniabout:"À propos et contact",
menilogin:"Connexion",
menilogout:"Déconnexion",
headfind:"Trouver",
headfindt:"Recherche d'appareils expérimentaux",
headcontribute:"Contribuer",
headcontributet:"Aidez-nous à agrandir notre collection d'objets !",
headaron:"Activer la RA",
headaront:"Cliquez pour activer la Réalité Augmentée",
headaroff:"Désactiver la RA",
headarofft:"Cliquez pour désactiver la réalité augmentée",
meni0_0:"POUR LES ÉTUDIANTS",
meni0_1:"Trouver. Tout. Des expériences historiques, aux vis de réglage fin.",
meni0_2:"Laissez-vous inspirer. Développez votre propre espace créatif en réfléchissant à différentes possibilités de design.",
meni1_0:"POUR LES ENSEIGNANTS",
meni1_1:"Utilise. Partagez sous forme de présentations et de cours.",
meni1_2:"Créez. Annotez les objets de vos propres descriptions, et partagez leurs histoires.",
meni2_0:"POUR LES CHERCHEURS",
meni2_1:"Contribuer. Il suffit d’une pause-café pour partager avec un monde entier cet appareil que vous croisez tous les jours.",
meni2_2:"Explorez. Suivez le développement des designs de prototypes.",
aboutheader:"A propos de ResearchX3D.com",
aboutteam:"L'équipe",
aboutcontact:"Contactez-nous",
about0:"Partageons le patrimoine scientifique pour libérer notre créativité ! L'appareil expérimental est un élément clé de la recherche scientifique. Les expériences historiques et les conceptions modernes constituent un patrimoine précieux. Une fois que ces objets sont partagés, ils deviennent des ressources utiles, stimulant la créativité des gens à travers le monde. Or, il est maintenant possible de partager un appareil expérimental pendant la pause café !",
about1:"Que fait ResearchX3D.com ?",
about2:"A partir de photos d’appareils scientifiques (issus des laboratoires, couloirs et étagères d’université, ...) <b>envoyées par l'utilisateur</b>...",
about3:"...nous <b>créons des modèles 3D </b>explorables par tous depuis un simple navigateur web.",
about4:"ResearchX3D.com permet donc d'accroître l'impact du patrimoine et d'accumuler des savoirs sur des appareillages expérimentaux :",
about5:"<b>L’explication détaillée</b> des objets avec marqueurs et flèches 3D se fait facilement grâce à l'éditeur en ligne. Les annotations peuvent être accompagnées de <b>descriptions textuelles et audio</b> ;",
about6:"Des groupes d'étiquettes forment des histoires sur les objets. Les utilisateurs peuvent <b>trouver des histoires en fonction de leur niveau de connaissance </b>. Tous les niveaux ont leur place : de l'enseignement primaire et secondaire jusqu'à des discussions avancées entre chercheurs, en passant par des descriptions détaillées pour l’enseignement universitaire ;",
about7:"Tout le monde peut poser des questions. Les <b>questions et réponses</b> utilisent les étiquettes 3D pour des descriptions <b>\"point-and-tell\"</b>. Les meilleures réponses sont élues par les utilisateurs ;",
about8:"Les objets peuvent être vus en <b>réalité augmentée </b>, permettant à chacun de matérialiser un appareil complexe sur son bureau ;",
about9:"Toutes les fonctionnalités sont apportées par l'interface web (pas d'installation, fonctionne sur toutes les plateforme), ce qui permet un partage <b>facile </b> d'objets et d'histoires en envoyant des simples liens à vos collègues et amis.",
about10:"La plateforme ResearchX3D.com vise à",
about12:"Physiciens, actuellement chercheurs postdoctoraux Marie Curie à <a href=\"https://www.institutoptique.fr/\">Institut d'Optique, Palaiseau, France</a>.",
about13:"Contactez-nous à <a href='mailto:contact@researchx3d.com?subject=Feedback'>contact@researchx3d.com</a>",
aboutli0:"Préserver le patrimoine scientifique et technique ;",
aboutli1:"Archiver leur description par les chercheurs afin de sauvegarder les idées et les astuces de conception pour l'avenir ;",
aboutli2:"Présenter le patrimoine de manière inspirante et créative, pour la curiosité, l'enseignement, ou la recherche ;",
aboutli3:"Démocratiser l'accès à la conception d'appareils expérimentaux, en partageant avec le monde entier des objets peu accessibles.",
findobject:"Rechercher un objet",
findstory:"...puis choisissez une histoire/annotation",
findquestion:"...ou voir les questions et réponses",
filtersubject:"Filtrer par thématique",
filterknowledgelevel:"Niveau de connaissance : ",
shareqr:"Partager l'appareil expérimental et l'histoire avec un lien direct ou un code QR",
click2copy:"cliquez pour copier le lien",
saveqr:"Enregistrer l'image du code QR",
askquestion:"Poser une question",
share:"partager",
addmodifystory:"Ajoutez/modifiez votre récit",
depositedby:"Déposé par",
logoutsuccess:"Vous avez été déconnecté avec succès !",
objectannotation:"Description d'objet",
objectannotationt:"cliquez pour sélectionner une annotation différente",
by:"par",
location:"Emplacement",
details:"Détails",
tags:"Tags",
forthisobject:"pour cet objet",
object:"object",
previousm:"Section précédente",
nextm:"Section suivante",
or:"ou",
moto:"Partager le patrimoine scientifique pour libérer la valeur créative.",
pleaselogin:"Pour continuer, veuillez vous connecter",
enteremail:"Entrez votre adresse email",
enterpassword:"Entrer le mot de passe",
login:"Connexion",
forgotpassword:"Mot de passe oublié ?",
cancel:"Annuler",
newuser:"Nouveau membre ?",
loginnote1:"Pour ajouter des objets, des annotations, poser des questions et y répondre, vous devez vous connecter.",
loginnote2:"Pour enregistrer les modifications, vous devez d'abord confirmer votre identité, puis appuyer sur 'Enregistrer'.",
add:"Ajouter",
remove:"enlever",
finally:"Enfin",
annotation:"segment d'histoire",
savestory:"sauvegardez le récit",
level1:"école primaire",
level2:"école secondaire/lycée",
level3:"université (premier cycle)",
level4:"Doctorat/recherche",
addmarker:"Ajouter un marqueur",
addarrow:"ajouter une flèche",
textual:"textuel",
audio:"sonore",
addexp:"Ajouter une description",
explanation:"pour cette annotation",
marker:"marqueur",
arrow:"flèche",
at:"à",
angle:"angle",
arintro:"Mettez le <a href=\"/print_marker.pdf\"><img alt=\"R3D\" src=\"\\ar_marker_small.png\" align=\"middle\" si></a> marker dans la vue caméra.<br/> Pour naviguer dans l'histoire, cliquez sur les flèches gauche et droite. ",
noexistingaudio:"Aucune description sonore existante.",
newupload:"Nouveau téléchargement ",
newrecording:"Nouvel enregistrement sonore ",
recordsound:"Démarrer l'enregistrement",
stopbutton:"Arrêter l'enregistrement",
storytitle:"Titre de l'histoire",
storydesc:"Bref résumé de cette histoire ...",
adddesc:"Ajouter la description de cette annotation ...",
arrowadjust:"Ajustez la position et l'orientation de flèche, puis ",
markeradjust:"Ajustez la position du marqueur, puis ",
savemarker:"enregistrer le marqueur",
savearrow:"enregistrer la flèche",
audiodesc:"Description sonore :",
clicktochangelan:"Cliquez pour changer de langue",
getarmarkers:"obtenez des marqueurs de réalité augmentée",
contributeh2:"Contribuer à l'appareil.... ça prend le temps d’une pause café !",
contributeh3_1:"Comment ça marche?",
contributeh3_2:"Prêt ? Commencez ici...",
contributeli1:"<b>Vous</b> téléchargez ~30 photos de l'appareil expérimental que vous documentez. Essayez de prendre des photos de telle sorte que chaque point sur l'objet soit vu sur 3 à 6 photos sous différents angles. Plus de photos, c'est mieux que moins de photos !",
contributeli2:"<b>Nous construisons un modèle 3D à partir de vos photos</b>, à l'aide d'un logiciel de photogrammétrie, et le mettons en ligne sur ResearchX3D",
contributeli3:"<b>Tout le monde</b> peut explorer, annoter, poser des questions et partager le modèle 3D reconstruit une fois qu'il est en ligne. En tant que propriétaire, vous recevrez une première invitation à ajouter une annotation et une histoire, qui seront mises en évidence comme annotation originale.",
contributep1:"C'est tout, le patrimoine de la recherche est accessible dans le monde entier, pour d'autres étudiants, éducateurs et chercheurs.",
contributep2:"Pour le moment, nous n'acceptons que les contributions d'utilisateurs ayant des courriels académiques. Si vous n'avez pas d'email académique mais que vous souhaitez contribuer, veuillez <input type=\"button\" onclick=\"openBoard('aboutProject');\" value=\"nous contacter\"/>.",
contributestart:"Démarrer le téléchargement des photos d'un objet",
newuserh3:"Enregistrement d'un nouvel utilisateur",
newuseri1:"Prénom",
newuseri1l:" Votre nom et prénom apparaîtront à côté des objets que vous téléchargez/annotez.",
newuseri2:"Nom",
newuseri3:"Établissement et pays",
newuseri3l:" Votre affiliation et votre pays d'implantation.",
newuseri4:"email",
newuseri4l:" Note : seuls les courriels académiques sont acceptés. Vous recevrez un lien de confirmation.",
newuseri5:"Saisir le mot de passe",
newuseri5l:" Minimum de 8 caractères.",
newuseri6:"Confirmer le mot de passe",
newuseri6l:" Juste pour vérifier qu'il n'y a pas de fautes de frappe.",
newusersubmit:"Inscrire un nouvel utilisateur",
uploadedobjects:"Objets téléchargés existants :",
nameobject:"Nommez votre nouvel objet ",
enterobjectname:"entrer un nom d'objet",
and:"et",
cratephotospace:"créez un espace pour les photographies",
photolisting:"Liste des photographies de",
nophotolist:"Vous n'avez pas encore téléchargé de photos pour aucun objet. Veuillez télécharger les photos des objets ci-dessous.",
uploadnewphotos:"Télécharger de nouveaux fichiers",
startupload:"Démarrer le téléchargement",
metadataobject:"Métadonnées sur l'objet photographié",
objtitle:"Nom de l'objet",
objtitlel:"Nom de l'objet",
objdetails:"Détails de l'objet",
objdetailsl:"brève description de l'objet",
objlocation:"Emplacement original et actuel de l'objet",
objlocationl:"p. ex. CERN (actuellement à l'Université de ...)",
objyear:"Année de fabrication de l'objet (estimation)",
objtags:"Tags d'objet",
objsubmit:"Soumettre une photo pour la reconstruction d'un objet 3D",
newobjectspaceerror:"Il y a eu une erreur lors de la création de votre espace objet : ",
newobjectspacesuccess:"Création réussie d'un espace pour la photographie d'un nouvel objet.",
objsubmerr1:"ERREUR : Vous devez ajouter quelques balises <b>Tags d'objet</b> avant la soumission !",
objsubmerr2:"ERREUR : Le nom de l'objet doit avoir une longueur d'au moins 3 caractères.",
objsubmerr3:"ERREUR : Entrez au moins 10 caractères pour la description de l'objet.",
objsubmerr4:"ERREUR : Veuillez indiquer l'emplacement de l'objet (historique, actuel ou entreprise auprès de laquelle il est disponible).",
objsubmerr5:"ERREUR : Veuillez entrer l'année de création de l'objet (estimée).",
delete:"supprimer",
question:"Question",
answers:"Réponses",
addeditanswer:"Ajoutez ou modifiez votre réponse",
clickdownvotel:"cliquez pour voter en bas de la question ou de la réponse",
clickupvotel:"cliquez pour augmenter le vote de la question ou de la réponse",
yourquestion:"Votre question:",
questiondesc:"Ajouter une annotation sur un objet et décrire les détails textuels de la question.",
submitquestion:"Soumettre une question",
tooltipmainm:"Cliquez pour ouvrir le menu principal",
meniobject:"Objets",
questiontitle:"Titre de la question",
aboutfunding:"Le financement",
about15:"Projet soutenu par le dispositif Science et Société de La Diagonale Paris-Saclay.",
size:"taille",
color:"couleur",
red:"rouge",
green:"vert",
blue:"bleu",
orange:"orange",
magenta:"magenta",
selectlicense:"Sélectionnez la licence pour les fichiers téléchargés (le modèle reconstruit sera publié sous la même licence)",
read:"lis",
licensetext:"licence",
translated:"Traduit",
transsee:"voir la traduction en",
transsource:"Texte original",
transseesource:"voir l'original dans",
transimprove:"améliorer la traduction",
"fr":"français",
"en":"Anglais",
"es":"Espagnol",
"pt":"Portugais",
"de":"allemand",
"zh":"chinois",
"ru":"russe",
"ar":"arabe",
"sv":"suédois",
"nl":"néerlandais",
"it":"italien",
"ja":"Japonais",
"sr":"serbe",
"cs":"tchèque",
"da":"danois",
"sw":"swahili",
"hi":"hindi",
"tr":"turc",
"vi":"vietnamien",
"th":"thaïlandais",
"ko":"coréen",
"fa":"farsi",
"id":"indonésien",
"cy":"gallois",
"el":"grec",
"ro":"roumain",
"hu":"hongrois",
"pl":"polonais",
transimprovetitle:"Améliorez la traduction",
transnote:"La traduction est un effort commun de traduction automatique et de rétroaction humaine. Merci d'avoir pris le temps de contribuer.",
transorigin:"Original en",
transsuggest:"Traduction en",
transsubmit:"Soumettre la traduction",
press:"Toucher",
forillustration:"pour illustration",
storylang:"Écrit dans la langue:",
footer0:"À propos de ResearchX3D",
footer1:"Rechercher des objets, des histoires et des questions",
footer2:"Poser une question sur l'objet",
footer3:"Réalité augmentée",
footer4:"Soumettre un objet",
footer5:"Soumettre une histoire",
footer_title1:"LIENS RAPIDES",
footer_title2:"LIENS SOCIAUX",
navigation:"La navigation",
rotation:"Faire tourner",
move:"déplacer, ou",
zoom:"zoomer l'objet",
clickForStory:"Cliquez ici pour voir l'histoire de l'objet.",
latexAdd:"ou ajouter au document LaTeX",
latexPDF:"téléchargez l'image PDF ici",
latexCode:"et ajoutez le code ci-dessous.",
latexCaption1:"Scannez le code QR ou entrez",
latexCaption2:"afin d'ouvrir l'objet.",
contributeHeader:"DEVENEZ CONTRIBUTEUR",
contribute1:"Regardez une courte vidéo sur la motivation derrière ResearchX3D ...",
contribute2:"... ou voir juste une introduction de 4 minutes à ResearchX3D.",
contribute3:"ResearchX3D crée des modèles 3D à partir de vos photographies ...",
contribute4:"... mais vous pouvez également télécharger des objets 3D déjà créés, par exemple à partir d'un logiciel de CAO.",
contribute5:"Chaque objet a de nombreuses histoires à raconter. En créant différents types d'histoires, vous pouvez:",
contribute6:"Expliquer une fonction et un design; ou",
contribute7:"Tester vos connaissances avec un quiz; ou",
contribute8:"Partager vos compétences et vos procédures.",
contribute9:"Voici comment l'éditeur ResearchX3D vous aide à créer une histoire.",
clickvideo:"Cliquez ici pour voir la vidéo.",
clickexample:"Cliquez ici pour voir un exemple",
openstory:"Ouvrez cette histoire",
allsbj:"tous les domaines",
showall:"afficher tout",
graphic:"graphique",
figclick:"Rechercher des histoires et des annotations sur cet objet",
openar:"ouvert en réalité augmentée",
meniagora:"Discussions communautaires - Agora",
r3dsummary:"<b> Qu'est-ce que ResearchX3D? </b> Une plate-forme communautaire ouverte pour partager le patrimoine scientifique afin de libérer une valeur créative pour l'avenir.",
agoraad:"<b> Suggérer et discuter </b> d’idées sur le projet ResearchX3D, et obtenir de l’aide sur notre Agora <img class = 'link' src = '/link.png'> pour les discussions communautaires."
}
