const lang_ro = {
  close:"Închide",
  loadingmodel:"Se încarcă modelul 3D al",
  menistartpage:"Pagina principala",
  menifind:"Găsiți obiecte, povești și întrebări",
  meniadd:"Adăugați sau editați povestea",
  meniask:"Puneți o întrebare asupra unui obiect",
  meniupload:"Încărcați fotografii pentru modelul 3D",
  menishare:"Împărtășește obiectul sau povestea",
  meniar:"Realitate augmentată...",
  meniaron:"Activați modul AR",
  menimarker:"Imprimați markeri AR",
  menisupport:"Contact și asistență",
  meniabout:"Despre ResearchX3D",
  menilogin:"Autentificare",
  menilogout:"Deconectați-vă",
  headfind:"Căutare",
  headfindt:"Căutați aparate experimentale",
  headcontribute:"A contribui",
  headcontributet:"Ajută-ne să ne dezvoltăm colecția de obiecte!",
  headaron:"AR ON",
  headaront:"Faceți clic pentru a activa Realitatea augmentată",
  headaroff:"AR OFF",
  headarofft:"Faceți clic pentru a dezactiva RA",
  meni0_0:"PENTRU STUDENTI",
  meni0_1:"Găsi. Totul, de la experimente istorice, la șuruburi de reglare fine.",
  meni0_2:"A fi inspirat. Extindeți-vă propriul spațiu creativ gândindu-vă la diferite posibilități de proiectare.",
  meni1_0:"PENTRU EDUCATORI",
  meni1_1:"Utilizare. Afișați în prezentări și împărtășiți în notele de curs.",
  meni1_2:"Crea. Adnotați obiecte după propria descriere și împărtășiți povestea dvs. despre ele.",
  meni2_0:"PENTRU CERCETATORI",
  meni2_1:"A contribui. Este nevoie de o pauză de cafea pentru a împărtăși lumii întregi aparatul pe care îl treceți în fiecare zi.",
  meni2_2:"Explora. Urmăriți dezvoltarea ideilor de proiectare.",
  aboutheader:"Despre ResearchX3D.com",
  aboutteam:"Echipa de contact și proiect",
  about0:"Să împărtășim moștenirea noastră științifică pentru a ne debloca potențialul creativ pentru viitor! Un aparat experimental este un element cheie în cercetarea științifică. Atât experimentele istorice, cât și desenele moderne sunt un patrimoniu valoros. Odată ce aceste obiecte sunt împărtășite, ele devin resurse utile, stimulând creativitatea oamenilor din întreaga lume. Și acum este posibil să împărtășim aparate experimentale în timpul unei pauze de cafea!",
  about1:"Ce face ResearchX3D.com?",
  about2:"Pe baza <b> fotografiilor încărcate de utilizator </b> ale aparatelor științifice din laboratoarele lor, coridoarele universității și rafturile de birouri ...",
  about3:"... <b> creăm modele 3D </b> explorabile de oricine din browserul web.",
  about4:"ResearchX3D.com permite apoi să îmbunătățim impactul patrimoniului nostru științific și să acumulăm cunoștințe pe aparate:",
  about5:"<b> Etichetarea 3D </b> a obiectelor cu markere și săgeți în spațiul 3D se face cu ușurință prin intermediul editorului nostru online. Adnotările pot fi însoțite de <b> descrieri textuale, grafice și / sau audio </b>;",
  about6:"Grupuri de etichete fac povești despre obiecte. Utilizatorii pot <b> găsi povești pe baza nivelului lor de cunoștințe </b>. Spectrul complet al utilizatorilor este acoperit: de la predarea școlii primare și a liceului, până la descrieri detaliate la nivel universitar, până la discuții avansate despre proiectarea aparatelor pentru nivelul de doctorat / cercetare. ResearchX3D și poveștile selectate sunt <b> disponibile în 25 de limbi </b>.",
  about7:"Toată lumea poate pune o întrebare. Ambele <b> întrebări și răspunsuri </b> utilizează etichete 3D pentru <b> descrierile „indică și spune” </b>. Cele mai bune răspunsuri sunt susținute de utilizatori;",
  about8:"Obiectele pot fi văzute în <b> realitate augmentată </b>, permițând tuturor să vadă aparate experimentale pe biroul lor;",
  about9:"Toate funcționalitățile funcționează prin interfața web (fără instalare, independentă de platformă), permițând <b> partajarea ușoară </b> a obiectelor și poveștilor prin trimiterea de linkuri către colegi și prieteni.",
  about10:"Platforma ResearchX3D.com își propune",
  about12:"Fizicieni, în prezent bursieri postdoctorali Marie Curie la <a href=\"https://www.institutoptique.fr/\"> Institute d'Optique, Palaiseau, Franța </a>.",
  about13:"Contactați-ne la <a href='mailto:contact@researchx3d.com?subject=Feedback'> contact@researchx3d.com </a>.",
  aboutli0:"Păstrați modele de obiecte ale patrimoniului științific și tehnic;",
  aboutli1:"Înregistrați descrierile de proiectare ale cercetătorilor pentru a proteja ideile și trucurile de proiectare pentru viitor;",
  aboutli2:"Prezentați moștenirea științifică într-un mod care inspiră și extinde gândirea creativă în publicul din tot spectrul, de la predare până la nivel de cercetare; și",
  aboutli3:"Democratizați accesul la proiectarea aparatelor experimentale, luând ceva accesibil anterior doar câtorva norocoși și împărtășindu-l cu întreaga lume.",
  findobject:"Căutați obiectul ...",
  findstory:"... și apoi alegeți povestea / adnotarea",
  findquestion:"... sau vezi întrebări și răspunsuri",
  filtersubject:"Filtrează după domeniu:",
  filterknowledgelevel:"Filtrează după nivelul de cunoștințe:",
  shareqr:"Distribuiți aparate experimentale și poveste cu link direct sau cod QR",
  click2copy:"faceți clic pentru a copia linkul",
  saveqr:"Salvați imaginea codului QR",
  askquestion:"Cere întrebare",
  share:"acțiune",
  addmodifystory:"Adăugați / modificați povestea",
  depositedby:"Depus de",
  logoutsuccess:"Ați fost deconectat cu succes!",
  objectannotation:"Adnotarea obiectului",
  objectannotationt:"Faceți clic pentru a selecta adnotări diferite",
  by:"de",
  location:"Locație",
  details:"Detalii",
  tags:"Etichete",
  forthisobject:"pentru acest obiect",
  object:"obiect",
  previousm:"Secțiunea anterioară",
  nextm:"Următoarea secțiune",
  or:"sau",
  moto:"Împărtășirea patrimoniului științific pentru a debloca valoarea creativă pentru viitor.",
  pleaselogin:"Pentru a continua vă rugăm să vă autentificați",
  enteremail:"Introduceți adresa de email",
  enterpassword:"Introdu parola",
  login:"Autentificare",
  forgotpassword:"Ați uitat parola?",
  cancel:"Anulare",
  newuser:"Utilizator nou?",
  loginnote1:"Pentru a adăuga obiecte, adnotări și a pune / răspunde la întrebări, trebuie să vă conectați.",
  loginnote2:"Pentru a salva modificările, trebuie mai întâi să vă confirmați identitatea și apoi să apăsați „Salvare”.",
  add:"Adăuga",
  remove:"elimina",
  finally:"In cele din urma",
  annotation:"segment de poveste",
  savestory:"salvează povestea",
  level1:"scoala primara",
  level2:"liceu",
  level3:"universitate (licență)",
  level4:"Doctorat / cercetare",
  addmarker:"Adăugați un marker",
  addarrow:"adauga sageata",
  textual:"textual",
  audio:"audio",
  addexp:"Adăuga",
  explanation:"descrierea acestei adnotări",
  marker:"marcator",
  arrow:"săgeată",
  at:"la",
  angle:"unghi",
  arintro:"Puneți marcatorul <a href=\"/print_marker.pdf\"><img alt = \"R3D\" src = \"\\ar_marker_small.png\" align = \"middle\" si></a> în vizualizarea camerei. <br/> Pentru a naviga în poveste, faceți clic pe săgețile din stânga și din dreapta.",
  noexistingaudio:"Nu există descrieri audio existente.",
  newupload:"Încărcare nouă",
  newrecording:"Înregistrare nouă",
  recordsound:"Începe să înregistrezi",
  stopbutton:"Opriți înregistrarea",
  storytitle:"Titlul poveștii",
  storydesc:"Scurt rezumat al acestei povești despre obiect ...",
  adddesc:"Adăugați o descriere pentru această adnotare ...",
  arrowadjust:"Reglați poziția și orientarea săgeții, apoi",
  markeradjust:"Reglați poziția markerului și apoi",
  savemarker:"salvați marker",
  savearrow:"săgeată de salvare",
  audiodesc:"Descriere audio:",
  clicktochangelan:"Faceți clic pentru a schimba limba",
  getarmarkers:"obțineți markeri de realitate augmentată",
  contributeh2:"Contribuie cu un aparat ... durează o pauză de cafea!",
  contributeh3_1:"Cum functioneazã?",
  contributeh3_2:"Gata? Începe aici...",
  contributeli1:"<b> Vă </b> încărcați ~ 30 de fotografii ale aparatului experimental pe care îl documentați. Încercați să faceți fotografii astfel încât fiecare punct al obiectului să fie văzut pe 3-6 fotografii din unghiuri diferite. Mai multe fotografii sunt mai bune decât mai puține fotografii!",
  contributeli2:"<b> Construim un model 3D din fotografiile dvs. </b>, folosind software de fotogrametrie și îl punem online pe ResearchX3D",
  contributeli3:"<b> Toată lumea </b> poate explora, adnota, pune întrebări și partaja modele 3D reconstruite odată ce este online. În calitate de proprietar, veți primi prima invitație de a adăuga adnotare și poveste, care va fi evidențiată ca adnotare originală.",
  contributep1:"Atât, patrimoniul cercetării este disponibil la nivel mondial, pentru alți studenți, educatori și cercetători.",
  contributep2:"În acest moment acceptăm doar contribuții de la utilizatori cu e-mailuri academice. Dacă nu aveți un e-mail academic, dar doriți să contribuiți, vă rugăm să <input type = \"button\" onclick = \"openBoard ('aboutProject');\" value = \"contactați-ne\" />.",
  contributestart:"Porniți încărcarea fotografiei obiect",
  newuserh3:"Înregistrare utilizator nou",
  newuseri1:"Nume",
  newuseri1l:" Numele și prenumele dvs. vor apărea lângă obiectele pe care le încărcați / adnotați.",
  newuseri2:"Nume de familie",
  newuseri3:"Instituție și țară",
  newuseri3l:" Afilierea dvs. și țara de locație.",
  newuseri4:"e-mail",
  newuseri4l:" Notă: numai e-mailurile academice sunt acceptate. Veți primi un link de confirmare.",
  newuseri5:"Introdu parola",
  newuseri5l:" Minim 8 caractere.",
  newuseri6:"repeta parola",
  newuseri6l:" Doar pentru a verifica dacă nu există greșeli de scriere.",
  newusersubmit:"Înregistrați un nou utilizator",
  uploadedobjects:"Obiecte existente încărcate:",
  nameobject:"Denumiți noul dvs. obiect",
  enterobjectname:"introduceți un nume de obiect nou",
  and:"și",
  cratephotospace:"creați un spațiu pentru fotografii",
  photolisting:"Listarea fotografiilor cu",
  nophotolist:"Nu ați încărcat încă fotografii pentru niciun obiect. Vă rugăm să încărcați fotografiile de mai jos.",
  uploadnewphotos:"Încărcați fișiere noi",
  startupload:"Începeți încărcarea",
  metadataobject:"Metadate pe obiectul fotografiat",
  objtitle:"Titlul obiectului",
  objtitlel:"Titlul obiectului",
  objdetails:"Detalii obiect",
  objdetailsl:"scurtă descriere a obiectului",
  objlocation:"Localizarea originală și actuală a obiectului",
  objlocationl:"de exemplu. CERN (în prezent la Universitatea din ...)",
  objyear:"Anul când a fost făcut obiectul (estimare)",
  objtags:"Etichete obiect",
  objsubmit:"Trimiteți fotografie pentru reconstrucția obiectelor 3D",
  newobjectspaceerror:"A apărut o eroare la crearea spațiului obiectului:",
  newobjectspacesuccess:"Spațiu creat cu succes pentru fotografiile unui obiect nou.",
  objsubmerr1:"EROARE: Trebuie să adăugați câteva <b> Etichete obiect </b> înainte de trimitere!",
  objsubmerr2:"EROARE: Numele obiectului trebuie să aibă lungimea de cel puțin 3 caractere",
  objsubmerr3:"EROARE: Introduceți cel puțin 10 caractere pentru descrierea obiectului.",
  objsubmerr4:"EROARE: Vă rugăm să introduceți locația obiectului (istoric, prezent sau companie de la care este disponibil).",
  objsubmerr5:"EROARE: Vă rugăm să introduceți anul de creare a obiectului (estimat).",
  delete:"șterge",
  question:"Întrebare",
  answers:"Răspunsuri",
  addeditanswer:"Adăugați sau editați răspunsul",
  clickdownvotel:"faceți clic pentru a vota în jos întrebarea sau răspunsul",
  clickupvotel:"faceți clic pentru a vota în sus întrebarea sau răspunsul",
  yourquestion:"Întrebarea dvs:",
  questiondesc:"Adăugați adnotare pe obiect și răspundeți textual la o întrebare.",
  submitquestion:"Trimiteți întrebarea",
  tooltipmainm:"Faceți clic pentru a deschide meniul principal",
  meniobject:"Obiect",
  questiontitle:"Titlul intrebarii",
  aboutfunding:"Finanțarea",
  about15:"Acest proiect este susținut de Știința și societatea La Diagonale Paris-Saclay.",
  size:"mărimea",
  color:"culoare",
  red:"roșu",
  green:"verde",
  blue:"albastru",
  orange:"portocale",
  magenta:"magenta",
  selectlicense:"Selectați licența pentru fișierele încărcate (modelul reconstruit va fi lansat sub aceeași licență)",
  read:"citit",
  licensetext:"licență",
  translated:"Tradus",
  transsee:"vezi traducerea în",
  transsource:"Text original",
  transseesource:"vezi originalul în",
  transimprove:"îmbunătăți traducerea",
  "fr":"limba franceza",
  "en":"Engleză",
  "es":"Spaniolă",
  "pt":"Portugheză",
  "de":"limba germana",
  "zh":"chinez",
  "ru":"Rusă",
  "ar":"arabic",
  "sv":"suedez",
  "nl":"Olandeză",
  "it":"Italiană",
  "ja":"japonez",
  "sr":"sârb",
  "cs":"ceh",
  "da":"danez",
  "sw":"Swahili",
  "hi":"hindi",
  "tr":"turc",
  "vi":"Vietnameză",
  "th":"Thai",
  "ko":"coreeană",
  "fa":"Farsi",
  "id":"Indoneziană",
  "cy":"Galeză",
  "el":"Greacă",
  "ro":"Română",
  "hu":"Maghiară",
  "pl":"Lustrui",
  transimprovetitle:"Îmbunătățiți traducerea",
  transnote:"Traducerea este un efort comun de traducere automată și feedback uman contribuit. Vă mulțumim că ați acordat timp pentru a contribui.",
  transorigin:"Original în",
  transsuggest:"Traducere în",
  transsubmit:"Trimiteți traducerea",
  press:"presa",
  forillustration:"pentru ilustrare",
  storylang:"Scris în limbă:",
  footer0:"Despre ResearchX3D",
  footer1:"Căutați obiecte, povești și întrebări",
  footer2:"Puneți o întrebare asupra obiectului",
  footer3:"Realitate augmentată",
  footer4:"Trimiteți obiectul",
  footer5:"Trimiteți povestea",
  footer_title1:"LINKURI RAPIDE",
  footer_title2:"LEGĂTURI SOCIALE",
  navigation:"Navigare",
  rotation:"a roti",
  move:"mutați sau",
  zoom:"măriți obiectul",
  clickForStory:"Faceți clic aici pentru a vedea povestea obiectului.",
  latexAdd:"sau adăugați la documentul LaTeX",
  latexPDF:"descărcați imaginea PDF aici",
  latexCode:"și adăugați cod mai jos.",
  latexCaption1:"Scanați codul QR sau introduceți",
  latexCaption2:"pentru a deschide obiectul.",
  contributeHeader:"DEVENIȚI CONTRIBUTOR",
  contribute1:"Urmăriți un scurt videoclip despre motivația din spatele ResearchX3D ...",
  contribute2:"... sau vedeți doar o introducere ResearchX3D de 4 minute.",
  contribute3:"ResearchX3D creează modele 3D din fotografiile dvs. ...",
  contribute4:"... dar puteți încărca și obiecte 3D deja create, de exemplu dintr-un software CAD.",
  contribute5:"Fiecare obiect are multe povești de spus. Prin crearea diferitelor tipuri de povești puteți:",
  contribute6:"Explicați o funcție și un design; sau",
  contribute7:"Testează cunoștințele cu un test; sau",
  contribute8:"Împărtășiți abilități și proceduri.",
  contribute9:"Iată cum vă ajută editorul ResearchX3D să creați o poveste.",
  clickvideo:"Faceți clic pentru a vedea videoclipul.",
  clickexample:"Faceți clic pentru a vedea un exemplu.",
  openstory:"Deschide această poveste",
  allsbj:"toate domeniile",
  showall:"arata tot",
  graphic:"grafic",
  figclick:"Găsiți povești și adnotări despre acest obiect",
  openar:"deschis în Realitate Augmentată",
meniagora:"Discuții comunitare - Agora",
r3dsummary:"<b> Ce este ResearchX3D? </b> O platformă comunitară deschisă pentru partajarea patrimoniului științific pentru a debloca valoarea creativă pentru viitor.",
agoraad:"<b> Sugerați și discutați </b> idei despre proiectul ResearchX3D și obțineți ajutor pe Agora <img class = 'link' src = '/link.png'> pentru discuții în comunitate."
};
