const lang_pt ={close:"Fechar",
loadingmodel:"Modelo de carregamento",
menistartpage:"Pagina inicial",
menifind:"Encontre objetos, histórias e perguntas",
meniadd:"Adicionar ou editar história do objeto",
meniask:"Faça uma pergunta no objeto",
meniupload:"Carregar fotos de objetos para o modelo 3D",
menishare:"Compartilhar objeto ou história",
meniar:"Realidade aumentada...",
meniaron:"Ativar o modo AR",
menimarker:"Imprimir marcadores RA",
menisupport:"Contato e suporte",
meniabout:"Sobre ResearchX3D",
menilogin:"Conecte-se",
menilogout:"Sair",
headfind:"Encontrar",
headfindt:"Pesquisa por aparelhos experimentais",
headcontribute:"Contribuir",
headcontributet:"Ajude-nos a aumentar a coleção de objetos!",
headaron:"AR ON",
headaront:"Clique para ativar a Realidade Aumentada",
headaroff:"AR DESLIGADO",
headarofft:"Clique para desativar o AR",
meni0_0:"Para estudantes",
meni0_1:"Encontrar. Tudo, desde experiências históricas até parafusos de ajuste finos.",
meni0_2:"Inspire-se. Expanda seu próprio espaço criativo pensando em diferentes possibilidades de design.",
meni1_0:"Para educadores",
meni1_1:"Usar. Mostrar em apresentações e cursos.",
meni1_2:"Crio. Anote objetos por sua própria descrição e compartilhe sua história sobre eles.",
meni2_0:"Para Pesquisadores",
meni2_1:"Contribuir. É preciso uma pausa para o café para compartilhar o aparelho que você passa diariamente com um mundo inteiro.",
meni2_2:"Explorar. Acompanhe o desenvolvimento de idéias de design.",
aboutheader:"Sobre o ResearchX3D.com",
aboutteam:"Equipe",
aboutcontact:"Contant",
about0:"Vamos compartilhar a herança científica para desbloquear valor criativo para o futuro! O aparato experimental é um elemento-chave na pesquisa científica. Tanto experimentos históricos quanto desenhos modernos são patrimônio valioso. Uma vez que esses objetos são compartilhados, eles se tornam um recurso útil, estimulando a criatividade das pessoas em todo o mundo. E agora é possível compartilhar o appparatus experimental durante a pausa para o café!",
about1:"O que ResearchX3D.com faz?",
about2:"Com base em <b> fotos carregadas por usuários </b> de equipamentos científicos de seus laboratórios, corredores de universidades e prateleiras de escritórios ...",
about3:"... nós <b> criamos modelos 3D </b> exploráveis ​​por qualquer pessoa no navegador da web.",
about4:"O ResearchX3D.com permite aumentar o impacto do patrimônio e acumular conhecimento no aparato:",
about5:"A marcação 3D de objetos com marcadores e setas no espaço 3D é feita facilmente através do editor on-line. As anotações podem ser acompanhadas com <b> descrições textuais e de áudio </b>;",
about6:"Grupos de etiquetas fazem histórias sobre os objetos. Os usuários podem <b> encontrar histórias com base em seu nível de conhecimento </b>. Os usuários em todo o espectro são abordados: do ensino fundamental e médio, através de descrições detalhadas no nível universitário, até discussões avançadas sobre design de appartus para nível de doutorado / pesquisa;",
about7:"Todos podem fazer uma pergunta. As <b> perguntas e respostas </b> usam rótulos 3D para <b> descrições \"apontar e contar\" </b>. As melhores respostas são votadas pelos usuários;",
about8:"Os objetos podem ser vistos na <b> realidade aumentada </b>, permitindo que todos vejam aparelhos experimentais em sua mesa;",
about9:"Toda a funcionalidade é trazida através da interface da web (sem instalação, independente da plataforma), permitindo <b> compartilhamento fácil </b> de objetos e histórias enviando links para colegas e amigos.",
about10:"A plataforma ResearchX3D.com visa",
about12:"Físicos, atualmente bolsistas de pós-doutorado Marie Curie no <a href=\"https://www.institutoptique.fr/\"> Institute d'Optique, Palaiseau, França </a>.",
about13:"Entre em contato conosco em <a href='mailto:contact@researchx3d.com?subject=Feedback'> contact@researchx3d.com </a>.",
aboutli0:"Preservar modelos de objetos de patrimônio científico e técnico;",
aboutli1:"Registre descrições de design pelos pesquisadores para proteger idéias e truques de design para o futuro;",
aboutli2:"Apresentar a herança de uma maneira que inspire e expanda o espaço criativo do público em todo o espectro, do ensino ao nível da pesquisa; e",
aboutli3:"Democratize o acesso ao design de aparelhos experimentais, pegando algo anteriormente acessível apenas a poucos sortudos e compartilhando-o pelo mundo inteiro.",
findobject:"Procurar objeto ...",
findstory:"... e depois escolha história / anotação",
findquestion:"... ou veja perguntas e respostas",
filtersubject:"Filtrar por área de assunto:",
filterknowledgelevel:"Filtrar por nível de conhecimento:",
shareqr:"Compartilhe aparatos e histórias experimentais com link direto ou código QR",
click2copy:"clique para copiar o link",
saveqr:"Salvar imagem do código QR",
askquestion:"Faça uma pergunta",
share:"compartilhar",
addmodifystory:"Adicione / modifique sua história",
depositedby:"Depositado por",
logoutsuccess:"Você foi desconectado com sucesso!",
objectannotation:"Anotação de objeto:",
objectannotationt:"clique para selecionar anotações diferentes",
by:"por",
location:"Localização",
details:"Detalhes",
tags:"Tag",
forthisobject:"para este objeto",
object:"objeto",
previousm:"Seção anterior",
nextm:"Próxima seção",
or:"ou",
moto:"Compartilhando a herança científica para desbloquear valor criativo para o futuro.",
pleaselogin:"Para continuar, faça o login",
enteremail:"Introduzir email",
enterpassword:"Digite a senha",
login:"Conecte-se",
forgotpassword:"Esqueceu a senha?",
cancel:"Cancelar",
newuser:"Novo usuário?",
loginnote1:"Para adicionar objetos, anotações e fazer e responder a perguntas que você precisa fazer login.",
loginnote2:"Para salvar as alterações, você precisa primeiro confirmar sua identidade e pressionar 'Salvar'.",
add:"Adicionar, acrescentar",
remove:"retirar",
finally:"Finalmente",
annotation:"segmento de história",
savestory:"salvar história",
level1:"escola primaria",
level2:"colegial",
level3:"universidade (graduação)",
level4:"Doutorado / pesquisa",
addmarker:"Adicionar marcador",
addarrow:"adicionar flecha",
textual:"textual",
audio:"audio",
addexp:"Adicionar, acrescentar",
explanation:"descrição para esta anotação",
marker:"marcador",
arrow:"seta",
at:"às",
angle:"ângulo",
arintro:"Coloque o marcador <a href=\"/print_marker.pdf\"><img src = \"\\ar_marker_small.png\" align = \"middle\" si></a> na visualização da câmera. <br/> Para navegar pela história, clique nas setas esquerda e direita.",
noexistingaudio:"Nenhuma descrição de áudio existente.",
newupload:"Novo upload",
newrecording:"Nova gravação",
recordsound:"Comece a gravar",
stopbutton:"Pare de gravar",
storytitle:"Título da história",
storydesc:"Breve resumo desta história do objeto ...",
adddesc:"Adicionar descrição para esta anotação ...",
arrowadjust:"Ajuste a posição e orientação da seta e depois",
markeradjust:"Ajuste a posição do marcador e depois",
savemarker:"salvar marcador",
savearrow:"salvar flecha",
audiodesc:"Descrição do áudio:",
clicktochangelan:"Clique para mudar o idioma",
getarmarkers:"obter marcadores de realidade aumentada",
contributeh2:"Contribuir com aparelhos ... é preciso um intervalo para o café!",
contributeh3_1:"Como funciona?",
contributeh3_2:"Pronto? Começa aqui...",
contributeli1:"<b> Você carrega ~ 30 fotos do aparato experimental que está documentando. Tente tirar fotografias de modo que cada ponto do objeto seja visto em 3-6 fotografias de ângulos diferentes. Mais fotos é melhor que menos fotos!",
contributeli2:"<b> Criamos modelo 3D a partir de suas fotos </b>, usando software de fotogrametria, e o colocamos online no ResearchX3D",
contributeli3:"<b> Todos </b> podem explorar, fazer anotações, fazer perguntas e compartilhar um modelo 3D reconstruído quando estiver online. Você como proprietário receberá o primeiro convite para adicionar anotação e história, que serão destacadas como anotação original.",
contributep1:"Isso é tudo, o patrimônio da pesquisa está disponível em todo o mundo, para outros estudantes, educadores e pesquisadores.",
contributep2:"No momento, aceitamos contribuições apenas de usuários com emails acadêmicos. Caso você não tenha um e-mail acadêmico, mas gostaria de contribuir, por favor <input type=\"button\" onclick=\"openBoard('aboutProject');\" value=\"entre em contato\" />.",
contributestart:"Iniciar o upload de fotos do objeto",
newuserh3:"Registo de novo utilizador",
newuseri1:"Nome",
newuseri1l:" Seu nome e sobrenome aparecerão ao lado dos objetos que você enviar / anotar.",
newuseri2:"Sobrenome",
newuseri3:"Instituição e país",
newuseri3l:" Sua afiliação e país de localização.",
newuseri4:"o email",
newuseri4l:" Nota: somente emails acadêmicos são aceitos. Você receberá um link de confirmação.",
newuseri5:"Digite a senha",
newuseri5l:" Mínimo de 8 caracteres.",
newuseri6:"Repita a senha",
newuseri6l:" Só para verificar se não há erros de digitação.",
newusersubmit:"Registrar um novo usuário",
uploadedobjects:"Objetos carregados existentes:",
nameobject:"Nomeie seu novo objeto",
enterobjectname:"insira o novo nome do objeto",
and:"e",
cratephotospace:"criar espaço para fotografias",
photolisting:"Listagem de fotografias de",
nophotolist:"Você ainda não enviou fotos para nenhum objeto. Envie as fotografias dos objetos abaixo.",
uploadnewphotos:"Carregar novos arquivos",
startupload:"Iniciar envio",
metadataobject:"Metadados no objeto fotografado",
objtitle:"Título do objeto",
objtitlel:"Título do objeto",
objdetails:"Detalhes do objeto",
objdetailsl:"descrição curta do objeto",
objlocation:"Localização original e atual do objeto",
objyear:"Ano em que o objeto foi feito (estimativa)",
objtags:"Tags de objeto",
objsubmit:"Enviar foto para reconstrução de objeto 3D",
newobjectspaceerror:"Ocorreu um erro ao criar seu espaço de objeto:",
newobjectspacesuccess:"Espaço criado com sucesso para fotografias de um novo objeto.",
objsubmerr1:"ERRO: Você precisa adicionar algumas <b> tags de objeto </b> antes do envio!",
objsubmerr2:"ERRO: o nome do objeto deve ter pelo menos 3 caracteres",
objsubmerr3:"ERRO: Digite pelo menos 10 caracteres para a descrição do objeto.",
objsubmerr4:"ERRO: Digite a localização do objeto (histórico, presente ou empresa da qual ele está disponível).",
objsubmerr5:"ERRO: Digite o ano de criação do objeto (estimado).",
delete:"excluir",
question:"Pergunta, questão",
answers:"Respostas",
addeditanswer:"Adicione ou edite sua resposta",
clickdownvotel:"clique para diminuir a votação da pergunta ou resposta",
clickupvotel:"clique para votar ou responder à pergunta inicial",
yourquestion:"Sua pergunta:",
questiondesc:"Adicione anotação no objeto e descreva textualmente os detalhes da pergunta.",
submitquestion:"Enviar pergunta",
tooltipmainm:"Clique para abrir o menu principal",
meniobject:"Objeto",
questiontitle:"Título da questão",
aboutfunding:"Financiamento",
about15:"Projeto apoiado pela Ciência e Sociedade de La Diagonale Paris-Saclay.",
size:"Tamanho",
color:"cor",
red:"vermelho",
green:"verde",
blue:"azul",
orange:"laranja",
magenta:"magenta",
selectlicense:"Selecione a licença para os arquivos enviados (o modelo reconstruído será lançado sob a mesma licença)",
read:"ler",
licensetext:"licença",
translated:"Traduzido",
transsee:"ver tradução em",
transsource:"Texto original",
transseesource:"ver original em",
transimprove:"melhorar a tradução",
"fr":"francês",
"en":"Inglês",
"es":"espanhol",
"pt":"português",
"de":"alemão",
"zh":"chinês",
"ru":"russo",
"ar":"árabe",
"sv":"sueco",
"nl":"holandês",
"it":"italiano",
"ja":"japonês",
"sr":"sérvio",
"cs":"tcheco",
"da":"dinamarquês",
"sw":"suaíli",
"hi":"hindi",
"tr":"turco",
"vi":"vietnamita",
"th":"tailandês",
"ko":"coreano",
"fa":"farsi",
"id":"indonésio",
"cy":"galês",
"el":"grego",
"ro":"romena",
"hu":"húngaro",
"pl":"polonês",
transimprovetitle:"Melhore a tradução",
transnote:"A tradução é um esforço conjunto da tradução automática e do feedback humano. Obrigado por dedicar um tempo para contribuir.",
transorigin:"Original em",
transsuggest:"Tradução em",
transsubmit:"Enviar tradução",
press:"Toque",
forillustration:"para ilustração",
storylang:"Escrito no idioma:",
footer0:"Sobre a ResearchX3D",
footer1:"Pesquise objetos, histórias e perguntas",
footer2:"Perguntar sobre o objeto",
footer3:"Realidade aumentada",
footer4:"Enviar objeto",
footer5:"Enviar história",
footer_title1:"LINKS RÁPIDOS",
footer_title2:"LINKS SOCIAIS",
navigation:"Navegação",
rotation:"Girar",
move:"mover ou",
zoom:"ampliar o objeto",
clickForStory:"Clique aqui para ver a história do objeto.",
latexAdd:"ou adicione ao documento LaTeX",
latexPDF:"faça o download da imagem em PDF aqui",
latexCode:"e adicione o código abaixo.",
latexCaption1:"Digitalize o código QR ou digite",
latexCaption2:"para abrir o objeto.",
contributeHeader:"TORNE-SE UM CONTRIBUIDOR",
contribute1:"Assista a um pequeno vídeo sobre a motivação por trás do ResearchX3D ...",
contribute2:"... ou veja apenas uma introdução de 4 minutos no ResearchX3D.",
contribute3:"ResearchX3D cria modelos 3D a partir de suas fotografias ...",
contribute4:"... mas você também pode carregar objetos 3D já criados, por exemplo de um software CAD.",
contribute5:"Cada objeto tem muitas histórias para contar. Ao criar diferentes tipos de histórias, você pode:",
contribute6:"Explique uma função e um design; ou",
contribute7:"Teste o conhecimento com um questionário; ou",
contribute8:"Compartilhe habilidades e procedimentos.",
contribute9:"Veja como o editor ResearchX3D ajuda você a criar uma história.",
clickvideo:"Clique aqui para ver o vídeo.",
clickexample:"Clique aqui para ver um exemplo",
openstory:"Abra esta história",
allsbj:"todas as áreas temáticas",
showall:"mostre tud",
graphic:"gráfico",
figclick:"Encontre histórias e anotações sobre este objeto",
openar:"abrir em Realidade Aumentada",
meniagora:"Discussões da comunidade - Agora",
r3dsummary:"<b> O que é ResearchX3D? </b> Uma plataforma de comunidade aberta para compartilhar patrimônio científico para desbloquear valor criativo para o futuro.",
agoraad:"<b> Sugira e discuta </b> ideias sobre o projeto ResearchX3D e obtenha ajuda em nosso Agora <img class = 'link' src = '/link.png'> para discussões da comunidade."
};
