const lang_tr ={close:"Kapat",
loadingmodel:"Yükleme modeli",
menistartpage:"Anasayfa",
menifind:"Nesneleri, hikayeleri ve soruları bulun",
meniadd:"Nesne hikayesi ekle veya düzenle",
meniask:"Nesne üzerinde soru sor",
meniupload:"3B model için nesne fotoğrafları yükleyin",
menishare:"Nesneyi veya hikayeyi paylaşın",
meniar:"Arttırılmış gerçeklik...",
meniaron:"AR modunu aç",
menimarker:"AR işaretleyicileri yazdır",
menisupport:"İletişim desteği",
meniabout:"ResearchX3D hakkında",
menilogin:"Oturum aç",
menilogout:"Çıkış Yap",
headfind:"bulmak",
headfindt:"Deneysel cihazları ara",
headcontribute:"Katkıda bulunmak",
headcontributet:"Nesnelerin koleksiyonunu büyütmemize yardımcı olun!",
headaron:"AR AÇIK",
headaront:"Artırılmış Gerçeklik açmak için tıklayın",
headaroff:"AR KAPALI",
headarofft:"AR'yi kapatmak için tıklayın",
meni0_0:"ÖĞRENCILER IÇIN",
meni0_1:"Bulun. Tarihsel deneylerden ince ayar vidalarına kadar her şey.",
meni0_2:"İlham almak. Farklı tasarım olanaklarını düşünerek kendi yaratıcı alanınızı genişletin.",
meni1_0:"EĞITIMCILER İÇINn",
meni1_1:"Kullan. Sunumlarda ve kurslarda göster.",
meni1_2:"Yaratmak, yapmak, tasarlamak, üretmek. Nesneleri kendi tanımınıza göre açıklama ekleyin ve öykülerinizi onlar hakkında paylaşın.",
meni2_0:"ARAŞTIRMACILAR İÇIN",
meni2_1:"Katkıda bulunmak. Her gün geçirdiğiniz cihazı bütün dünyayla paylaşmak bir kahve molası veriyor.",
meni2_2:"Keşfetmek. Tasarım fikirlerinin gelişimini takip edin.",
aboutheader:"ResearchX3D.com Hakkında",
aboutteam:"Takım",
aboutcontact:"contant",
about0:"Geleceğe yönelik yaratıcı değeri ortaya çıkarmak için bilimsel mirası paylaşalım! Deneysel aparat, bilimsel araştırmada anahtar unsurdur. Hem tarihi deneyler hem de modern tasarımlar değerli bir mirastır. Bu nesneler paylaşıldıktan sonra, dünyadaki insanların yaratıcılığını teşvik ederek faydalı bir kaynak haline gelirler. Ve şimdi kahve molası sırasında deneysel aparatları paylaşmak mümkün!",
about1:"ResearchX3D.com ne yapar?",
about2:"Laboratuvarlarından, üniversite koridorlarından ve ofis raflarından bilimsel aygıtın <b> kullanıcı tarafından yüklenen fotoğraflarına </b> göre ...",
about3:"... web tarayıcısındaki herkes tarafından keşfedilebilen <b> 3D modeller yaratıyoruz </b>.",
about4:"Ardından ResearchX3D.com, bir kişinin mirasa olan etkisini arttırmasına ve cihaz üzerinde bilgi biriktirmesine izin veriyor:",
about5:"3B alanda işaretçileri ve okları olan nesnelerin <b> 3B etiketlemesi </b> çevrimiçi editör üzerinden kolayca yapılabilir. Ek açıklamalara <b> metinsel ve sesli açıklamalar </b>;",
about6:"Etiket grupları nesnelerle ilgili hikayeler oluşturur. Kullanıcılar <b> bilgi düzeylerine göre hikayeler bulabilirler </b>. Spektrumun karşısındaki kullanıcılar kapsanmaktadır: ilköğretim ve lise öğretiminden, üniversite düzeyinde ayrıntılı açıklamalara, doktora / araştırma düzeyi için appartus tasarımı üzerine ileri görüşmelere;",
about7:"Herkes bir soru sorabilir. Her iki <b> soru ve cevap </b> da <b> \"göster ve anlat\" tanımları </b> için 3B etiketleri kullanır. En iyi cevaplar kullanıcılar tarafından beğenilir;",
about8:"Nesneler, <b> artırılmış gerçeklik </b> te görülebilir ve herkesin masasında deneysel bir araç görmesini sağlar;",
about9:"Tüm işlevler, web arayüzü aracılığıyla (kurulum, platformdan bağımsız) iş arkadaşlarına ve arkadaşlarına bağlantılar göndererek nesnelerin ve hikayelerin <b> kolayca paylaşılmasını </b> sağlar.",
about10:"ResearchX3D.com platformunun amacı",
about12:"Fizikçiler, şu anda Marie Curie doktora sonrası araştırmacıları <a href=\"https://www.institutoptique.fr/\"> Institute d'Optique, Palaiseau, Fransa </a> 'da.",
about13:"<a href='mailto:contact@researchx3d.com?subject=Feedback'> contact@researchx3d.com </a> adresinden bize ulaşın.",
aboutli0:"Bilimsel ve teknik mirasın nesne modellerini korumak;",
aboutli1:"Tasarım fikirlerini ve püf noktalarını gelecek için korumak amacıyla araştırmacılar tarafından tasarım açıklamalarını kaydedin;",
aboutli2:"Öğretmenlikten araştırma seviyesine, spektrumdaki izleyicilerdeki yaratıcı alanı ilham alan ve genişleten bir şekilde mevcut mirası sunun; ve",
aboutli3:"Önceden sadece birkaç şanslı için erişilebilir olan bir şeyi alarak ve tüm dünyayı paylaşarak deneysel cihaz tasarımına erişimi demokratikleştirin.",
findobject:"Nesne ara ...",
findstory:"... ve ardından hikaye / açıklama seçin",
findquestion:"... veya soruları ve cevapları gör",
filtersubject:"Konu alanına göre filtrele:",
filterknowledgelevel:"Bilgi seviyesine göre filtrele:",
shareqr:"Doğrudan bağlantı veya QR kodu ile deneysel cihaz ve hikaye paylaşın",
click2copy:"bağlantıyı kopyalamak için tıklayın",
saveqr:"QR kod görüntüsünü kaydet",
askquestion:"Soru sor",
share:"Paylaş",
addmodifystory:"Hikayenizi ekleyin / değiştirin",
depositedby:"Tarafından yatırılan",
logoutsuccess:"Başarılı bir şekilde çıkış yaptınız!",
objectannotation:"Nesne ek açıklaması:",
objectannotationt:"farklı açıklama seçmek için tıklayın",
by:"tarafından",
location:"yer",
details:"ayrıntılar",
tags:"Etiketler",
forthisobject:"bu nesne için",
object:"nesne, cisim",
previousm:"Önceki bölüm",
nextm:"Sonraki bölüm",
or:"veya",
moto:"Geleceğe yönelik yaratıcı değeri ortaya çıkarmak için bilimsel mirası paylaşmak.",
pleaselogin:"Devam etmek için lütfen giriş yapınız",
enteremail:"E-posta giriniz",
enterpassword:"Şifre girin",
login:"Oturum aç",
forgotpassword:"Parolanızı mı unuttunuz?",
cancel:"İptal etmek",
newuser:"Yeni kullanıcı?",
loginnote1:"Nesne, açıklama eklemek ve giriş yapmak için ihtiyacınız olan soruları sorup cevaplamak için.",
loginnote2:"Değişiklikleri kaydetmek için önce kimliğinizi onaylamanız ve ardından 'Kaydet' düğmesine basmanız gerekir.",
add:"Eklemek",
remove:"Kaldır",
finally:"En sonunda",
annotation:"hikaye bölümü",
savestory:"hikayeyi kaydet",
level1:"ilkokul",
level2:"lise",
level3:"üniversite (lisans)",
level4:"Doktora / Araştırma",
addmarker:"İşaretçi ekle",
addarrow:"ok ekle",
textual:"metinsel",
audio:"ses",
addexp:"Eklemek",
explanation:"bu ek açıklamanın açıklaması",
marker:"işaretleyici",
arrow:"ok",
at:"en",
angle:"açı",
arintro:"Kamera görüntüsüne <a href=\"/print_marker.pdf\"><img src = \"\\ar_marker_small.png\" align = \"middle\" si></a> işaretçisini yerleştirin. <br/> Hikayede gezinmek için sola ve sağa okları tıklayın.",
noexistingaudio:"Mevcut ses açıklaması yok.",
newupload:"Yeni yükleme",
newrecording:"Yeni kayıt",
recordsound:"Kayda başla",
stopbutton:"Kaydetmeyi bırak",
storytitle:"Öykü başlığı",
storydesc:"Bu nesne hikayesinin kısa özeti ...",
adddesc:"Bu ek açıklama için açıklama ekle ...",
arrowadjust:"Ok konumunu ve yönünü ayarlayın ve ardından",
markeradjust:"İşaretçi konumunu ve ardından",
savemarker:"işaretçiyi kaydet",
savearrow:"oku kaydet",
audiodesc:"Sesli açıklama:",
clicktochangelan:"Dili değiştirmek için tıklayın",
getarmarkers:"artırılmış gerçeklik belirteçleri almak",
contributeh2:"Katkı aparatı ... bir kahve molası alır!",
contributeh3_1:"Nasıl çalışır?",
contributeh3_2:"Hazır? Buradan başlayın...",
contributeli1:"Belgelemekte olduğunuz deney cihazının ~ 30 fotoğrafını <b> siz </b> yüklersiniz. Nesnelerdeki her noktanın 3-6 fotoğrafta farklı açılardan görüleceği şekilde fotoğraf çekmeyi deneyin. Daha fazla fotoğraf, daha az fotoğraftan daha iyidir!",
contributeli2:"<b> Fotoğraflarınızdan 3B model oluşturuyoruz </b>, fotogrametri yazılımı kullanarak ve çevrimiçi olarak ResearchX3D'ye yerleştirdik",
contributeli3:"<b> Herkes </b> çevrimiçi olduktan sonra keşif edebilir, açıklama ekleyebilir, soru sorabilir ve yeniden oluşturulmuş 3B modeli paylaşabilir. Sahip olarak, ek açıklama ve hikaye eklemek üzere ilk davetiyeyi alacaksınız; bunlar orijinal ek açıklama olarak vurgulanacak.",
contributep1:"Hepsi bu kadar, araştırma mirası, diğer öğrenciler, eğitimciler ve araştırmacılar için dünya çapında beklenebilir.",
contributep2:"Şu anda yalnızca akademik e-postaları olan kullanıcıların katkılarını kabul ediyoruz. Akademik e-postanız yoksa ancak katkıda bulunmak istemeniz durumunda lütfen <input type = \"button\" onclick = \"openBoard ('aboutProject');\" value = \"bize ulaşın\" />.",
contributestart:"Nesne fotoğraf yüklemesini başlat",
newuserh3:"Yeni kullanıcı kaydı",
newuseri1:"isim",
newuseri1l:" Adınız ve soyadınız yüklediğiniz / not aldığınız nesnelerin yanında görünecektir.",
newuseri2:"Soyadı",
newuseri3:"Kurum ve ülke",
newuseri3l:" Üyeliğiniz ve bulunduğunuz ülke.",
newuseri4:"E-posta",
newuseri4l:" Not: Sadece akademi e-postalar kabul edilir. Onay linki alacaksınız.",
newuseri5:"Şifre girin",
newuseri5l:" En az 8 karakter.",
newuseri6:"Şifreyi tekrar girin",
newuseri6l:" Sadece kontrol etmek için yazım hatası yok.",
newusersubmit:"Yeni bir kullanıcı kaydet",
uploadedobjects:"Mevcut yüklenen nesneler:",
nameobject:"Yeni nesnenize isim verin",
enterobjectname:"yeni nesne adı girin",
and:"ve",
cratephotospace:"fotoğraflar için alan yaratın",
photolisting:"Fotoğrafların listesi",
nophotolist:"Hiçbir nesne için henüz fotoğraf yüklemediniz. Lütfen aşağıdaki nesne fotoğraflarını yükleyin.",
uploadnewphotos:"Yeni dosyalar yükle",
startupload:"Yüklemeye başla",
metadataobject:"Fotoğraflanan nesnenin meta verileri",
objtitle:"Nesne başlığı",
objtitlel:"Nesne başlığı",
objdetails:"Nesne ayrıntıları",
objdetailsl:"kısa nesne açıklaması",
objlocation:"Nesnenin orijinal ve şimdiki konumu",
objyear:"Nesnenin yapıldığı yıl (tahmini)",
objtags:"Nesne etiketleri",
objsubmit:"3B nesneyi yeniden yapılandırmak için fotoğraf gönderin",
newobjectspaceerror:"Nesne alanınızı yaratırken bir hata oluştu:",
newobjectspacesuccess:"Yeni bir nesnenin fotoğrafları için başarıyla alan oluşturuldu.",
objsubmerr1:"HATA: Gönderilmeden önce bazı <b> Nesne etiketleri </b> eklemelisiniz!",
objsubmerr2:"HATA: Nesne adının uzunluğu en az 3 karakter olmalı",
objsubmerr3:"HATA: Nesne açıklaması için en az 10 karakter girin.",
objsubmerr4:"HATA: Lütfen nesnenin yerini girin (tarihi, şimdiki veya hazır olduğu şirket).",
objsubmerr5:"HATA: Lütfen nesne oluşturma yılını girin (tahmini).",
delete:"silmek",
question:"Soru",
answers:"Cevaplar",
addeditanswer:"Cevabınızı Ekleyin veya Düzenleyin",
clickdownvotel:"soru veya yanıtı indirmek için tıklayın",
clickupvotel:"soruyu veya yanıtı yükseltmek için tıklayın",
yourquestion:"Senin sorun:",
questiondesc:"Nesneye açıklama ekleyin ve sorunun metinsel ayrıntılarını açıklayın.",
submitquestion:"Soru gönder",
tooltipmainm:"Ana menüyü açmak için tıklayın",
meniobject:"Nesne, cisim",
questiontitle:"Soru başlığı",
aboutfunding:"Finansman",
about15:"La Diagonale Paris-Saclay Bilim ve Toplum tarafından desteklenen proje.",
size:"boyut",
color:"renk",
red:"kırmızı",
green:"yeşil",
blue:"mavi",
orange:"Portakal",
magenta:"eflatun",
selectlicense:"Yüklenen dosyalar için lisans seçin (yeniden oluşturulmuş model aynı lisans altında yayınlanacaktır)",
read:"okumak",
licensetext:"lisans",
translated:"Çeviri",
transsee:"çeviriye bak",
transsource:"Orjinal metin",
transseesource:"orijinali görmek",
transimprove:"çeviriyi geliştir",
"fr":"Fransızca",
"en":"ingilizce",
"es":"İspanyol",
"pt":"portugese",
"de":"Almanca",
"zh":"Çince",
"ru":"Rusça",
"ar":"Arapça",
"sv":"İsveççe",
"nl":"Flemenkçe",
"it":"İtalyan",
"ja":"Japonca",
"sr":"Sırpça",
"cs":"Çek",
"da":"Danimarkalı",
"sw":"svahili",
"hi":"Hintçe",
"tr":"Türk",
"vi":"Vietnam",
"th":"Tayland",
"ko":"Koreli",
"fa":"Farsça",
"id":"Endonezya",
"cy":"sözünü tutmamak",
"el":"Yunan",
"ro":"Romence",
"hu":"Macarca",
"pl":"Lehçe",
transimprovetitle:"Çeviriyi geliştirin",
transnote:"Çeviri, makine çevirisi ve insanın katkıda bulunduğu geri bildirimin bir araya gelmesidir. Katkıda bulunmak için zaman ayırdığınız için teşekkür ederiz.",
transorigin:"Orijinal",
transsuggest:"Çeviri",
transsubmit:"Çeviri gönderin",
press:"Dokunma",
forillustration:"gösterim için",
storylang:"Dilde yazılmış:",
footer0:"ResearchX3D Hakkında",
footer1:"Nesneleri, hikayeleri ve soruları arama",
footer2:"Nesne hakkında soru sor",
footer3:"Arttırılmış gerçeklik",
footer4:"Nesneyi gönder",
footer5:"Hikaye gönder",
footer_title1:"HIZLI LİNKLER",
footer_title2:"SOSYAL LİNKLER",
navigation:"navigasyon",
rotation:"döndürmek",
move:"hareket et veya",
zoom:"nesneyi yakınlaştır",
clickForStory:"Nesnenin öyküsünü görmek için buraya tıklayın.",
latexAdd:"veya LaTeX belgesine ekleyin",
latexPDF:"PDF görüntüsünü buradan indirin",
latexCode:"ve kodu aşağıya ekleyin.",
latexCaption1:"QR kodunu tarayın veya girin",
latexCaption2:"nesneyi açmak için.",
contributeHeader:"KATKIDA BULUNAN OLUN",
contribute1:"ResearchX3D'nin arkasındaki motivasyon hakkında kısa bir video izleyin ...",
contribute2:"... veya sadece 4 dakikalık ResearchX3D girişine bakın.",
contribute3:"ResearchX3D, fotoğraflarınızdan 3 boyutlu modeller oluşturur ...",
contribute4:"... ancak önceden oluşturulmuş 3B nesneleri, örneğin bir CAD yazılımından da yükleyebilirsiniz.",
contribute5:"Her nesnenin anlatacak birçok hikayesi vardır. Farklı türde hikayeler oluşturarak şunları yapabilirsiniz:",
contribute6:"Bir işlevi ve tasarımı açıklayın; veya",
contribute7:"Bir sınavla bilgiyi test edin; veya",
contribute8:"Becerileri ve prosedürleri paylaşın.",
contribute9:"ResearchX3D editörünün bir hikaye oluşturmanıza nasıl yardımcı olacağı aşağıda açıklanmıştır.",
clickvideo:"Videoyu görmek için buraya tıklayın.",
clickexample:"Bir örnek görmek için burayı tıklayın",
openstory:"Bu hikayeyi açın",
allsbj:"tüm konu alanları",
showall:"hepsini göster",
graphic:"grafik",
figclick:"Bu nesne hakkında hikayeler ve ek açıklamalar bulun",
openar:"Artırılmış Gerçeklikte aç",
meniagora:"Topluluk tartışmaları - Agora",
r3dsummary:"<b> ResearchX3D nedir? </b> Gelecek için yaratıcı değeri ortaya çıkarmak için bilimsel mirası paylaşmak için açık bir topluluk platformu.",
agoraad:"ResearchX3D projesi hakkında fikirler <b> önerin ve tartışın </b> ve Topluluk Tartışmaları için Agora <img class = 'link' src = '/link.png'> konusunda yardım alın."
};
