const lang_it ={close:"Vicino",
loadingmodel:"Caricamento modello",
menistartpage:"Homepage",
menifind:"Trova oggetti, storie e domande",
meniadd:"Aggiungi o modifica la trama dell'oggetto",
meniask:"Fai una domanda sull'oggetto",
meniupload:"Carica foto di oggetti per il modello 3D",
menishare:"Condividi oggetto o storia",
meniar:"Realtà aumentata...",
meniaron:"Attiva la modalità AR",
menimarker:"Stampa marcatori AR",
menisupport:"Contatta il supporto",
meniabout:"Di ResearchX3D",
menilogin:"Accesso",
menilogout:"Disconnettersi",
headfind:"Trova",
headfindt:"Cerca apparati sperimentali",
headcontribute:"Contribuire",
headcontributet:"Aiutaci a far crescere la collezione di oggetti!",
headaron:"AR ON",
headaront:"Fai clic per attivare la realtà aumentata",
headaroff:"AR OFF",
headarofft:"Fare clic per disattivare AR",
meni0_0:"PER STUDENTI",
meni0_1:"Trova. Tutto, dagli esperimenti storici alle viti di regolazione fine.",
meni0_2:"Fatti ispirare. Espandi il tuo spazio creativo pensando a diverse possibilità di design.",
meni1_0:"PER EDUCATORI",
meni1_1:"Uso. Mostra in presentazioni e corsi.",
meni1_2:"Creare. Annota gli oggetti con la tua descrizione e condividi la tua storia su di essi.",
meni2_0:"PER I RICERCATORI",
meni2_1:"Contribuire. Ci vuole una pausa caffè per condividere l'apparato che stai passando ogni giorno con un mondo intero.",
meni2_2:"Esplorare. Traccia lo sviluppo di idee di design.",
aboutheader:"Informazioni su ResearchX3D.com",
aboutteam:"Squadra",
aboutcontact:"Contant",
about0:"Condividiamo il patrimonio scientifico per sbloccare il valore creativo per il futuro! L'apparato sperimentale è un elemento chiave nella ricerca scientifica. Sia gli esperimenti storici che i design moderni sono patrimonio prezioso. Una volta condivisi, questi oggetti diventano utili risorse, stimolando la creatività delle persone in tutto il mondo. E ora è possibile condividere l'apparato sperimentale durante la pausa caffè!",
about1:"Cosa fa ResearchX3D.com?",
about2:"Basato su <b> fotografie caricate dall'utente </b> di apparati scientifici dai loro laboratori, corridoi universitari e scaffali degli uffici ...",
about3:"... <b> creiamo modelli 3D </b> esplorabili da chiunque nel browser web.",
about4:"ResearchX3D.com consente quindi di migliorare l'impatto del patrimonio e accumula conoscenze sugli apparati:",
about5:"<b> Etichettatura 3D </b> di oggetti con marcatori e frecce nello spazio 3D è facilmente eseguibile tramite l'editor online. Le annotazioni possono essere accompagnate da <b> descrizioni testuali e audio </b>;",
about6:"Gruppi di etichette creano storie sugli oggetti. Gli utenti possono <b> trovare storie in base al loro livello di conoscenza </b>. Gli utenti di tutto lo spettro sono coperti: dalla scuola elementare e l'insegnamento delle scuole superiori, attraverso descrizioni dettagliate a livello universitario, a discussioni avanzate sulla progettazione di appartamenti per dottorato di ricerca / livello di ricerca;",
about7:"Tutti possono porre una domanda. Entrambe le <b> domande e risposte </b> utilizzano etichette 3D per <b> descrizioni \"point-and-tell\" </b>. Le migliori risposte sono votate dagli utenti;",
about8:"Gli oggetti possono essere visti nella <b> realtà aumentata </b>, permettendo a tutti di vedere apparati sperimentali sulla propria scrivania;",
about9:"Tutte le funzionalità sono portate attraverso l'interfaccia web (nessuna installazione, indipendente dalla piattaforma), che consente la <b> facile condivisione </b> di oggetti e storie inviando collegamenti a colleghi e amici.",
about10:"La piattaforma ResearchX3D.com mira a",
about12:"Fisici, attualmente borsisti post-dottorato Marie Curie presso <a href=\"https://www.institutoptique.fr/\"> Institute d'Optique, Palaiseau, Francia </a>.",
about13:"Contattaci a <a href='mailto:contact@researchx3d.com?subject=Feedback'> contact@researchx3d.com </a>.",
aboutli0:"Preservare i modelli di oggetti del patrimonio scientifico e tecnico;",
aboutli1:"Registrare le descrizioni dei progetti da parte dei ricercatori per salvaguardare idee e trucchi per il futuro;",
aboutli2:"Patrimonio attuale in un modo che ispira ed espande lo spazio creativo nel pubblico attraverso gli spettri, dall'insegnamento al livello di ricerca; e",
aboutli3:"Democratizzare l'accesso alla progettazione di apparati sperimentali, prendendo qualcosa di precedentemente accessibile solo a pochi fortunati e condividendolo con tutto il mondo.",
findobject:"Cerca oggetto ...",
findstory:"... quindi scegli storia / annotazione",
findquestion:"... o vedi domande e risposte",
filtersubject:"Filtra per area tematica:",
filterknowledgelevel:"Filtra per livello di conoscenza:",
shareqr:"Condividi apparati e storie sperimentali con link diretto o codice QR",
click2copy:"fai clic per copiare il link",
saveqr:"Salva l'immagine del codice QR",
askquestion:"Fai una domanda",
share:"Condividere",
addmodifystory:"Aggiungi / modifica la tua storia",
depositedby:"Depositato da",
logoutsuccess:"Sei stato disconnesso correttamente!",
objectannotation:"Annotazione oggetto:",
objectannotationt:"fare clic per selezionare diverse annotazioni",
by:"di",
location:"Posizione",
details:"Dettagli",
tags:"tag",
forthisobject:"per questo oggetto",
object:"oggetto",
previousm:"Sezione precedente",
nextm:"Sezione successiva",
or:"o",
moto:"Condividere il patrimonio scientifico per sbloccare il valore creativo per il futuro.",
pleaselogin:"Per procedere, effettua il login",
enteremail:"Inserisci l'email",
enterpassword:"Inserire la password",
login:"Accesso",
forgotpassword:"Ha dimenticato la password?",
cancel:"Annulla",
newuser:"Nuovo utente?",
loginnote1:"Per aggiungere oggetti, annotazioni e porre e rispondere a domande che devi effettuare il login.",
loginnote2:"Per salvare le modifiche devi prima confermare la tua identità e poi premere 'Salva'.",
add:"Inserisci",
remove:"rimuovere",
finally:"Finalmente",
annotation:"segmento della storia",
savestory:"salva la storia",
level1:"scuola elementare",
level2:"Scuola superiore",
level3:"università (laurea)",
level4:"Dottorato di ricerca / ricerca",
addmarker:"Aggiungi marcatore",
addarrow:"aggiungi freccia",
textual:"testuale",
audio:"Audio",
addexp:"Inserisci",
explanation:"descrizione per questa annotazione",
marker:"marcatore",
arrow:"freccia",
at:"a",
angle:"angolo",
arintro:"Inserisci il marcatore <a href=\"/print_marker.pdf\"><img src = \"\\ar_marker_small.png\" align = \"middle\" si></a> nella vista della telecamera. <br/> Per navigare nella storia, fai clic sulle frecce sinistra e destra.",
noexistingaudio:"Nessuna descrizione audio esistente.",
newupload:"Nuovo caricamento",
newrecording:"Nuova registrazione",
recordsound:"Inizia a registrare",
stopbutton:"Ferma la registrazione",
storytitle:"Titolo della storia",
storydesc:"Breve riassunto di questa storia dell'oggetto ...",
adddesc:"Aggiungi descrizione per questa annotazione ...",
arrowadjust:"Regola la posizione e l'orientamento della freccia, quindi",
markeradjust:"Regola la posizione del marker e quindi",
savemarker:"salva marcatore",
savearrow:"salva freccia",
audiodesc:"Descrizione audio:",
clicktochangelan:"Fai clic per cambiare lingua",
getarmarkers:"ottenere marcatori di realtà aumentata",
contributeh2:"Contribuisci all'apparato ... ci vuole una pausa caffè!",
contributeh3_1:"Come funziona?",
contributeh3_2:"Pronto? Comincia qui...",
contributeli1:"<b> Tu </b> carichi ~ 30 foto dell'apparato sperimentale che stai documentando. Prova a scattare fotografie in modo tale che ogni punto sull'oggetto sia visto su 3-6 fotografie da diverse angolazioni. Più foto è meglio di meno foto!",
contributeli2:"<b> Costruiamo un modello 3D dalle tue foto </b>, utilizzando il software di fotogrammetria, e lo mettiamo online su ResearchX3D",
contributeli3:"<b> Tutti </b> possono esplorare, annotare, porre domande e condividere modelli 3D ricostruiti una volta online. Come proprietario riceverai il primo invito ad aggiungere annotazioni e storie, che verranno evidenziate come annotazioni originali.",
contributep1:"Questo è tutto, il patrimonio di ricerca è disponibile in tutto il mondo, per altri studenti, educatori e ricercatori.",
contributep2:"Al momento accettiamo contributi solo dagli utenti con e-mail accademiche. Nel caso in cui non si disponga di un'e-mail accademica ma si desidera contribuire, si prega di <input type=\"button\" onclick=\"openBoard('aboutProject');\" value=\"contattaci\" />.",
contributestart:"Avvia caricamento foto oggetto",
newuserh3:"Nuova registrazione utente",
newuseri1:"Nome",
newuseri1l:" Il tuo nome e cognome appariranno accanto agli oggetti che carichi / annoti.",
newuseri2:"Cognome",
newuseri3:"Istituzione e paese",
newuseri3l:" La tua affiliazione e il tuo Paese di residenza.",
newuseri4:"e-mail",
newuseri4l:" Nota: sono accettate solo e-mail accademiche. Riceverai un link di conferma.",
newuseri5:"Inserire la password",
newuseri5l:" Minimo 8 caratteri.",
newuseri6:"ripeti la password",
newuseri6l:" Solo per controllare non ci sono errori di battitura.",
newusersubmit:"Registra un nuovo utente",
uploadedobjects:"Oggetti caricati esistenti:",
nameobject:"Dai un nome al tuo nuovo oggetto",
enterobjectname:"inserisci il nome del nuovo oggetto",
and:"e",
cratephotospace:"creare spazio per le fotografie",
photolisting:"Elenco delle fotografie di",
nophotolist:"Non hai ancora caricato foto per nessun oggetto. Carica le fotografie degli oggetti di seguito.",
uploadnewphotos:"Carica nuovi file",
startupload:"Inizia il caricamento",
metadataobject:"Metadati su oggetto fotografato",
objtitle:"Titolo dell'oggetto",
objtitlel:"Titolo dell'oggetto",
objdetails:"Dettagli dell'oggetto",
objdetailsl:"breve descrizione dell'oggetto",
objlocation:"Posizione originale e attuale dell'oggetto",
objyear:"Anno in cui è stato realizzato l'oggetto (stima)",
objtags:"Tag oggetto",
objsubmit:"Invia foto per la ricostruzione di oggetti 3D",
newobjectspaceerror:"Si è verificato un errore durante la creazione dello spazio oggetti:",
newobjectspacesuccess:"Spazio creato con successo per le fotografie di un nuovo oggetto.",
objsubmerr1:"ERRORE: è necessario aggiungere alcuni <b> tag oggetto </b> prima dell'invio!",
objsubmerr2:"ERRORE: il nome dell'oggetto deve contenere almeno 3 caratteri",
objsubmerr3:"ERRORE: inserire almeno 10 caratteri per la descrizione dell'oggetto.",
objsubmerr4:"ERRORE: inserire la posizione dell'oggetto (storico, presente o dell'azienda da cui è disponibile).",
objsubmerr5:"ERRORE: inserire l'anno di creazione dell'oggetto (stimato).",
delete:"Elimina",
question:"Domanda",
answers:"risposte",
addeditanswer:"Aggiungi o modifica la tua risposta",
clickdownvotel:"fai clic per votare una domanda o una risposta",
clickupvotel:"fai clic per votare domanda o risposta",
yourquestion:"La tua domanda:",
questiondesc:"Aggiungi annotazione sull'oggetto e descrivi i dettagli testuali della domanda.",
submitquestion:"Invia domanda",
tooltipmainm:"Fai clic per aprire il menu principale",
meniobject:"Oggetto",
questiontitle:"Titolo della domanda",
aboutfunding:"finanziamento",
about15:"Progetto sostenuto dalla Scienza e società di La Diagonale Paris-Saclay.",
size:"taglia",
color:"colore",
red:"rosso",
green:"verde",
blue:"blu",
orange:"arancia",
magenta:"magenta",
selectlicense:"Seleziona la licenza per i file caricati (il modello ricostruito verrà rilasciato con la stessa licenza)",
read:"leggere",
licensetext:"licenza",
translated:"tradotto",
transsee:"vedi traduzione in",
transsource:"Testo originale",
transseesource:"vedi originale in",
transimprove:"migliorare la traduzione",
"fr":"francese",
"en":"inglese",
"es":"spagnolo",
"pt":"portoghese",
"de":"Tedesco",
"zh":"Cinese",
"ru":"russo",
"ar":"Arabo",
"sv":"svedese",
"nl":"olandese",
"it":"italiano",
"ja":"giapponese",
"sr":"serbo",
"cs":"ceco",
"da":"danese",
"sw":"swahili",
"hi":"hindi",
"tr":"Turco",
"vi":"vietnamita",
"th":"tailandese",
"ko":"coreano",
"fa":"Farsi",
"id":"indonesiano",
"cy":"gallese",
"el":"greco",
"ro":"rumeno",
"hu":"ungherese",
"pl":"polacco",
transimprovetitle:"Migliora la traduzione",
transnote:"La traduzione è uno sforzo congiunto di traduzione automatica e feedback con contributi umani. Grazie per aver dedicato del tempo per contribuire.",
transorigin:"Originale in",
transsuggest:"Traduzione in",
transsubmit:"Invia la traduzione",
press:"Toccare",
forillustration:"per l'illustrazione",
storylang:"Scritto in lingua:",
footer0:"Informazioni su ResearchX3D",
footer1:"Cerca oggetti, storie e domande",
footer2:"Chiedi domanda sull'oggetto",
footer3:"Realtà aumentata",
footer4:"Invia oggetto",
footer5:"Invia storia",
footer_title1:"LINK VELOCI",
footer_title2:"LINK SOCIALI",
navigation:"Navigazione",
rotation:"ruotare",
move:"spostare o",
zoom:"ingrandire l'oggetto",
clickForStory:"Clicca qui per vedere la storia dell'oggetto.",
latexAdd:"o aggiungi al documento LaTeX",
latexPDF:"scarica l'immagine PDF qui",
latexCode:"e aggiungi il codice qui sotto.",
latexCaption1:"Scansiona il codice QR o inserisci",
latexCaption2:"per aprire l'oggetto.",
contributeHeader:"DIVENTA UN CONTRIBUTORE",
contribute1:"Guarda un breve video sulla motivazione alla base di ResearchX3D ...",
contribute2:"... o guarda solo un'introduzione di 4 minuti a ResearchX3D.",
contribute3:"ResearchX3D crea modelli 3D dalle tue fotografie ...",
contribute4:"... ma puoi anche caricare oggetti 3D già creati, ad esempio da un software CAD.",
contribute5:"Ogni oggetto ha tante storie da raccontare. Creando diversi tipi di storie puoi:",
contribute6:"Spiegare una funzione e un design; o",
contribute7:"Verifica la conoscenza con un quiz; o",
contribute8:"Condividete abilità e procedure.",
contribute9:"Ecco come l'editor di ResearchX3D ti aiuta a creare una storia.",
clickvideo:"Clicca qui per vedere il video.",
clickexample:"Clicca qui per vedere un esempio",
openstory:"Apri questa storia",
allsbj:"tutte le aree tematiche",
showall:"mostra tutt",
graphic:"grafico",
figclick:"Trova storie e annotazioni su questo oggetto",
openar:"aperto in Realtà Aumentata",
meniagora:"Discussioni della comunità - Agora",
r3dsummary:"<b> Cos'è ResearchX3D? </b> Una piattaforma comunitaria aperta per condividere il patrimonio scientifico e sbloccare valore creativo per il futuro.",
agoraad:"<b> Suggerisci e discuti </b> idee sul progetto ResearchX3D e ottieni aiuto sul nostro Agora <img class = 'link' src = '/link.png'> per le discussioni della comunità."
};
