const lang_hu = {
close:"Bezárás",
loadingmodel:"3D modelljének betöltése",
menistartpage:"Honlap",
menifind:"Keressen tárgyakat, történeteket és kérdéseket",
meniadd:"Történet hozzáadása vagy szerkesztése",
meniask:"Tegyen fel egy tárgyat",
meniupload:"Töltsön fel fotókat a 3D modellhez",
menishare:"Objektum vagy történet megosztása",
meniar:"Kibővített valóság...",
meniaron:"Kapcsolja be az AR módot",
menimarker:"AR markerek nyomtatása",
menisupport:"Kapcsolat és támogatás",
meniabout:"A ResearchX3D-ről",
menilogin:"Belépés",
menilogout:"Kijelentkezés",
headfind:"Keresés",
headfindt:"Kísérleti készülék keresése",
headcontribute:"Hozzájárul",
headcontributet:"Segítsen nekünk a tárgygyűjtemény bővítésében!",
headaron:"AR BE",
headaront:"Kattintson a kiterjesztett valóság bekapcsolásához",
headaroff:"AR OFF",
headarofft:"Kattintson az AR kikapcsolásához",
meni0_0:"DIÁKOKNAK",
meni0_1:"Megtalálja. A történeti kísérletektől kezdve a finombeállító csavarokig.",
meni0_2:"Merítsen ihletet. Bővítse saját kreatív terét a különböző tervezési lehetőségek átgondolásával.",
meni1_0:"OKTATÓK számára",
meni1_1:"Használat. Mutasson előadásokban, és ossza meg előadásjegyzetekben.",
meni1_2:"Teremt. Jegyezze fel az objektumokat saját leírása alapján, és ossza meg velük kapcsolatos történetét.",
meni2_0:"KUTATÓK számára",
meni2_1:"Hozzájárul. Egy kávészünetre van szükség ahhoz, hogy az egész világgal megossza azt a készüléket, amely mellett mindennap elhalad.",
meni2_2:"Fedezd fel. Kövesse nyomon a tervezési ötletek fejlődését.",
aboutheader:"A ResearchX3D.com webhelyről",
aboutteam:"Lépjen kapcsolatba a & projekt csapattal",
about0:"Osszuk meg tudományos örökségünket, hogy felszabadítsuk a jövő kreatív lehetőségeit! A kísérleti készülék a tudományos kutatás kulcseleme. A történelmi kísérletek és a modern tervek egyaránt értékes örökséget jelentenek. Miután ezeket a tárgyakat megosztották, hasznos forrásokká válnak, serkentik az emberek kreativitását szerte a világon. Most pedig lehetőség van kísérleti készülékek megosztására egy kávészünet alatt!",
about1:"Mit csinál a ResearchX3D.com?",
about2:"A felhasználók által a laboratóriumaikból, az egyetemi folyosókról és az irodai polcokról származó tudományos berendezésekről készített fényképek alapján ...",
about3:"... <b> 3D modelleket készítünk </b>, amelyeket bárki felfedezhet a webböngészőben.",
about4:"A ResearchX3D.com lehetővé teszi, hogy fokozzuk tudományos örökségünk hatását és felhalmozzuk az ismereteket a készülékeken:",
about5:"Az objektumok <b> 3D címkézése </b> jelölőkkel és nyilakkal a 3D térben egyszerűen elvégezhető online szerkesztőnk segítségével. A kommentárokat <b> szöveges, grafikus és / vagy hangleírásokkal </b> kísérhetik;",
about6:"A címkék csoportjai történeteket készítenek az objektumokról. A felhasználók <b> tudásszintjük alapján találhatnak történeteket </b>. A teljes felhasználói spektrum lefedésre kerül: az általános iskolai és középiskolai oktatástól kezdve az egyetemi szintű részletes leírásokon át a PhD / kutatási szintű készüléktervezéssel kapcsolatos fejlett megbeszélésekig. A ResearchX3D és a kiválasztott történetek <b> 25 nyelven érhetők el </b>.",
about7:"Mindenki feltehet egy kérdést. A <b> kérdések és válaszok </b> egyaránt 3D címkéket használnak a <b> \"point-and-tell\" leírásokhoz </b>. A legjobb válaszokat a felhasználók felértékelik;",
about8:"A tárgyak a <b> kibővített valóságban </b> láthatók, lehetővé téve mindenki számára, hogy kísérleti apparátust lásson az asztalán;",
about9:"Minden funkció a webes felületen keresztül működik (nincs telepítés, platformfüggetlen), lehetővé téve az objektumok és történetek <b> egyszerű megosztását </b> azáltal, hogy linkeket küld kollégáknak és barátoknak.",
about10:"A ResearchX3D.com platform célja",
about12:"Fizikusok, jelenleg Marie Curie posztdoktori ösztöndíjasok a <a href=\"https://www.institutoptique.fr/\"> Institute d'Optique-ban, Palaiseau, Franciaország </a>.",
about13:"Keressen minket a <a href='mailto:contact@researchx3d.com?subject=Feedback'> contact@researchx3d.com </a> címen.",
aboutli0:"A tudományos és műszaki örökség objektummodelljeinek megőrzése;",
aboutli1:"Jegyezze fel a kutatók által készített tervleírásokat a jövőbeli tervezési ötletek és trükkök megőrzése érdekében;",
aboutli2:"Olyan módon mutassa be a tudományos örökséget, amely inspirálja és kiterjeszti a kreatív gondolkodást a hallgatóság körében az egész spektrumban, az oktatástól a kutatási szintig; és",
aboutli3:"Demokratizálja a kísérleti készüléktervhez való hozzáférést úgy, hogy olyat vesz el, amely korábban csak néhány szerencsés számára volt hozzáférhető, és megosztotta azt az egész világgal.",
findobject:"Objektum keresése ...",
findstory:"... majd válassza a sztorit / annotációt",
findquestion:"... vagy nézze meg a kérdéseket és válaszokat",
filtersubject:"Szűrés tárgyterület szerint:",
filterknowledgelevel:"Szűrés tudásszint szerint:",
shareqr:"Ossza meg a kísérleti készülékeket és történeteket közvetlen linkkel vagy QR-kóddal",
click2copy:"kattintson a link másolásához",
saveqr:"QR-kódkép mentése",
askquestion:"Kérdezz",
share:"részvény",
addmodifystory:"Adja hozzá / módosítsa a történetét",
depositedby:"Letétbe helyezte",
logoutsuccess:"Sikeresen kijelentkezett!",
objectannotation:"Tárgyjegyzet",
objectannotationt:"Kattintson a különféle jelölések kiválasztásához",
by:"által",
location:"Elhelyezkedés",
details:"Részletek",
tags:"Címkék",
forthisobject:"ehhez a tárgyhoz",
object:"tárgy",
previousm:"Előző szakasz",
nextm:"Következő szakasz",
or:"vagy",
moto:"A tudományos örökség megosztása a jövő kreatív értékének kiaknázása érdekében.",
pleaselogin:"A folytatáshoz kérjük, jelentkezzen be",
enteremail:"Írja be az e-mail címet",
enterpassword:"Írd be a jelszót",
login:"Belépés",
forgotpassword:"Elfelejtette a jelszavát?",
cancel:"Megszünteti",
newuser:"Új felhasználó?",
loginnote1:"Objektumok, kommentárok hozzáadásához és a kérdésekre való válaszadáshoz / bejelentkezéshez be kell jelentkeznie.",
loginnote2:"A változtatások mentéséhez először meg kell erősítenie személyazonosságát, majd nyomja meg a „Mentés” gombot.",
add:"Hozzáadás",
remove:"eltávolítani",
finally:"Végül",
annotation:"sztori szegmens",
savestory:"menteni a történetet",
level1:"Általános Iskola",
level2:"Gimnázium",
level3:"egyetem (egyetemista)",
level4:"PhD / kutatás",
addmarker:"Adjon hozzá jelölőt",
addarrow:"nyíl hozzáadása",
textual:"szöveges",
audio:"hang-",
addexp:"Hozzáadás",
explanation:"ennek a kommentárnak a leírása",
marker:"jelző",
arrow:"nyíl",
at:"nál nél",
angle:"szög",
arintro:"Helyezze az <a href=\"/print_marker.pdf\"><img alt = \"R3D\" src = \"\\ar_marker_small.png\" align = \"middle\" si></a> jelölőt a kamera nézetébe. <br/> A történetben való navigáláshoz kattintson a balra és jobbra mutató nyilakra.",
noexistingaudio:"Nincs meglévő hangleírás.",
newupload:"Új feltöltés",
newrecording:"Új felvétel",
recordsound:"Felvétel megkezdése",
stopbutton:"Állítsa le a felvételt",
storytitle:"Történet címe",
storydesc:"A tárgy történetének rövid összefoglalása ...",
adddesc:"Adjon hozzá leírást ehhez a kommentárhoz ...",
arrowadjust:"Állítsa be a nyíl helyzetét és tájolását, majd",
markeradjust:"Állítsa be a jelölő helyzetét, majd",
savemarker:"mentse a jelölőt",
savearrow:"nyíl mentése",
audiodesc:"Hangleírás:",
clicktochangelan:"Kattintson a nyelv megváltoztatásához",
getarmarkers:"szerezzen kibővített valóságjelzőket",
contributeh2:"Hozzájárulás egy készülékhez ... egy kávészünetre van szükség!",
contributeh3_1:"Hogyan működik?",
contributeh3_2:"Kész? Kezdd itt...",
contributeli1:"<b> ~ 30 fotót tölt fel az Ön által dokumentált kísérleti készülékről. Próbáljon olyan fényképeket készíteni, hogy a tárgy minden pontja 3-6 fényképen különböző szögekből látható legyen. Több fotó jobb, mint kevesebb fotó!",
contributeli2:"<b> 3D-s modellt készítünk a fotóiból </b>, fotogrammetriai szoftverek segítségével, és online a ResearchX3D-n",
contributeli3:"<b> Mindenki </b> felfedezheti, megjegyzéseket fűzhet, kérdéseket tehet fel és megoszthatja a rekonstruált 3D-s modelleket, miután online vannak. Ön, mint tulajdonos, első meghívót kap, hogy hozzárendelje a kommentárokat és a történeteket, amelyeket eredeti kommentárként emelnek ki.",
contributep1:"Ennyi, a kutatási örökség világszerte elérhető más hallgatók, oktatók és kutatók számára.",
contributep2:"Jelenleg csak tudományos e-mailekkel rendelkező felhasználókat fogadunk el. Ha nincs tudományos e-mail címe, de szeretne közreműködni, kérjük, írja be a következőt: <input type = \"button\" onclick = \"openBoard ('aboutProject');\" value = \"vegye fel velünk a kapcsolatot\" />.",
contributestart:"Indítsa el az objektum fotó feltöltését",
newuserh3:"Új felhasználó regisztrációja",
newuseri1:"Név",
newuseri1l:" Az Ön neve és vezetékneve megjelenik a feltöltött / annotált objektumok mellett.",
newuseri2:"Vezetéknév",
newuseri3:"Intézmény és ország",
newuseri3l:" Hovatartozása és országa.",
newuseri4:"email",
newuseri4l:" Megjegyzés: csak tudományos e-maileket fogadunk el. Megerősítő linket kap.",
newuseri5:"Írd be a jelszót",
newuseri5l:" Legalább 8 karakter.",
newuseri6:"Jelszó újra",
newuseri6l:" Csak ellenőrizni, hogy nincs-e elírás.",
newusersubmit:"Új felhasználó regisztrálása",
uploadedobjects:"Meglévő feltöltött objektumok:",
nameobject:"Nevezze el az új objektumot",
enterobjectname:"írja be az új objektum nevét",
and:"és",
cratephotospace:"teret teremtsen a fényképek számára",
photolisting:"Fényképeinek felsorolása",
nophotolist:"Még nem töltött fel fotókat egyetlen objektumról sem. Kérjük, töltse fel az alábbi fényképeket.",
uploadnewphotos:"Töltsön fel új fájlokat",
startupload:"Indítsa el a feltöltést",
metadataobject:"Metaadatok fényképezett tárgyon",
objtitle:"Objektum címe",
objtitlel:"Objektum címe",
objdetails:"Az objektum részletei",
objdetailsl:"rövid tárgyleírás",
objlocation:"Az objektum eredeti és jelenlegi helye",
objlocationl:"például. CERN (jelenleg a ... egyetemen)",
objyear:"Az objektum elkészítésének éve (becslés)",
objtags:"Objektumcímkék",
objsubmit:"Fotó benyújtása 3D objektum rekonstrukcióhoz",
newobjectspaceerror:"Hiba történt az objektumterület létrehozása során:",
newobjectspacesuccess:"Sikeresen létrehozott helyet egy új tárgy fényképeinek elkészítéséhez.",
objsubmerr1:"HIBA: A beküldés előtt hozzá kell adnia néhány <b> Objektumcímkét </b>!",
objsubmerr2:"HIBA: Az objektum nevének legalább 3 karakter hosszúnak kell lennie",
objsubmerr3:"HIBA: Írjon be legalább 10 karaktert az objektumleíráshoz.",
objsubmerr4:"HIBA: Kérjük, adja meg az objektum helyét (történelmi, jelen vagy cég, amelytől elérhető).",
objsubmerr5:"HIBA: Adja meg az objektum létrehozásának évét (becsült érték).",
delete:"töröl",
question:"Kérdés",
answers:"Válaszok",
addeditanswer:"Adja hozzá vagy szerkessze a választ",
clickdownvotel:"Kattintson a kérdés vagy válasz visszavonásához",
clickupvotel:"kattintson a kérdés vagy a válasz pozitív szavazatához",
yourquestion:"A kérdésed:",
questiondesc:"Adjon megjegyzést az objektumhoz, és válaszoljon szövegesen egy kérdésre.",
submitquestion:"Küldjön kérdést",
tooltipmainm:"Kattintson a főmenü megnyitásához",
meniobject:"Tárgy",
questiontitle:"Kérdés címe",
aboutfunding:"Finanszírozás",
about15:"Ezt a projektet a La Diagonale Paris-Saclay Tudomány és Társaság támogatja.",
size:"méret",
color:"szín",
red:"piros",
green:"zöld",
blue:"kék",
orange:"narancs",
magenta:"bíborvörös",
selectlicense:"Válasszon licencet a feltöltött fájlokhoz (a rekonstruált modell ugyanazon licenc alatt jelenik meg)",
read:"olvas",
licensetext:"engedély",
translated:"Lefordított",
transsee:"lásd a fordítást",
transsource:"Eredeti szöveg",
transseesource:"lásd eredeti",
transimprove:"javítsa a fordítást",
"fr":"Francia",
"en":"angol",
"es":"spanyol",
"pt":"Portugál",
"de":"német",
"zh":"kínai",
"ru":"orosz",
"ar":"arab",
"sv":"svéd",
"nl":"holland",
"it":"olasz",
"ja":"japán",
"sr":"szerb",
"cs":"cseh",
"da":"dán",
"sw":"Szuahéli",
"hi":"hindi",
"tr":"török",
"vi":"vietnami",
"th":"Thai",
"ko":"koreai",
"fa":"Fárszi",
"id":"indonéz",
"cy":"walesi",
"el":"görög",
"ro":"román",
"hu":"Magyar",
"pl":"fényesít",
transimprovetitle:"Javítsa a fordítást",
transnote:"A fordítás a gépi fordítás és az emberi hozzájárulás együttes erőfeszítése. Köszönjük, hogy időt szánt a közreműködésre.",
transorigin:"Eredeti",
transsuggest:"Fordítás",
transsubmit:"Fordítás beküldése",
press:"nyomja meg",
forillustration:"illusztrációként",
storylang:"Nyelvben írva:",
footer0:"A ResearchX3D-ről",
footer1:"Tárgyak, történetek és kérdések keresése",
footer2:"Tegyen fel egy kérdést a tárgyról",
footer3:"Kibővített valóság",
footer4:"Objektum beküldése",
footer5:"Küldje el a történetet",
footer_title1:"GYORS LINKEK",
footer_title2:"TÁRSADALMI LINKEK",
navigation:"Navigáció",
rotation:"forgatni",
move:"mozogni, vagy",
zoom:"nagyítsa az objektumot",
clickForStory:"Kattintson ide az objektum történetének megtekintéséhez.",
latexAdd:"vagy hozzáadhatja a LaTeX dokumentumhoz",
latexPDF:"töltse le a PDF képet itt",
latexCode:"és adja hozzá az alábbi kódot.",
latexCaption1:"Olvassa be a QR-kódot, vagy írja be",
latexCaption2:"objektum megnyitása érdekében.",
contributeHeader:"LENNI TÁMOGATÓ",
contribute1:"Nézzen meg egy rövid videót a ResearchX3D mögött meghúzódó motivációról ...",
contribute2:"... vagy csak egy 4 perces ResearchX3D bevezetést tekinthet meg.",
contribute3:"A ResearchX3D 3D modelleket készít a fényképeiből ...",
contribute4:"... de már létrehozott 3D objektumokat is feltölthet, például egy CAD szoftverből.",
contribute5:"Minden tárgynak sok története van. Különböző típusú történetek létrehozásával:",
contribute6:"Magyarázzon el egy funkciót és egy tervet; vagy",
contribute7:"Tesztelje tudását kvízzel; vagy",
contribute8:"Ossza meg készségeit és eljárásait.",
contribute9:"Így segít a ResearchX3D szerkesztő létrehozni egy történetet.",
clickvideo:"Kattintson a videó megtekintéséhez.",
clickexample:"Kattintson egy példa megtekintéséhez.",
openstory:"Nyisd meg ezt a történetet",
allsbj:"minden tantárgy",
showall:"Mutasd az összeset",
graphic:"grafikus",
figclick:"Keressen történeteket és kommentárokat erről az objektumról",
openar:"nyitva a kiterjesztett valóságban",
meniagora:"Közösségi beszélgetések - Agora",
r3dsummary:"<b> Mi az a ResearchX3D? </b> Nyílt közösségi platform a tudományos örökség megosztására a jövő kreatív értékének kiaknázása érdekében.",
agoraad:"<b> Javasoljon és vitasson meg </b> ötleteket a ResearchX3D projektről, és kérjen segítséget az Agora <img class = 'link' src = '/link.png'> közösségi beszélgetésekhez."
};
