const lang_sw ={close:"Karibu",
loadingmodel:"Inapakia mfano",
menistartpage:"Ukurasa wa nyumbani",
menifind:"Pata vitu, hadithi na maswali",
meniadd:"Ongeza au hariri hadithi ya kitu",
meniask:"Uliza swali juu ya kitu",
meniupload:"Sasisha picha za kitu kwa mfano wa 3D",
menishare:"Shiriki kitu au hadithi",
meniar:"Ukweli uliodhabitiwa ...",
meniaron:"Washa hali ya AR",
menimarker:"Chapisha alama za AR",
menisupport:"Wasiliana na msaada",
meniabout:"Kuhusu ResearchX3D",
menilogin:"Ingia",
menilogout:"Logout",
headfind:"Pata",
headfindt:"Tafuta vifaa vya majaribio",
headcontribute:"Kuchangia",
headcontributet:"Tusaidie kukuza mkusanyiko wa vitu!",
headaron:"PEKEE",
headaront:"Bonyeza ili kuwasha Ukweli wa Augmented",
headaroff:"ACHA",
headarofft:"Bonyeza kuzima AR",
meni0_0:"KWA WANAFUNZI",
meni0_1:"Pata. Kila kitu kutoka kwa majaribio ya kihistoria, kwa screws nzuri za marekebisho.",
meni0_2:"Pata msukumo. Panua nafasi yako mwenyewe ya ubunifu kwa kufikiria juu ya uwezekano tofauti wa muundo.",
meni1_0:"KWA WAALIMU",
meni1_1:"Tumia. Onyesha katika maonyesho na kozi.",
meni1_2:"Unda. Tambua vitu kwa maelezo yako mwenyewe, na ushiriki hadithi yako juu yao.",
meni2_0:"KWA WATAFITI",
meni2_1:"Kuchangia. Inachukua mapumziko ya kahawa moja kushiriki vifaa ambavyo unapita kila siku na ulimwengu wote.",
meni2_2:"Gundua. Fuatilia maendeleo ya maoni ya muundo.",
aboutheader:"Kuhusu ResearchX3D.com",
aboutteam:"Timu",
aboutcontact:"Yaliyomo",
about0:"Wacha tushiriki urithi wa kisayansi kufungua thamani ya ubunifu kwa siku zijazo! Vifaa vya majaribio ni jambo muhimu katika utafiti wa kisayansi. Majaribio ya kihistoria na miundo ya kisasa ni urithi muhimu. Mara vitu hivi vinaposhirikiwa, huwa rasilimali nzuri, inachochea ubunifu wa watu ulimwenguni kote. Na sasa inawezekana kushiriki vifaa vya majaribio wakati wa mapumziko ya kahawa!",
about1:"Je! ResearchX3D.com inafanya nini?",
about2:"Kulingana na <b> picha zilizopakiwa na watumiaji </b> za vifaa vya kisayansi kutoka maabara zao, korido za chuo kikuu, na rafu za ofisi ...",
about3:"... tuna .... <huunda mifano ya 3D </b> inayoweza kufahamika na mtu yeyote kwenye kivinjari cha wavuti.",
about4:"ResearchX3D.com basi inaruhusu moja kuongeza athari za urithi na kukusanya ujuzi juu ya vifaa:",
about5:"<b> 3D ya kuweka lebo </b> ya vitu vyenye alama na mishale kwenye nafasi ya 3D hufanywa kwa urahisi kupitia hariri ya mkondoni. Ujumbe unaweza kuambatana na maelezo ya <b> maandishi na sauti </b>;",
about6:"Vikundi vya maabara hufanya hadithi juu ya vitu. Watumiaji wanaweza <b> kupata hadithi kulingana na kiwango chao cha ufahamu </b>. Watumiaji waligundua wigo umefunikwa: kutoka shule ya msingi na mafundisho ya shule ya upili, kupitia maelezo ya kina ya kiwango cha chuo kikuu, hadi majadiliano ya hali ya juu juu ya muundo wa appartus kwa kiwango cha PhD / utafiti;",
about7:"Kila mtu anaweza kuuliza swali. Wote <b> maswali na majibu </b> tumia lebo za 3D kwa <b> \"kuelekeza-na-kuwaambia\" maelezo </b>. Majibu mazuri ni juu ya watumiaji.",
about8:"Vitu vinaweza kuonekana katika <b> ukweli uliodhibitishwa </b>, kuruhusu kila mtu kuona vifaa vya majaribio kwenye dawati lao;",
about9:"Utendaji wote huletwa kupitia interface ya wavuti (hakuna usakinishaji, jukwaa huru), inaruhusu <b> kugawana rahisi </b> ya vitu na hadithi kwa kutuma viungo kwa wenzako na marafiki.",
about10:"Utafiti wa jukwaa la XXDD linalenga",
about12:"Wanafizikia, kwa sasa Marie Curie wenzake wa posta wa kitendaji huko <a href=\"https://www.institutoptique.fr/\"> Taasisi ya d'Optique, Palaiseau, Ufaransa </a>.",
about13:"Wasiliana nasi kwa <a href='mailto:contact@researchx3d.com?subject=Feedback'> contact@researchx3d.com </a>.",
aboutli0:"Hifadhi mifano ya kitu cha urithi wa kisayansi na kiufundi;",
aboutli1:"Rekodi maelezo ya muundo na watafiti ili kulinda mawazo ya hila na hila za siku zijazo;",
aboutli2:"Urithi wa sasa kwa njia ambayo huchochea na kupanua nafasi ya ubunifu katika watazamaji kupitisha tasnia, kutoka kwa ufundishaji hadi kiwango cha utafiti; na",
aboutli3:"Demokrasia ufikiaji wa muundo wa vifaa vya majaribio, kwa kuchukua kitu ambacho kilipatikana tu kwa wachache wenye bahati na kushiriki ulimwengu wote.",
findobject:"Tafuta kitu ...",
findstory:"... na kisha uchague hadithi / maelezo",
findquestion:"... au angalia maswali na majibu",
filtersubject:"Filter kwa eneo la somo:",
filterknowledgelevel:"Kuchuja kwa kiwango cha maarifa:",
shareqr:"Shiriki vifaa vya majaribio na hadithi na kiungo cha moja kwa moja au msimbo wa QR",
click2copy:"bonyeza ili kunakili kiunga",
saveqr:"Hifadhi picha ya msimbo wa QR",
askquestion:"Uliza Swali",
share:"kushiriki",
addmodifystory:"Ongeza / urekebishe hadithi yako",
depositedby:"Iliyowekwa na",
logoutsuccess:"Umeondolewa kwa mafanikio!",
objectannotation:"Sababu ya kitu:",
objectannotationt:"bonyeza kuchagua maelezo tofauti",
by:"na",
location:"Mahali",
details:"Maelezo",
tags:"Tepe",
forthisobject:"kwa kitu hiki",
object:"kitu",
previousm:"Sehemu iliyotangulia",
nextm:"Sehemu inayofuata",
or:"au",
moto:"Kushiriki urithi wa kisayansi kufungua thamani ya ubunifu kwa siku zijazo.",
pleaselogin:"Kuendelea tafadhali ingia",
enteremail:"Ingiza barua pepe",
enterpassword:"Ingiza Nywila",
login:"Ingia",
forgotpassword:"Umesahau nywila?",
cancel:"Ghairi",
newuser:"Mtumiaji mpya?",
loginnote1:"Kuongeza vitu, maelezo na kuuliza na kujibu maswali unayohitaji kuingia.",
loginnote2:"Ili kuokoa mabadiliko unahitaji kwanza kudhibitisha kitambulisho chako na kisha bonyeza 'Hifadhi'.",
add:"Ongeza",
remove:"ondoa",
finally:"Mwishowe",
annotation:"sehemu ya hadithi",
savestory:"ila hadithi",
level1:"Shule ya msingi",
level2:"sekondari",
level3:"chuo kikuu (shahada ya kwanza)",
level4:"PhD / utafiti",
addmarker:"Ongeza alama",
addarrow:"ongeza mshale",
textual:"maandishi",
audio:"sauti",
addexp:"Ongeza",
explanation:"maelezo ya maelezo haya",
marker:"alama",
arrow:"mshale",
at:"katika",
angle:"pembe",
arintro:"Weka <a href=\"/print_marker.pdf\"><img src = \"\\ar_marker_small.png\" align = \"katikati\" si></a> alama kwenye mtazamo wa kamera. <br/> Ili kuzunguka hadithi, bonyeza kwenye mishale ya kushoto na kulia.",
noexistingaudio:"Hakuna maelezo ya sauti yaliyopo.",
newupload:"Upakiaji mpya",
newrecording:"Kurekodi mpya",
recordsound:"Anza kurekodi",
stopbutton:"Acha kurekodi",
storytitle:"Kichwa cha hadithi",
storydesc:"Muhtasari mfupi wa hadithi hii ya kitu ...",
adddesc:"Ongeza maelezo kwa maelezo haya ...",
arrowadjust:"Kurekebisha msimamo wa mshale na mwelekeo, na kisha",
markeradjust:"Kurekebisha alama ya alama na kisha",
savemarker:"ila alama",
savearrow:"ila mshale",
audiodesc:"Maelezo ya sauti:",
clicktochangelan:"Bonyeza kubadili lugha",
getarmarkers:"pata alama za ukweli uliodhabitiwa",
contributeh2:"Kuchangia vifaa ... inachukua mapumziko ya kahawa moja!",
contributeh3_1:"Inavyofanya kazi?",
contributeh3_2:"Uko tayari? Anza hapa ...",
contributeli1:"<b> Unapakia ~ picha 30 za vifaa vya jaribio unazoandika. Jaribu kuchukua picha ili kila nukta kwenye kitu ionekane kwenye picha 3-6 kutoka pembe tofauti. Picha zaidi ni bora kisha picha kidogo!",
contributeli2:"<b> Tunaunda mfano wa 3D kutoka kwa picha zako </b>, kwa kutumia programu ya kupiga picha, na kuiweka mkondoni kwenye ResearchX3D",
contributeli3:"<b> Kila mtu </b> anaweza kuchunguza, kufuta, kuuliza maswali na kushiriki mfano mpya wa 3D mara tu iko mkondoni. Wewe kama mmiliki utapokea mwaliko wa kwanza wa kuongeza kero na hadithi, ambayo itaangaziwa kama daftari la asili.",
contributep1:"Hiyo ndio yote, urithi wa utafiti unapatikana ulimwenguni kote, kwa wanafunzi wengine, waelimishaji na watafiti.",
contributep2:"Kwa sasa tunakubali michango kutoka kwa watumiaji walio na barua pepe za kitaalam. Ila ikiwa hauna barua pepe ya kielimu lakini ungependa kuchangia tafadhali <input type =\"button\" onclick=\"openBoard('aboutProject');\" value=\"wasiliana nasi\" />.",
contributestart:"Anza kupakia picha ya kitu",
newuserh3:"Usajili mpya wa watumiaji",
newuseri1:"Jina",
newuseri1l:" Jina lako na jina lako litaonekana kando ya vitu unavyopakia / kumaliza.",
newuseri2:"Surname",
newuseri3:"Taasisi na nchi",
newuseri3l:" Ushirikiano wako na nchi ya eneo.",
newuseri4:"barua pepe",
newuseri4l:" Kumbuka: barua pepe za kitambulisho tu zinakubaliwa. Utapokea kiunga cha uthibitisho.",
newuseri5:"Ingiza nywila",
newuseri5l:" Kiwango cha chini cha herufi 8.",
newuseri6:"Rudia neno siri",
newuseri6l:" Ili kuangalia tu hakuna aina.",
newusersubmit:"Sajili mtumiaji mpya",
uploadedobjects:"Vitu vilivyopakiwa vilivyopakiwa:",
nameobject:"Sema kitu chako kipya",
enterobjectname:"ingiza jina mpya la kitu",
and:"na",
cratephotospace:"tengeneza nafasi kwa picha",
photolisting:"Orodha ya picha za",
nophotolist:"Bado haujapakia picha za kitu chochote. Tafadhali pakia picha za kitu hapa chini.",
uploadnewphotos:"Sasisha faili mpya",
startupload:"Anza kupakia",
metadataobject:"Metadata kwenye kitu kilichopigwa picha",
objtitle:"Kichwa cha kitu",
objtitlel:"Kichwa cha kitu",
objdetails:"Maelezo ya kitu",
objdetailsl:"maelezo mafupi ya kitu",
objlocation:"Sehemu ya asili na ya sasa ya kitu",
objyear:"Mwaka wakati kitu kilifanywa (makisio)",
objtags:"Vitambulisho vya kitu",
objsubmit:"Peana picha kwa ujenzi wa kitu cha 3D",
newobjectspaceerror:"Kulikuwa na hitilafu wakati wa kuunda nafasi yako ya kitu:",
newobjectspacesuccess:"Imeunda vizuri nafasi ya picha za kitu kipya.",
objsubmerr1:"ERROR: Unahitaji kuongeza vitambulisho vya <b> Kitu </b> kabla ya uwasilishaji!",
objsubmerr2:"ERROR: Jina la kitu lazima liwe na urefu wa herufi tatu",
objsubmerr3:"ERROR: Ingiza angalau herufi 10 kwa maelezo ya kitu.",
objsubmerr4:"ERROR: Tafadhali ingiza eneo la kitu hicho (kihistoria, sasa, au kampuni ambayo inapatikana).",
objsubmerr5:"ERROR: Tafadhali ingiza mwaka wa uundaji wa vitu (inakadiriwa).",
delete:"futa",
question:"Swali",
answers:"Majibu",
addeditanswer:"Ongeza au Hariri jibu lako",
clickdownvotel:"bonyeza ili kupunguza swali au jibu",
clickupvotel:"bonyeza ili kuuliza swali au answe",
yourquestion:"Swali lako:",
questiondesc:"Ongeza kashfa kwenye kitu na ueleze maelezo ya nguo.",
submitquestion:"Tuma swali",
tooltipmainm:"Bonyeza kufungua menyu kuu",
meniobject:"Kitu",
questiontitle:"Kichwa cha swali",
aboutfunding:"Ufadhili",
about15:"Mradi unaoungwa mkono na Sayansi na Jamii ya La Diagonale Paris-Saclay.",
size:"saizi",
color:"rangi",
red:"nyekundu",
green:"kijani",
blue:"bluu",
orange:"machungwa",
magenta:"magenta",
selectlicense:"Chagua leseni ya faili zilizopakiwa (mfano uliyopangwa upya utatolewa chini ya leseni moja)",
read:"soma",
licensetext:"leseni",
translated:"Ilitafsiriwa",
transsee:"angalia tafsiri ndani",
transsource:"Maandishi asilia",
transseesource:"tazama asili ndani",
transimprove:"kuboresha tafsiri",
"fr":"Kifaransa",
"en":"kiingereza",
"es":"Kihispania",
"pt":"portugese",
"de":"jamani",
"zh":"Kichina",
"ru":"Kirusi",
"ar":"arabiki",
"sv":"ulimwengu",
"nl":"Jadi",
"it":"Italia",
"ja":"Kijapani",
"sr":"seria",
"cs":"czech",
"da":"Danish",
"sw":"Kiswahili",
"hi":"Hindi",
"tr":"Kituruki",
"vi":"vietnamese",
"th":"thai",
"ko":"Kikorea",
"fa":"farsi",
"id":"Indema",
"cy":"mr",
"el":"busara",
"ro":"Kiromania",
"hu":"Kihungari",
"pl":"Kipolishi",
transimprovetitle:"Boresha tafsiri",
transnote:"Tafsiri ni juhudi ya kujumuika ya tafsiri ya mashine na maoni yaliyotolewa na binadamu. Asante kwa kuchukua muda wa kuchangia.",
transorigin:"Asili ndani",
transsuggest:"Tafsiri katika",
transsubmit:"Peana tafsiri",
press:"Gusa",
forillustration:"kwa mfano",
storylang:"Imeandikwa kwa lugha:",
footer0:"Kuhusu ResearchX3D",
footer1:"Tafuta vitu, hadithi na maswali",
footer2:"Uliza maswali juu ya kitu",
footer3:"Ukweli uliodhabitiwa",
footer4:"Peana kitu",
footer5:"Peana hadithi",
footer_title1:"MAHUSIANO ZAIDI",
footer_title2:"MAHUSIANO YA JAMII",
navigation:"Urambazaji",
rotation:"kuzunguka",
move:"hoja, au",
zoom:"vuta kitu",
clickForStory:"Bonyeza hapa kuona hadithi ya kitu.",
latexAdd:"au ongeza kwa hati ya LaTeX",
latexPDF:"pakua picha ya PDF hapa",
latexCode:"na ongeza nambari hapa chini.",
latexCaption1:"Skena nambari ya QR au ingiza",
latexCaption2:"ili kufungua kitu.",
contributeHeader:"KUWA MCHANGIAJI",
contribute1:"Tazama video fupi juu ya motisha nyuma ya UtafitiX3D ..",
contribute2:"... au angalia tu utangulizi wa dakika 4 wa UtafitiX3D.",
contribute3:"UtafitiX3D huunda vielelezo vya 3D kutoka picha zako ...",
contribute4:"... lakini unaweza pia kupakia vitu vya 3D vilivyoundwa tayari, kwa mfano kutoka kwa programu ya CAD.",
contribute5:"Kila kitu kina hadithi nyingi za kusimulia. Kwa kuunda hadithi tofauti unaweza:",
contribute6:"Eleza kazi na muundo; au",
contribute7:"Jaribu maarifa na jaribio; au",
contribute8:"Shiriki ujuzi na taratibu.",
contribute9:"Hivi ndivyo mhariri wa ResearchX3D anayekusaidia kuunda hadithi.",
clickvideo:"Bonyeza hapa kuona video.",
clickexample:"Bonyeza hapa kuona mfano",
openstory:"Fungua hadithi hii",
allsbj:"maeneo yote ya somo",
showall:"Onyesha yot",
graphic:"picha",
figclick:"Hitta berättelser och kommentarer om detta objekt",
openar:"wazi katika Ukweli uliodhabitiwa",
meniagora:"Majadiliano ya jamii - Agora",
r3dsummary:"<b> UtafitiX3D ni nini? </b> Jukwaa wazi la jamii la kushiriki urithi wa kisayansi kufungua thamani ya ubunifu kwa siku zijazo.",
agoraad:"<b> Pendekeza na ujadili </b> maoni kuhusu mradi wa ResearchX3D, na upate usaidizi kwenye Agora <img class = 'link' src = '/link.png'> yetu ya Majadiliano ya Jumuiya."
};
