const lang_de ={close:"Schließen",
loadingmodel:"Modell wird geladen",
menistartpage:"Startseite",
menifind:"Finde Objekte, Geschichten und Fragen",
meniadd:"Objektgeschichte hinzufügen oder bearbeiten",
meniask:"Frage zum Objekt stellen",
meniupload:"Laden Sie Objektfotos für das 3D-Modell hoch",
menishare:"Teile ein Objekt oder eine Geschichte",
meniar:"Erweiterte Realität...",
meniaron:"Aktivieren Sie den AR-Modus",
menimarker:"AR-Marker drucken",
menisupport:"Kontaktieren Sie Support",
meniabout:"Über ResearchX3D",
menilogin:"Einloggen",
menilogout:"Ausloggen",
headfind:"Finden",
headfindt:"Suche nach Versuchsapparaturen",
headcontribute:"Einen Beitrag leisten",
headcontributet:"Helfen Sie uns, die Sammlung von Objekten zu vergrößern!",
headaron:"AR ON",
headaront:"Klicken Sie, um Augmented Reality zu aktivieren",
headaroff:"AR AUS",
headarofft:"Klicken Sie, um AR auszuschalten",
meni0_0:"FÜR STUDIERENDE",
meni0_1:"Finden. Alles von historischen Experimenten bis hin zu Feineinstellungsschrauben.",
meni0_2:"Lass dich inspirieren. Erweitern Sie Ihren eigenen kreativen Raum, indem Sie über verschiedene Gestaltungsmöglichkeiten nachdenken.",
meni1_0:"FÜR PÄDAGOGEN",
meni1_1:"Verwenden. In Präsentationen und Kursen zeigen.",
meni1_2:"Erstellen. Beschriften Sie Objekte mit Ihrer eigenen Beschreibung und teilen Sie Ihre Geschichte damit.",
meni2_0:"FÜR FORSCHER",
meni2_1:"Einen Beitrag leisten. Es dauert eine Kaffeepause, um den Apparat, an dem Sie jeden Tag vorbeigehen, mit einer ganzen Welt zu teilen.",
meni2_2:"Erkunden. Verfolgen Sie die Entwicklung von Designideen.",
aboutheader:"Über die ResearchX3D.com",
aboutteam:"Mannschaft",
aboutcontact:"Contant",
about0:"Teilen wir das wissenschaftliche Erbe, um den kreativen Wert für die Zukunft freizuschalten! Der experimentelle Apparat ist ein Schlüsselelement in der wissenschaftlichen Forschung. Sowohl historische Experimente als auch moderne Designs sind ein wertvolles Erbe. Sobald diese Objekte geteilt werden, werden sie zu nützlichen Ressourcen, die die Kreativität von Menschen auf der ganzen Welt anregen. Und jetzt ist es möglich, experimentelle Geräte während der Kaffeepause zu teilen!",
about1:"Was macht ResearchX3D.com?",
about2:"Basierend auf <b> von Nutzern hochgeladenen Fotos </b> von wissenschaftlichen Geräten aus ihren Labors, Universitätskorridoren und Büroregalen ...",
about3:"... wir <b> erstellen 3D-Modelle </b>, die von jedem im Webbrowser erkundet werden können.",
about4:"ResearchX3D.com ermöglicht es dann, die Auswirkung des Erbes zu verbessern und Wissen über Geräte zu sammeln:",
about5:"Die <b> 3D-Beschriftung </b> von Objekten mit Markierungen und Pfeilen im 3D-Raum erfolgt einfach über den Online-Editor. Anmerkungen können mit <b> Text- und Audiobeschreibungen </b> versehen werden.",
about6:"Gruppen von Labels machen Geschichten über die Objekte. Nutzer können <b> Geschichten basierend auf ihrem Wissensstand finden </b>. Benutzer aus dem gesamten Spektrum werden abgedeckt: von Grundschul- und Gymnasialunterricht über detaillierte Beschreibungen auf Hochschulebene bis hin zu fortgeschrittenen Diskussionen über die Gestaltung von Apparaturen für Doktoranden / Forscher;",
about7:"Jeder kann eine Frage stellen. Bei beiden <b> Fragen und Antworten </b> werden 3D-Beschriftungen für <b> Point-and-Tell-Beschreibungen </b> verwendet. Die besten Antworten werden von den Benutzern positiv bewertet.",
about8:"Objekte können in <b> Augmented Reality </b> gesehen werden, sodass jeder experimentelle Geräte auf seinem Schreibtisch sehen kann.",
about9:"Alle Funktionen werden über die Webschnittstelle bereitgestellt (keine Installation, plattformunabhängig), sodass Sie Objekte und Geschichten <b> einfach teilen </b> können, indem Sie Links an Kollegen und Freunde senden.",
about10:"Die Plattform ResearchX3D.com zielt darauf ab",
about12:"Physiker, derzeit Marie-Curie-Stipendiaten am <a href=\"https://www.institutoptique.fr/\"> Institute d'Optique, Palaiseau, Frankreich </a>.",
about13:"Kontaktieren Sie uns unter <a href='mailto:contact@researchx3d.com?subject=Feedback'> contact@researchx3d.com </a>.",
aboutli0:"Objektmodelle des wissenschaftlichen und technischen Erbes erhalten;",
aboutli1:"Zeichnen Sie Konstruktionsbeschreibungen von Forschern auf, um Konstruktionsideen und -tricks für die Zukunft zu sichern.",
aboutli2:"Präsentieren Sie das Erbe auf eine Weise, die den kreativen Raum des Publikums über die Spektren hinweg inspiriert und erweitert, von der Lehre bis zur Forschungsebene. und",
aboutli3:"Demokratisieren Sie den Zugang zum experimentellen Apparatebau, indem Sie etwas, das bisher nur wenigen Glücklichen zugänglich war, der ganzen Welt zugänglich machen.",
findobject:"Objekt suchen ...",
findstory:"... und dann Story / Annotation auswählen",
findquestion:"... oder sehen Sie Fragen und Antworten",
filtersubject:"Filtern nach Themenbereich:",
filterknowledgelevel:"Filtern nach Wissensstand:",
shareqr:"Teilen Sie experimentelle Geräte und Geschichten mit direktem Link oder QR-Code",
click2copy:"Klicken Sie, um den Link zu kopieren",
saveqr:"Speichern Sie das QR-Code-Bild",
askquestion:"Frage stellen",
share:"Teilen",
addmodifystory:"Füge deine Geschichte hinzu / ändere sie",
depositedby:"Hinterlegt von",
logoutsuccess:"Du hast dich erfolgreich abgemeldet!",
objectannotation:"Objektanmerkung:",
objectannotationt:"Klicken Sie, um eine andere Anmerkung auszuwählen",
by:"durch",
location:"Lage",
details:"Einzelheiten",
tags:"Stichworte",
forthisobject:"für dieses Objekt",
object:"Objekt",
previousm:"Vorherige Sektion",
nextm:"Nächster Abschnitt",
or:"oder",
moto:"Teilen des wissenschaftlichen Erbes, um kreativen Wert für die Zukunft freizusetzen.",
pleaselogin:"Bitte melden Sie sich an, um fortzufahren",
enteremail:"Email eingeben",
enterpassword:"Passwort eingeben",
login:"Einloggen",
forgotpassword:"Passwort vergessen?",
cancel:"Stornieren",
newuser:"Neuer Benutzer?",
loginnote1:"Um Objekte und Anmerkungen hinzuzufügen und Fragen zu stellen und zu beantworten, müssen Sie sich anmelden.",
loginnote2:"Um die Änderungen zu speichern, müssen Sie zuerst Ihre Identität bestätigen und dann auf \"Speichern\" klicken.",
add:"Hinzufügen",
remove:"entfernen",
finally:"Endlich",
annotation:"story-segment",
savestory:"Geschichte speichern",
level1:"Grundschule",
level2:"weiterführende Schule",
level3:"Universität (Bachelor)",
level4:"Promotion / Forschung",
addmarker:"Marker hinzufügen",
addarrow:"Pfeil hinzufügen",
textual:"Text",
audio:"Audio-",
addexp:"Hinzufügen",
explanation:"Beschreibung für diese Anmerkung",
marker:"Marker",
arrow:"Pfeil",
at:"beim",
angle:"Winkel",
arintro:"Setzen Sie den Marker <a href=\"/print_marker.pdf\"><img src = \"\\ar_marker_small.png\" align = \"middle\" si></a> in die Kameraansicht. <br/> Um durch die Story zu navigieren, klicken Sie auf die Pfeile nach links und rechts.",
noexistingaudio:"Keine vorhandenen Audiobeschreibungen.",
newupload:"Neuer Upload",
newrecording:"Neue Aufnahme",
recordsound:"Starte die Aufnahme",
stopbutton:"Höre auf, aufzunehmen",
storytitle:"Titel der Geschichte",
storydesc:"Kurze Zusammenfassung dieser Objektgeschichte ...",
adddesc:"Beschreibung für diese Anmerkung hinzufügen ...",
arrowadjust:"Passen Sie die Pfeilposition und -ausrichtung an und dann",
markeradjust:"Passen Sie die Markerposition an und dann",
savemarker:"Markierung speichern",
savearrow:"Pfeil speichern",
audiodesc:"Audiobeschreibung:",
clicktochangelan:"Klicken Sie hier, um die Sprache zu ändern",
getarmarkers:"Holen Sie sich Augmented-Reality-Marker",
contributeh2:"Apparat einbringen ... es dauert eine Kaffeepause!",
contributeh3_1:"Wie es funktioniert?",
contributeh3_2:"Bereit? Fang hier an...",
contributeli1:"<b> Sie </b> laden ~ 30 Fotos des zu dokumentierenden Versuchsgeräts hoch. Versuchen Sie, so zu fotografieren, dass jeder Punkt auf dem Objekt auf 3-6 Fotos aus verschiedenen Winkeln zu sehen ist. Mehr Fotos sind besser als weniger Fotos!",
contributeli2:"<b> Wir erstellen aus Ihren Fotos ein 3D-Modell </b> mit Hilfe der Photogrammetrie-Software und stellen es auf dem ResearchX3D online",
contributeli3:"<b> Jeder </b> kann rekonstruierte 3D-Modelle untersuchen, kommentieren, Fragen stellen und freigeben, sobald sie online sind. Sie als Eigentümer erhalten eine erste Einladung zum Hinzufügen von Anmerkungen und Storys, die als Originalanmerkungen hervorgehoben werden.",
contributep1:"Das ist alles, das Forschungserbe ist für andere Studenten, Pädagogen und Forscher weltweit verfügbar.",
contributep2:"Momentan akzeptieren wir nur Beiträge von Nutzern mit akademischen E-Mails. Falls Sie keine akademische E-Mail-Adresse haben, aber einen Beitrag leisten möchten, <input type=\"button\" onclick=\"openBoard('aboutProject');\" value =\"kontaktiere uns\" />.",
contributestart:"Starten Sie den Upload des Objektfotos",
newuserh3:"Neue Benutzerregistrierung",
newuseri1:"Name",
newuseri1l:" Ihr Vor- und Nachname wird neben den Objekten angezeigt, die Sie hochladen / mit Anmerkungen versehen.",
newuseri2:"Nachname",
newuseri3:"Institution und Land",
newuseri3l:" Ihre Zugehörigkeit und Ihr Land.",
newuseri4:"Email",
newuseri4l:" Hinweis: Es werden nur akademische E-Mails akzeptiert. Sie erhalten einen Bestätigungslink.",
newuseri5:"Passwort eingeben",
newuseri5l:" Mindestens 8 Zeichen.",
newuseri6:"Wiederhole das Passwort",
newuseri6l:" Nur um zu überprüfen, gibt es keine Tippfehler.",
newusersubmit:"Registrieren Sie einen neuen Benutzer",
uploadedobjects:"Vorhandene hochgeladene Objekte:",
nameobject:"Benennen Sie Ihr neues Objekt",
enterobjectname:"Geben Sie einen neuen Objektnamen ein",
and:"und",
cratephotospace:"Platz für Fotos schaffen",
photolisting:"Auflistung von Fotografien von",
nophotolist:"Sie haben noch keine Fotos für ein Objekt hochgeladen. Bitte laden Sie unten Objektfotos hoch.",
uploadnewphotos:"Laden Sie neue Dateien hoch",
startupload:"Upload starten",
metadataobject:"Metadaten zum fotografierten Objekt",
objtitle:"Objekttitel",
objtitlel:"Objekttitel",
objdetails:"Objektdetails",
objdetailsl:"kurze Objektbeschreibung",
objlocation:"Ursprünglicher und gegenwärtiger Standort des Objekts",
objyear:"Jahr, in dem das Objekt hergestellt wurde (Schätzung)",
objtags:"Objekt-Tags",
objsubmit:"Senden Sie ein Foto für die 3D-Objektrekonstruktion",
newobjectspaceerror:"Beim Erstellen Ihres Objektbereichs ist ein Fehler aufgetreten:",
newobjectspacesuccess:"Erfolgreich erstellter Platz für Fotos eines neuen Objekts.",
objsubmerr1:"FEHLER: Sie müssen vor dem Absenden einige <b> Objekt-Tags </b> hinzufügen!",
objsubmerr2:"FEHLER: Der Objektname muss mindestens 3 Zeichen lang sein",
objsubmerr3:"FEHLER: Geben Sie mindestens 10 Zeichen für die Objektbeschreibung ein.",
objsubmerr4:"FEHLER: Bitte geben Sie den Ort des Objekts ein (historisch, gegenwärtig oder Firma, von der es verfügbar ist).",
objsubmerr5:"FEHLER: Bitte geben Sie das Jahr der Objekterstellung ein (geschätzt).",
delete:"löschen",
question:"Frage",
answers:"Antworten",
addeditanswer:"Füge deine Antwort hinzu oder bearbeite sie",
clickdownvotel:"Klicken Sie hier, um die Frage oder Antwort herunter zu stimmen",
clickupvotel:"Klicken Sie hier, um die Frage oder Antwort zu verbessern",
yourquestion:"Ihre Frage:",
questiondesc:"Fügen Sie eine Anmerkung zum Objekt hinzu und beschreiben Sie die Textdetails der Frage.",
submitquestion:"Frage einreichen",
tooltipmainm:"Klicken Sie hier, um das Hauptmenü zu öffnen",
meniobject:"Objekt",
questiontitle:"Fragentitel",
aboutfunding:"Finanzierung",
about15:"Projekt unterstützt von der Wissenschaft und Gesellschaft der Diagonale Paris-Saclay.",
size:"Größe",
color:"Farbe",
red:"rot",
green:"Grün",
blue:"Blau",
orange:"Orange",
magenta:"Magenta",
selectlicense:"Lizenz für hochgeladene Dateien auswählen (das rekonstruierte Modell wird unter derselben Lizenz veröffentlicht)",
read:"lesen",
licensetext:"Lizenz",
translated:"Übersetzt",
transsee:"siehe Übersetzung in",
transsource:"Original Text",
transseesource:"siehe Original in",
transimprove:"übersetzung verbessern",
"fr":"Französisch",
"en":"Englisch",
"es":"Spanisch",
"pt":"Portugiesisch",
"de":"Deutsche",
"zh":"Chinesisch",
"ru":"Russisch",
"ar":"Arabisch",
"sv":"Schwedisch",
"nl":"Niederländisch",
"it":"Italienisch",
"ja":"japanisch",
"sr":"serbisch",
"cs":"Tschechisch",
"da":"dänisch",
"sw":"Suaheli",
"hi":"Hindi",
"tr":"Türkisch",
"vi":"Vietnamesisch",
"th":"Thai",
"ko":"Koreanisch",
"fa":"Farsi",
"id":"Indonesisch",
"cy":"Walisisch",
"el":"griechisch",
"ro":"rumänisch",
"hu":"ungarisch",
"pl":"Polieren",
transimprovetitle:"Übersetzung verbessern",
transnote:"Die Übersetzung ist ein Zusammenschluss von maschineller Übersetzung und menschlichem Feedback. Vielen Dank, dass Sie sich die Zeit genommen haben, einen Beitrag zu leisten.",
transorigin:"Original in",
transsuggest:"Übersetzung in",
transsubmit:"Übersetzung einreichen",
press:"Berühren",
forillustration:"zur Veranschaulichung",
storylang:"Geschrieben in Sprache:",
footer0:"Über ResearchX3D",
footer1:"Suche nach Objekten, Geschichten und Fragen",
footer2:"Stellen Sie eine Frage zum Objekt",
footer3:"Erweiterte Realität",
footer4:"Objekt senden",
footer5:"Geschichte einreichen",
footer_title1:"SCHNELLE LINKS",
footer_title2:"SOZIALE LINKS",
navigation:"Navigation",
rotation:"rotieren",
move:"bewegen, oder",
zoom:"Zoomen Sie das Objekt",
clickForStory:"Klicken Sie hier, um die Geschichte des Objekts zu sehen.",
latexAdd:"oder zum LaTeX-Dokument hinzufügen",
latexPDF:"PDF-Bild hier herunterladen",
latexCode:"und fügen Sie den folgenden Code hinzu.",
latexCaption1:"QR-Code scannen oder eingeben",
latexCaption2:"um ein Objekt zu öffnen.",
contributeHeader:"WERDEN SIE BEITRAG",
contribute1:"Sehen Sie sich ein kurzes Video über die Motivation hinter ResearchX3D an ...",
contribute2:"... oder sehen Sie sich nur eine 4-minütige ResearchX3D-Einführung an.",
contribute3:"ResearchX3D erstellt 3D-Modelle aus Ihren Fotos ...",
contribute4:"... Sie können aber auch bereits erstellte 3D-Objekte hochladen, beispielsweise aus einer CAD-Software.",
contribute5:"Jedes Objekt hat viele Geschichten zu erzählen. Durch das Erstellen verschiedener Arten von Geschichten können Sie:",
contribute6:"Erläutern Sie eine Funktion und ein Design. oder",
contribute7:"Testen Sie Ihr Wissen mit einem Quiz. oder",
contribute8:"Teilen Sie Fähigkeiten und Verfahren.",
contribute9:"So hilft Ihnen der ResearchX3D-Editor beim Erstellen einer Story.",
clickvideo:"Klicken Sie hier, um das Video zu sehen.",
clickexample:"Klicken Sie hier, um ein Beispiel zu sehen",
openstory:"Öffne diese Geschichte",
allsbj:"alle Themenbereiche",
showall:"zeige alle",
graphic:"grafik",
figclick:"Finden Sie Geschichten und Anmerkungen zu diesem Objekt",
openar:"offen in Augmented Reality",
meniagora:"Community-Diskussionen - Agora",
r3dsummary:"<b> Was ist ResearchX3D? </ b> Eine offene Community-Plattform zum Teilen des wissenschaftlichen Erbes, um kreativen Wert für die Zukunft freizusetzen.",
agoraad:"<b> Schlagen Sie Ideen zum ResearchX3D-Projekt vor und diskutieren Sie sie </ b> und holen Sie sich Hilfe zu unserer Agora <img class = 'link' src = '/link.png'> für Community-Diskussionen."
};
