const lang_nl ={close:"Dichtbij",
loadingmodel:"Model laden",
menistartpage:"Startpagina",
menifind:"Zoek objecten, verhalen en vragen",
meniadd:"Objectverhaal toevoegen of bewerken",
meniask:"Stel een vraag over het object",
meniupload:"Upload objectfoto's voor 3D-model",
menishare:"Deel object of verhaal",
meniar:"Augmented reality ...",
meniaron:"Schakel de AR-modus in",
menimarker:"AR-markeringen afdrukken",
menisupport:"Contact opnemen met ondersteuning",
meniabout:"Over ResearchX3D",
menilogin:"Log in",
menilogout:"Uitloggen",
headfind:"Vind",
headfindt:"Zoeken naar experimenteel apparaat",
headcontribute:"Bijdragen",
headcontributet:"Help ons met het verzamelen van objecten!",
headaron:"AR AAN",
headaront:"Klik om Augmented Reality in te schakelen",
headaroff:"AR UIT",
headarofft:"Klik om AR uit te schakelen",
meni0_0:"VOOR STUDENTEN",
meni0_1:"Vind. Alles van historische experimenten tot fijnafstelschroeven.",
meni0_2:"Raak geïnspireerd. Breid uw eigen creatieve ruimte uit door na te denken over verschillende ontwerpmogelijkheden.",
meni1_0:"VOOR OPVOEDERS",
meni1_1:"Gebruik. Weergeven in presentaties en cursussen.",
meni1_2:"Maken. Annoteer objecten volgens uw eigen beschrijving en deel uw verhaal erover.",
meni2_0:"VOOR ONDERZOEKERS",
meni2_1:"Bijdragen. Er is één koffiepauze nodig om dat apparaat waar je elke dag langskomt te delen met een hele wereld.",
meni2_2:"Explore. Volg de ontwikkeling van ontwerpideeën.",
aboutheader:"Over de ResearchX3D.com",
aboutteam:"Team",
aboutcontact:"contant",
about0:"Laten we wetenschappelijk erfgoed delen om creatieve waarde voor de toekomst te ontsluiten! Experimentele apparatuur is een sleutelelement in wetenschappelijk onderzoek. Zowel historische experimenten als moderne ontwerpen zijn waardevol erfgoed. Als deze objecten eenmaal zijn gedeeld, worden ze een nuttige bron en stimuleren ze de creativiteit van mensen over de hele wereld. En nu is het mogelijk om experimentele appparatus te delen tijdens de koffiepauze!",
about1:"Wat doet ResearchX3D.com?",
about2:"Gebaseerd op <b> door gebruikers geüploade foto's </b> van wetenschappelijke apparaten uit hun laboratoria, universitaire gangen en kantoorrekken ...",
about3:"... we <b> 3D-modellen maken </b> verkenbaar door iedereen in de webbrowser.",
about4:"Met ResearchX3D.com kunt u vervolgens de impact van erfgoed vergroten en kennis op apparaten verzamelen:",
about5:"<b> 3D-labels </b> van objecten met markeringen en pijlen in 3D-ruimte is eenvoudig te doen via de online-editor. Annotaties kunnen vergezeld gaan van <b> tekstuele en audiobeschrijvingen </b>;",
about6:"Groepen labels maken verhalen over de objecten. Gebruikers kunnen <b> verhalen vinden op basis van hun kennisniveau </b>. Gebruikers in het hele spectrum komen aan bod: van het basisonderwijs en het middelbaar onderwijs, via gedetailleerde beschrijvingen op universitair niveau tot geavanceerde discussies over appartusontwerp voor promotie- / onderzoeksniveau;",
about7:"Iedereen kan een vraag stellen. Zowel <b> vragen als antwoorden </b> gebruiken 3D-labels voor <b> \"point-and-tell\" -beschrijvingen </b>. De beste antwoorden worden door de gebruikers gestemd;",
about8:"Objecten zijn te zien in <b> augmented reality </b>, waardoor iedereen experimentele apparaten op hun bureau kan zien;",
about9:"Alle functionaliteit wordt via de webinterface gebracht (geen installatie, platformonafhankelijk), waardoor <b> eenvoudig delen </b> van objecten en verhalen mogelijk is door koppelingen naar collega's en vrienden te sturen.",
about10:"Het ResearchX3D.com-platform is gericht op",
about12:"Natuurkundigen, momenteel Marie Curie-postdoctorale fellows bij <a href=\"https://www.institutoptique.fr/\"> Institute d'Optique, Palaiseau, Frankrijk </a>.",
about13:"Neem contact met ons op via <a href='mailto:contact@researchx3d.com?subject=Feedback'> contact@researchx3d.com </a>.",
aboutli0:"Objectmodellen van wetenschappelijk en technisch erfgoed bewaren;",
aboutli1:"Leg ontwerpbeschrijvingen van onderzoekers vast om ontwerpideeën en trucs voor de toekomst veilig te stellen;",
aboutli2:"Presenteer erfgoed op een manier die de creatieve ruimte van publiek over de spectra inspireert en uitbreidt, van onderwijs tot onderzoeksniveau; en",
aboutli3:"Democratiseer de toegang tot het ontwerp van experimentele apparaten door iets te nemen dat voorheen alleen toegankelijk was voor enkele gelukkigen en het over de hele wereld te delen.",
findobject:"Zoeken naar object ...",
findstory:"... en kies vervolgens verhaal / annotatie",
findquestion:"... of bekijk vragen en antwoorden",
filtersubject:"Filteren op onderwerp:",
filterknowledgelevel:"Filteren op kennisniveau:",
shareqr:"Deel experimenteel apparaat en verhaal met directe link of QR-code",
click2copy:"klik om link te kopiëren",
saveqr:"Afbeelding met QR-code opslaan",
askquestion:"Stel een vraag",
share:"delen",
addmodifystory:"Voeg uw verhaal toe / wijzig het",
depositedby:"Gestort door",
logoutsuccess:"U bent succesvol uitgelogd!",
objectannotation:"Object annotatie:",
objectannotationt:"klik om een ​​andere annotatie te selecteren",
by:"door",
location:"Plaats",
details:"Details",
tags:"Tags",
forthisobject:"voor dit object",
object:"voorwerp",
previousm:"Vorige paragraaf",
nextm:"Volgende sectie",
or:"of",
moto:"Het delen van wetenschappelijk erfgoed om creatieve waarde voor de toekomst te ontsluiten.",
pleaselogin:"Log in om door te gaan",
enteremail:"Voer email in",
enterpassword:"Voer wachtwoord in",
login:"Log in",
forgotpassword:"Wachtwoord vergeten?",
cancel:"annuleren",
newuser:"Nieuwe gebruiker?",
loginnote1:"Om objecten, annotaties toe te voegen en vragen te stellen en te beantwoorden moet je inloggen.",
loginnote2:"Om wijzigingen op te slaan, moet u eerst uw identiteit bevestigen en vervolgens op 'Opslaan' drukken.",
add:"Toevoegen",
remove:"verwijderen",
finally:"Tenslotte",
annotation:"verhaalsegment",
savestory:"verhaal opslaan",
level1:"Lagere school",
level2:"middelbare school",
level3:"universiteit (niet-gegradueerde)",
level4:"PhD / onderzoek",
addmarker:"Markering toevoegen",
addarrow:"pijl toevoegen",
textual:"tekstueel",
audio:"audio",
addexp:"Toevoegen",
explanation:"beschrijving voor deze annotatie",
marker:"markeerstift",
arrow:"pijl",
at:"Bij",
angle:"hoek",
arintro:"Plaats de markering <a href=\"/print_marker.pdf\"><img src = \"\\ar_marker_small.png\" align = \"middle\" si></a> in de cameraweergave. <br/> Klik op de pijlen links en rechts om door het verhaal te navigeren.",
noexistingaudio:"Geen bestaande audiobeschrijvingen.",
newupload:"Nieuwe upload",
newrecording:"Nieuwe opname",
recordsound:"Start met opnemen",
stopbutton:"Stop met opnemen",
storytitle:"Verhaaltitel",
storydesc:"Korte samenvatting van dit objectverhaal ...",
adddesc:"Voeg een beschrijving toe voor deze annotatie ...",
arrowadjust:"Pas de pijlpositie en richting aan en vervolgens",
markeradjust:"Pas de markeringspositie aan en vervolgens",
savemarker:"bewaar marker",
savearrow:"pijl opslaan",
audiodesc:"Audiobeschrijving:",
clicktochangelan:"Klik om de taal te wijzigen",
getarmarkers:"krijg augmented reality-markeringen",
contributeh2:"Draag apparaat bij ... het duurt één koffiepauze!",
contributeh3_1:"Hoe het werkt?",
contributeh3_2:"Klaar? Begin hier...",
contributeli1:"<b> U </b> upload ~ 30 foto's van het experimentele apparaat dat u documenteert. Probeer foto's zo te maken dat elk punt op een object op 3-6 foto's vanuit verschillende hoeken wordt gezien. Meer foto's is beter dan minder foto's!",
contributeli2:"<b> We bouwen een 3D-model van uw foto's </b>, met behulp van fotogrammetriesoftware, en zetten het online op de ResearchX3D",
contributeli3:"<b> Iedereen </b> kan verkennen, annoteren, vragen stellen en een gereconstrueerd 3D-model delen zodra het online is. U als eigenaar ontvangt de eerste uitnodiging om aantekeningen en verhalen toe te voegen, die worden gemarkeerd als originele aantekeningen.",
contributep1:"Dat is alles, het onderzoekerfgoed is wereldwijd beschikbaar voor andere studenten, docenten en onderzoekers.",
contributep2:"Op dit moment accepteren we alleen bijdragen van gebruikers met academische e-mails. Als u geen academische e-mail heeft maar wel wilt bijdragen, gelieve <input type=\"button\" onclick=\"openBoard('aboutProject');\" value=\"contact\" />.",
contributestart:"Start objectfoto-upload",
newuserh3:"Nieuwe gebruiker registratie",
newuseri1:"Naam",
newuseri1l:" Uw naam en achternaam verschijnen naast de objecten die u uploadt / annoteert.",
newuseri2:"Achternaam",
newuseri3:"Instelling en land",
newuseri3l:" Uw affiliatie en land van vestiging.",
newuseri4:"e-mail",
newuseri4l:" Opmerking: alleen accademische e-mails worden geaccepteerd. U ontvangt een bevestigingslink.",
newuseri5:"Voer wachtwoord in",
newuseri5l:" Minimaal 8 tekens.",
newuseri6:"herhaal wachtwoord",
newuseri6l:" Om te controleren of er geen typefouten zijn.",
newusersubmit:"Registreer een nieuwe gebruiker",
uploadedobjects:"Bestaande geüploade objecten:",
nameobject:"Geef uw nieuwe object een naam",
enterobjectname:"voer een nieuwe objectnaam in",
and:"en",
cratephotospace:"maak ruimte voor foto's",
photolisting:"Lijst met foto's van",
nophotolist:"Je hebt nog geen foto's geüpload voor een object. Upload hieronder objectfoto's.",
uploadnewphotos:"Upload nieuwe bestanden",
startupload:"Start uploaden",
metadataobject:"Metadata over gefotografeerd object",
objtitle:"Object titel",
objtitlel:"Object titel",
objdetails:"Object details",
objdetailsl:"korte objectbeschrijving",
objlocation:"Oorspronkelijke en huidige locatie van het object",
objyear:"Jaar waarop object is gemaakt (schatting)",
objtags:"Object tags",
objsubmit:"Foto indienen voor 3D-objectreconstructie",
newobjectspaceerror:"Er is een fout opgetreden bij het maken van uw objectruimte:",
newobjectspacesuccess:"Met succes ruimte gemaakt voor foto's van een nieuw object.",
objsubmerr1:"FOUT: u moet enkele <b> objecttags </b> toevoegen voordat u deze verzendt!",
objsubmerr2:"FOUT: objectnaam moet minimaal 3 tekens bevatten",
objsubmerr3:"FOUT: voer minimaal 10 tekens in voor objectbeschrijving.",
objsubmerr4:"FOUT: voer de locatie van het object in (historisch, heden of bedrijf waar het beschikbaar is).",
objsubmerr5:"FOUT: voer het jaar van objectcreatie in (geschat).",
delete:"verwijderen",
question:"Vraag",
answers:"antwoorden",
addeditanswer:"Voeg uw antwoord toe of bewerk het",
clickdownvotel:"klik om de vraag of het antwoord te verlagen",
clickupvotel:"klik om vraag of antwoord te stemmen",
yourquestion:"Uw vraag:",
questiondesc:"Voeg een annotatie toe op het object en beschrijf tekstuele details van de vraag.",
submitquestion:"Vraag indienen",
tooltipmainm:"Klik om het hoofdmenu te openen",
meniobject:"Voorwerp",
questiontitle:"Vraag Titel",
aboutfunding:"Funding",
about15:"Project ondersteund door de Science and Society of La Diagonale Paris-Saclay.",
size:"grootte",
color:"kleur",
red:"rood",
green:"groen",
blue:"blauw",
orange:"oranje",
magenta:"magenta",
selectlicense:"Selecteer licentie voor geüploade bestanden (het gereconstrueerde model wordt vrijgegeven onder dezelfde licentie)",
read:"lezen",
licensetext:"licentie",
translated:"vertaald",
transsee:"zie vertaling in",
transsource:"Originele tekst",
transseesource:"zie origineel in",
transimprove:"vertaling verbeteren",
"fr":"Frans",
"en":"Engels",
"es":"Spaans",
"pt":"portugese",
"de":"Duitse",
"zh":"Chinese",
"ru":"Russisch",
"ar":"Arabisch",
"sv":"Zweeds",
"nl":"Nederlands",
"it":"Italiaans",
"ja":"Japans",
"sr":"Servisch",
"cs":"Tsjechisch",
"da":"Deens",
"sw":"Swahili",
"hi":"Hindi",
"tr":"Turks",
"vi":"Vietnamees",
"th":"Thais",
"ko":"Koreaans",
"fa":"farsi",
"id":"Indonesisch",
"cy":"wels",
"el":"Grieks",
"ro":"Roemeense",
"hu":"Hongaars",
"pl":"Pools",
transimprovetitle:"Vertaling verbeteren",
transnote:"Vertalen is een inspanning van machinevertaling en feedback van mensen. Bedankt dat je de tijd hebt genomen om bij te dragen.",
transorigin:"Origineel in",
transsuggest:"Vertaling in",
transsubmit:"Vertaling indienen",
press:"Touch",
forillustration:"ter illustratie",
storylang:"Geschreven in taal:",
footer0:"Over ResearchX3D",
footer1:"Zoek objecten, verhalen en vragen",
footer2:"Stel vragen over het object",
footer3:"Augmented reality",
footer4:"Object indienen",
footer5:"Verhaal indienen",
footer_title1:"SNELLE LINKS",
footer_title2:"SOCIALE LINKS",
navigation:"Navigatie",
rotation:"draaien",
move:"verplaatsen, of",
zoom:"zoom op het object",
clickForStory:"Klik hier om het verhaal van het object te zien.",
latexAdd:"of voeg toe aan LaTeX-document",
latexPDF:"download hier de PDF-afbeelding",
latexCode:"en voeg onderstaande code toe.",
latexCaption1:"Scan de QR-code of ga naar binnen",
latexCaption2:"om object te openen.",
contributeHeader:"WORD EEN BIJDRAGEER",
contribute1:"Bekijk een korte video over de motivatie achter ResearchX3D ...",
contribute2:"... of bekijk een ResearchX3D-introductie van 4 minuten.",
contribute3:"ResearchX3D maakt 3D-modellen van uw foto's ...",
contribute4:"... maar u kunt ook reeds gemaakte 3D-objecten uploaden, bijvoorbeeld vanuit CAD-software.",
contribute5:"Elk object heeft veel verhalen te vertellen. Door verschillende soorten verhalen te maken, kunt u:",
contribute6:"Leg een functie en een ontwerp uit; of",
contribute7:"Test kennis met een quiz; of",
contribute8:"Deel vaardigheden en procedures.",
contribute9:"Hier is hoe de ResearchX3D-editor u helpt om een verhaal te maken.",
clickvideo:"Klik hier om de video te zien.",
clickexample:"Klik hier voor een voorbeeld",
openstory:"Open dit verhaal",
allsbj:"alle vakgebieden",
showall:"toon alle",
graphic:"grafisch",
figclick:"Vind verhalen en aantekeningen over dit object",
openar:"geopend in Augmented Reality",
meniagora:"Gemeenschapsdiscussies - Agora",
r3dsummary:"<b> Wat is ResearchX3D? </b> Een open communityplatform voor het delen van wetenschappelijk erfgoed om creatieve waarde voor de toekomst te ontsluiten.",
agoraad:"<b> Suggereer en bespreek </b> ideeën over het ResearchX3D-project, en krijg hulp op onze Agora <img class = 'link' src = '/link.png'> voor communitydiscussies."
};
