const lang_vi ={close:"Đóng",
loadingmodel:"Đang tải mô hình",
menistartpage:"Trang chủ",
menifind:"Tìm đối tượng, câu chuyện và câu hỏi",
meniadd:"Thêm hoặc chỉnh sửa câu chuyện đối tượng",
meniask:"Đặt câu hỏi về đối tượng",
meniupload:"Tải ảnh đối tượng lên mô hình 3D",
menishare:"Chia sẻ đối tượng hoặc câu chuyện",
meniar:"Hiện thực mở rộng ...",
meniaron:"Bật chế độ AR",
menimarker:"In đánh dấu AR",
menisupport:"Liên hệ hỗ trợ",
meniabout:"Giới thiệu về ResearchX3D",
menilogin:"Đăng nhập",
menilogout:"Đăng xuất",
headfind:"Tìm thấy",
headfindt:"Tìm kiếm bộ máy thí nghiệm",
headcontribute:"Góp phần",
headcontributet:"Hãy giúp chúng tôi phát triển bộ sưu tập các đối tượng!",
headaron:"AR ON",
headaront:"Nhấn vào đây để bật thực tế Augmented",
headaroff:"TẮT AR",
headarofft:"Nhấn vào đây để tắt AR",
meni0_0:"DÀNH CHO SINH VIÊN",
meni0_1:"Tìm thấy. Tất cả mọi thứ từ các thí nghiệm lịch sử, đến các vít điều chỉnh tốt.",
meni0_2:"Lấy cảm hứng. Mở rộng không gian sáng tạo của riêng bạn bằng cách suy nghĩ về các khả năng thiết kế khác nhau.",
meni1_0:"DÀNH CHO NHÀ GIÁO DỤC",
meni1_1:"Sử dụng. Hiển thị trong các bài thuyết trình và các khóa học.",
meni1_2:"Tạo nên. Chú thích các đối tượng theo mô tả của riêng bạn và chia sẻ câu chuyện của bạn về chúng.",
meni2_0:"DÀNH CHO CÁC NHÀ NGHIÊN CỨU",
meni2_1:"Góp phần. Phải mất một lần uống cà phê để chia sẻ bộ máy mà bạn đang đi qua mỗi ngày với cả thế giới.",
meni2_2:"Khám phá. Theo dõi phát triển ý tưởng thiết kế.",
aboutheader:"Giới thiệu về ResearchX3D.com",
aboutteam:"Đội",
aboutcontact:"Tiếp",
about0:"Hãy chia sẻ di sản khoa học để mở khóa giá trị sáng tạo cho tương lai! Bộ máy thí nghiệm là yếu tố chính trong nghiên cứu khoa học. Cả thí nghiệm lịch sử và thiết kế hiện đại đều là di sản quý giá. Một khi các đối tượng này được chia sẻ, chúng trở thành tài nguyên hữu ích, kích thích sự sáng tạo của mọi người trên khắp thế giới. Và bây giờ có thể chia sẻ appparatus thử nghiệm trong thời gian nghỉ giải lao!",
about1:"ResearchX3D.com làm gì?",
about2:"Dựa trên <b> người dùng đã tải lên ảnh </ b> của bộ máy khoa học từ phòng thí nghiệm, hành lang đại học và kệ văn phòng của họ ...",
about3:"... Chúng tôi <b> tạo mô hình 3D </ b> có thể khám phá bởi bất kỳ ai trong trình duyệt web.",
about4:"ResearchX3D.com sau đó cho phép một người tăng cường tác động của di sản và tích lũy kiến thức về bộ máy:",
about5:"<b> Ghi nhãn 3D </ b> của các đối tượng có điểm đánh dấu và mũi tên trong không gian 3D có thể dễ dàng thực hiện thông qua trình chỉnh sửa trực tuyến. Chú thích có thể được kèm theo <b> mô tả văn bản và âm thanh </ b>;",
about6:"Các nhóm nhãn làm cho câu chuyện về các đối tượng. Người dùng có thể <b> tìm các câu chuyện dựa trên mức độ kiến thức của họ </ b>. Người dùng trên toàn phổ được bảo hiểm: từ giảng dạy ở trường tiểu học và trung học, thông qua các mô tả chi tiết ở cấp đại học, đến các cuộc thảo luận nâng cao về thiết kế appartus cho cấp độ tiến sĩ / nghiên cứu;",
about7:"Mọi người có thể hỏi một câu hỏi. Cả <b> câu hỏi và câu trả lời </ b> đều sử dụng nhãn 3D cho các mô tả <b> \"nói và nói\" </ b>. Các câu trả lời tốt nhất được nâng cấp bởi người dùng;",
about8:"Các đối tượng có thể được nhìn thấy trong <b> thực tế tăng cường </ b>, cho phép mọi người nhìn thấy bộ máy thử nghiệm trên bàn của họ;",
about9:"Tất cả chức năng được đưa qua giao diện web (không cài đặt, độc lập với nền tảng), cho phép <b> chia sẻ dễ dàng </ b> các đối tượng và câu chuyện bằng cách gửi liên kết tới đồng nghiệp và bạn bè.",
about10:"Nền tảng ResearchX3D.com nhằm mục đích",
about12:"Các nhà vật lý, hiện là nghiên cứu sinh sau tiến sĩ Marie Curie tại <a href=\"https://www.institutoptique.fr/\"> Viện d'Optique, Palaiseau, Pháp </a>.",
about13:"Liên hệ với chúng tôi tại <a href='mailto:contact@researchx3d.com?subject=Feedback'> contact@researchx3d.com </a>.",
aboutli0:"Bảo tồn mô hình đối tượng của di sản khoa học và kỹ thuật;",
aboutli1:"Ghi lại các mô tả thiết kế của các nhà nghiên cứu để bảo vệ các ý tưởng và thủ thuật thiết kế cho tương lai;",
aboutli2:"Trình bày di sản theo cách truyền cảm hứng và mở rộng không gian sáng tạo trong khán giả qua quang phổ, từ giảng dạy đến cấp độ nghiên cứu; và",
aboutli3:"Dân chủ hóa quyền truy cập vào thiết kế bộ máy thử nghiệm, bằng cách lấy thứ gì đó trước đây chỉ có thể truy cập được cho một vài người may mắn và chia sẻ nó trên toàn thế giới.",
findobject:"Tìm kiếm đối tượng ...",
findstory:"... Và sau đó chọn câu chuyện / chú thích",
findquestion:"... hoặc xem câu hỏi và câu trả lời",
filtersubject:"Lọc theo lĩnh vực chủ đề:",
filterknowledgelevel:"Lọc theo cấp độ kiến thức:",
shareqr:"Chia sẻ bộ máy và câu chuyện thử nghiệm với liên kết trực tiếp hoặc mã QR",
click2copy:"nhấp để sao chép liên kết",
saveqr:"Lưu hình ảnh mã QR",
askquestion:"Hỏi câu hỏi",
share:"chia sẻ",
addmodifystory:"Thêm / sửa đổi câu chuyện của bạn",
depositedby:"Gửi bởi",
logoutsuccess:"Bạn đã đăng xuất thành công!",
objectannotation:"Chú thích đối tượng:",
objectannotationt:"nhấn vào đây để chọn chú thích khác nhau",
by:"bởi",
location:"Vị trí",
details:"Chi tiết",
tags:"Thẻ",
forthisobject:"cho đối tượng này",
object:"vật",
previousm:"Phần trước đó",
nextm:"Phần tiếp theo",
or:"hoặc là",
moto:"Chia sẻ di sản khoa học để mở khóa giá trị sáng tạo cho tương lai.",
pleaselogin:"Để tiến hành xin vui lòng đăng nhập",
enteremail:"Nhập email",
enterpassword:"Nhập mật khẩu",
login:"Đăng nhập",
forgotpassword:"Quên mật khẩu?",
cancel:"Hủy bỏ",
newuser:"Người dùng mới?",
loginnote1:"Để thêm các đối tượng, chú thích và hỏi và trả lời các câu hỏi bạn cần đăng nhập.",
loginnote2:"Để lưu các thay đổi, trước tiên bạn cần xác nhận danh tính của mình và sau đó nhấn 'Lưu'.",
add:"Thêm vào",
remove:"tẩy",
finally:"Cuối cùng",
annotation:"phân đoạn câu chuyện",
savestory:"lưu lại câu chuyện",
level1:"trường tiểu học",
level2:"Trung học phổ thông",
level3:"đại học Đại học)",
level4:"Tiến sĩ / nghiên cứu",
addmarker:"Thêm điểm đánh dấu",
addarrow:"thêm mũi tên",
textual:"văn bản",
audio:"âm thanh",
addexp:"Thêm vào",
explanation:"mô tả cho chú thích này",
marker:"đánh dấu",
arrow:"mũi tên",
at:"tại",
angle:"góc",
arintro:"Đặt điểm đánh dấu <a href=\"/print_marker.pdf\"><img src = \"\\ar_marker_small.png\" align = \"middle\" si></a> trong chế độ xem camera. <br/> Để điều hướng câu chuyện, nhấp vào mũi tên trái và phải.",
noexistingaudio:"Không có mô tả âm thanh hiện có.",
newupload:"Tải lên mới",
newrecording:"Ghi âm mới",
recordsound:"Bắt đầu thu",
stopbutton:"Dừng ghi âm",
storytitle:"Tên truyện",
storydesc:"Tóm tắt ngắn về câu chuyện đối tượng này ...",
adddesc:"Thêm mô tả cho chú thích này ...",
arrowadjust:"Điều chỉnh vị trí và hướng mũi tên, và sau đó",
markeradjust:"Điều chỉnh vị trí đánh dấu và sau đó",
savemarker:"lưu điểm đánh dấu",
savearrow:"lưu mũi tên",
audiodesc:"Mô tả âm thanh:",
clicktochangelan:"Nhấn vào đây để thay đổi ngôn ngữ",
getarmarkers:"được đánh dấu thực tế tăng cường",
contributeh2:"Bộ máy đóng góp ... phải mất một lần uống cà phê!",
contributeh3_1:"Làm thế nào nó hoạt động?",
contributeh3_2:"Sẵn sàng? Bắt đầu ở đây...",
contributeli1:"<b> Bạn </ b> tải lên ~ 30 ảnh về bộ máy thử nghiệm mà bạn đang ghi lại. Hãy thử chụp ảnh sao cho mỗi điểm trên vật thể được nhìn thấy trên 3-6 bức ảnh từ các góc khác nhau. Càng nhiều ảnh càng tốt thì càng ít ảnh!",
contributeli2:"<b> Chúng tôi xây dựng mô hình 3D từ ảnh của bạn </ b>, sử dụng phần mềm chụp ảnh và đưa nó lên mạng trên ResearchX3D",
contributeli3:"<b> Mọi người </ b> có thể khám phá, chú thích, đặt câu hỏi và chia sẻ mô hình 3D được xây dựng lại khi nó trực tuyến. Bạn là chủ sở hữu sẽ nhận được lời mời đầu tiên để thêm chú thích và câu chuyện, sẽ được đánh dấu là chú thích ban đầu.",
contributep1:"Đó là tất cả, di sản nghiên cứu có sẵn trên toàn thế giới, cho các sinh viên, nhà giáo dục và nhà nghiên cứu khác.",
contributep2:"Hiện tại, chúng tôi chỉ chấp nhận đóng góp từ người dùng có email học thuật. Trong trường hợp bạn không có email học tập nhưng muốn đóng góp, vui lòng <input type = \"button\" onclick = \"openBoard ('aboutProject');\" value = \"liên hệ với chúng tôi\" />.",
contributestart:"Bắt đầu tải ảnh đối tượng",
newuserh3:"Đăng Ký Người Dùng Mới",
newuseri1:"Tên",
newuseri1l:" Tên và họ của bạn sẽ xuất hiện bên cạnh các đối tượng bạn tải lên / chú thích.",
newuseri2:"Họ",
newuseri3:"Tổ chức giáo dục và đất nước",
newuseri3l:" Liên kết của bạn và đất nước của vị trí.",
newuseri4:"e-mail",
newuseri4l:" Lưu ý: chỉ các email accademia được chấp nhận. Bạn sẽ nhận được liên kết xác nhận.",
newuseri5:"Nhập mật khẩu",
newuseri5l:" Tối thiểu 8 ký tự.",
newuseri6:"lặp lại mật khẩu",
newuseri6l:" Chỉ cần kiểm tra không có lỗi chính tả.",
newusersubmit:"Đăng ký người dùng mới",
uploadedobjects:"Các đối tượng được tải lên hiện có:",
nameobject:"Đặt tên cho đối tượng mới của bạn",
enterobjectname:"nhập tên đối tượng mới",
and:"và",
cratephotospace:"tạo không gian cho ảnh",
photolisting:"Danh sách các bức ảnh của",
nophotolist:"Bạn chưa tải lên hình ảnh cho bất kỳ đối tượng. Vui lòng tải lên hình ảnh đối tượng dưới đây.",
uploadnewphotos:"Tải lên tệp mới",
startupload:"Bắt đầu tải lên",
metadataobject:"Siêu dữ liệu trên đối tượng được chụp ảnh",
objtitle:"Tiêu đề đối tượng",
objtitlel:"Tiêu đề đối tượng",
objdetails:"Chi tiết đối tượng",
objdetailsl:"mô tả đối tượng ngắn",
objlocation:"Vị trí ban đầu và hiện tại của đối tượng",
objyear:"Năm khi đối tượng được thực hiện (ước tính)",
objtags:"Thẻ đối tượng",
objsubmit:"Gửi ảnh để tái tạo đối tượng 3D",
newobjectspaceerror:"Có lỗi khi tạo không gian đối tượng của bạn:",
newobjectspacesuccess:"Tạo thành công không gian cho các bức ảnh của một đối tượng mới.",
objsubmerr1:"LRI: Bạn cần thêm một số <b> Thẻ đối tượng </ b> trước khi gửi!",
objsubmerr2:"LRI: Tên đối tượng phải có độ dài ít nhất 3 ký tự",
objsubmerr3:"LRI: Nhập ít nhất 10 ký tự cho mô tả đối tượng.",
objsubmerr4:"LRI: Vui lòng nhập vị trí của đối tượng (lịch sử, hiện tại hoặc công ty mà nó có sẵn).",
objsubmerr5:"LRI: Vui lòng nhập năm tạo đối tượng (ước tính).",
delete:"xóa bỏ",
question:"Câu hỏi",
answers:"Đáp án",
addeditanswer:"Thêm hoặc chỉnh sửa câu trả lời của bạn",
clickdownvotel:"nhấp để tải xuống câu hỏi hoặc câu trả lời",
clickupvotel:"nhấp để upvote câu hỏi hoặc trả lời",
yourquestion:"Câu hỏi của bạn:",
questiondesc:"Thêm chú thích vào đối tượng và mô tả chi tiết văn bản của câu hỏi.",
submitquestion:"Gửi câu hỏi",
tooltipmainm:"Nhấn vào đây để mở menu chính",
meniobject:"Vật",
questiontitle:"Tiêu đề Câu hỏi",
aboutfunding:"Kinh phí",
about15:"Dự án được hỗ trợ bởi Khoa học và Hiệp hội La Diagonale Paris-Saclay.",
size:"kích thước",
color:"màu sắc",
red:"màu đỏ",
green:"màu xanh lá",
blue:"màu xanh da trời",
orange:"trái cam",
magenta:"đỏ tươi",
selectlicense:"Chọn giấy phép cho các tệp được tải lên (mô hình được xây dựng lại sẽ được phát hành theo cùng giấy phép)",
read:"đọc",
licensetext:"giấy phép",
translated:"Đã dịch",
transsee:"xem bản dịch trong",
transsource:"Văn bản gốc",
transseesource:"xem bản gốc trong",
transimprove:"cải thiện dịch thuật",
"fr":"người Pháp",
"en":"Tiếng Anh",
"es":"người Tây Ban Nha",
"pt":"portugese",
"de":"tiếng Đức",
"zh":"người Trung Quốc",
"ru":"tiếng Nga",
"ar":"tiếng Ả Rập",
"sv":"Thụy Điển",
"nl":"Hà Lan",
"it":"người Ý",
"ja":"tiếng Nhật",
"sr":"Thành phố",
"cs":"séc",
"da":"người Đan Mạch",
"sw":"Đổ",
"hi":"tiếng Hin-ddi",
"tr":"thổ nhĩ kỳ",
"vi":"Tiếng Việt",
"th":"thái lan",
"ko":"Hàn Quốc",
"fa":"farsi",
"id":"Indonesia",
"cy":"người xứ Wales",
"el":"người Hy Lạp",
"ro":"Tiếng Rumani",
"hu":"người Hungary",
"pl":"đánh bóng",
transimprovetitle:"Cải thiện bản dịch",
transnote:"Dịch là tham gia nỗ lực của dịch máy và phản hồi đóng góp của con người. Cảm ơn bạn đã dành thời gian để đóng góp.",
transorigin:"Bản gốc trong",
transsuggest:"Dịch trong",
transsubmit:"Gửi bản dịch",
press:"Chạm",
forillustration:"để minh họa",
storylang:"Viết bằng ngôn ngữ:",
footer0:"Giới thiệu về ResearchX3D",
footer1:"Tìm kiếm đối tượng, câu chuyện và câu hỏi",
footer2:"Đặt câu hỏi về đối tượng",
footer3:"Thực tế mở rộng",
footer4:"Gửi đối tượng",
footer5:"Gửi câu chuyện",
footer_title1:"ĐƯỜNG DẪN NHANH",
footer_title2:"ĐƯỜNG LIÊN KẾT MẠNG XÃ HỘI",
navigation:"dẫn đường",
rotation:"để xoay",
move:"di chuyển, hoặc",
zoom:"phóng to đối tượng",
clickForStory:"Nhấn vào đây để xem câu chuyện của đối tượng.",
latexAdd:"hoặc thêm vào tài liệu LaTeX",
latexPDF:"tải hình ảnh PDF tại đây",
latexCode:"và thêm mã dưới đây.",
latexCaption1:"Quét mã QR hoặc nhập",
latexCaption2:"để mở đối tượng.",
contributeHeader:"TRỞ THÀNH NHÀ ĐÓNG GÓP",
contribute1:"Xem video ngắn về động lực đằng sau ResearchX3D ...",
contribute2:"... hoặc chỉ xem phần giới thiệu ResearchX3D dài 4 phút.",
contribute3:"ResearchX3D tạo mô hình 3D từ ảnh của bạn ...",
contribute4:"... nhưng bạn cũng có thể tải lên các đối tượng 3D đã được tạo, ví dụ như từ phần mềm CAD.",
contribute5:"Mỗi đối tượng đều có nhiều câu chuyện để kể. Bằng cách tạo các loại câu chuyện khác nhau, bạn có thể:",
contribute6:"Giải thích một chức năng và một thiết kế; hoặc là",
contribute7:"Kiểm tra kiến thức bằng một bài trắc nghiệm; hoặc là",
contribute8:"Chia sẻ kỹ năng và thủ tục.",
contribute9:"Đây là cách trình chỉnh sửa ResearchX3D giúp bạn tạo một câu chuyện.",
clickvideo:"Nhấn vào đây để xem video.",
clickexample:"Nhấn vào đây để xem một ví dụ",
openstory:"Mở câu chuyện này",
allsbj:"tất cả các lĩnh vực chủ đề",
showall:"hiển thị tất c",
graphic:"đồ họa",
figclick:"Tìm câu chuyện và chú thích về đối tượng này",
openar:"mở trong Thực tế tăng cường",
meniagora:"Thảo luận cộng đồng - Agora",
r3dsummary:"<b> ResearchX3D là gì? </b> Một nền tảng cộng đồng mở để chia sẻ di sản khoa học nhằm mở ra giá trị sáng tạo cho tương lai.",
agoraad:"<b> Đề xuất và thảo luận </b> ý tưởng về dự án ResearchX3D, đồng thời nhận trợ giúp trên Agora <img class = 'link' src = '/link.png'> của chúng tôi về Thảo luận cộng đồng."
};
