const lang_es ={close:"Cerrar",
loadingmodel:"Modelo de carga",
menistartpage:"Página principal",
menifind:"Encuentra objetos, historias y preguntas",
meniadd:"Agregar o editar historia de objeto",
meniask:"Haga una pregunta sobre el objeto",
meniupload:"Sube fotos de objetos para el modelo 3D",
menishare:"Compartir objeto o historia",
meniar:"Realidad aumentada...",
meniaron:"Activar el modo AR",
menimarker:"Imprimir marcadores AR",
menisupport:"Soporte de contacto",
meniabout:"Acerca de ResearchX3D",
menilogin:"Iniciar sesión",
menilogout:"Cerrar sesión",
headfind:"Encontrar",
headfindt:"Búsqueda de aparatos experimentales.",
headcontribute:"Contribuir",
headcontributet:"¡Ayúdanos a hacer crecer la colección de objetos!",
headaron:"AR ON",
headaront:"Haga clic para activar la realidad aumentada",
headaroff:"AR OFF",
headarofft:"Haga clic para desactivar AR",
meni0_0:"PARA ESTUDIANTES",
meni0_1:"Encontrar. Todo, desde experimentos históricos, hasta tornillos de ajuste fino.",
meni0_2:"Inspírate. Amplíe su propio espacio creativo pensando en diferentes posibilidades de diseño.",
meni1_0:"PARA EDUCADORES",
meni1_1:"Utilizar. Mostrar en presentaciones y cursos.",
meni1_2:"Crear. Anota objetos por tu propia descripción y comparte tu historia sobre ellos.",
meni2_0:"PARA INVESTIGADORES",
meni2_1:"Contribuir. Se necesita una pausa para café para compartir ese aparato al lado del cual pasas todos los días con todo el mundo.",
meni2_2:"Explorar. Seguimiento del desarrollo de ideas de diseño.",
aboutheader:"Sobre ResearchX3D.com",
aboutteam:"Equipo",
aboutcontact:"Contacto & equipo del proyecto",
about0:"¡Compartamos el patrimonio científico para desbloquear el valor creativo para el futuro! El aparato experimental es un elemento clave en la investigación científica. Tanto los experimentos históricos como los diseños modernos son patrimonio valioso. Una vez que estos objetos se comparten, se convierten en recursos útiles, estimulando la creatividad de las personas de todo el mundo. ¡Y ahora es posible compartir aparatos experimentales durante una pausa del café!",
about1:"¿Qué hace ResearchX3D.com?",
about2:"Basado en <b> fotografías cargadas por el usuario </b> de aparatos científicos de sus laboratorios, corredores universitarios y estanterías de oficinas ...",
about3:"... <b> creamos modelos 3D </b> explorables por cualquier persona en el navegador web.",
about4:"ResearchX3D.com luego le permite a uno mejorar el impacto del patrimonio y acumula conocimiento sobre el aparato:",
about5:"El <b> etiquetado 3D </b> de objetos con marcadores y flechas en el espacio 3D se realiza fácilmente a través del editor en línea. Las anotaciones pueden ir acompañadas de <b> descripciones textuales y de audio </b>;",
about6:"Grupos de etiquetas hacen historias sobre los objetos. Los usuarios pueden <b> encontrar historias basadas en su nivel de conocimiento </b>. Los usuarios de todo el espectro están cubiertos: desde la enseñanza primaria y secundaria, pasando por descripciones detalladas a nivel universitario, hasta debates avanzados sobre el diseño de aparato para doctorado / nivel de investigación;",
about7:"Todos pueden hacer una pregunta. Ambas <b> preguntas y respuestas </b> usan etiquetas 3D para <b> descripciones de \"apuntar y decir\" </b>. Las mejores respuestas son votadas por los usuarios;",
about8:"Los objetos se pueden ver en <b> realidad aumentada </b>, lo que permite a todos ver aparatos experimentales en su escritorio;",
about9:"Toda la funcionalidad se lleva a través de la interfaz web (sin instalación, independiente de la plataforma), lo que permite <b> compartir fácilmente </b> objetos e historias mediante el envío de enlaces a colegas y amigos.",
about10:"La plataforma ResearchX3D.com tiene como objetivo",
about12:"Físicos, actualmente becarios postdoctorales Marie Curie en <a href=\"https://www.institutoptique.fr/\"> Institute d'Optique, Palaiseau, Francia </a>.",
about13:"Contáctenos en <a href='mailto:contact@researchx3d.com?subject=Feedback'> contact@researchx3d.com </a>.",
aboutli0:"Preservar modelos de objetos del patrimonio científico y técnico;",
aboutli1:"Registrar descripciones de diseño de investigadores para salvaguardar ideas de diseño y trucos para el futuro;",
aboutli2:"Presentar el patrimonio de una manera que inspire y expanda el espacio creativo en audiencias a través de los espectros, desde la enseñanza hasta el nivel de investigación; y",
aboutli3:"Democratizar el acceso al diseño de aparatos experimentales, tomando algo previamente accesible solo para unos pocos afortunados y compartiéndolo con todo el mundo.",
findobject:"Buscar objeto ...",
findstory:"... y luego elige historia / anotación",
findquestion:"... o ver preguntas y respuestas",
filtersubject:"Filtrar por área temática:",
filterknowledgelevel:"Filtrar por nivel de conocimiento:",
shareqr:"Comparta aparatos e historias experimentales con enlace directo o código QR",
click2copy:"haga clic para copiar el enlace",
saveqr:"Guardar imagen de código QR",
askquestion:"Pregunta",
share:"compartir",
addmodifystory:"Agrega / modifica tu historia",
depositedby:"Depositado por",
logoutsuccess:"¡Ha sido desconectado exitosamente!",
objectannotation:"Anotación de objeto:",
objectannotationt:"haga clic para seleccionar una anotación diferente",
by:"por",
location:"Ubicación",
details:"Detalles",
tags:"Etiquetas",
forthisobject:"para este objeto",
object:"objeto",
previousm:"Sección previa",
nextm:"Siguiente sección",
or:"o",
moto:"Compartir el patrimonio científico para desbloquear el valor creativo para el futuro.",
pleaselogin:"Para continuar, inicie sesión",
enteremail:"Ingrese correo electrónico",
enterpassword:"Introducir la contraseña",
login:"Iniciar sesión",
forgotpassword:"¿Se te olvidó tu contraseña?",
cancel:"Cancelar",
newuser:"¿Nuevo Usuario?",
loginnote1:"Para agregar objetos, anotaciones y hacer y responder preguntas que necesita para iniciar sesión.",
loginnote2:"Para guardar los cambios, primero debe confirmar su identidad y luego presionar 'Guardar'.",
add:"Añadir",
remove:"eliminar",
finally:"Finalmente",
annotation:"segmento de la historia",
savestory:"guardar historia",
level1:"escuela primaria",
level2:"escuela secundaria",
level3:"universidad (pregrado)",
level4:"Doctorado / investigación",
addmarker:"Agregar marcador",
addarrow:"agregar flecha",
textual:"textual",
audio:"audio",
addexp:"Añadir",
explanation:"descripción de esta anotación",
marker:"marcador",
arrow:"flecha",
at:"a",
angle:"ángulo",
arintro:"Coloque el marcador <a href=\"/print_marker.pdf\"><img src = \"\\ar_marker_small.png\" align = \"middle\" si></a> en la vista de la cámara. <br/> Para navegar por la historia, haga clic en las flechas izquierda y derecha.",
noexistingaudio:"No hay descripciones de audio existentes.",
newupload:"Nueva carga",
newrecording:"Nueva grabación",
recordsound:"Iniciar la grabación",
stopbutton:"Para de grabar",
storytitle:"Título de la historia",
storydesc:"Breve resumen de esta historia de objetos ...",
adddesc:"Agregar descripción para esta anotación ...",
arrowadjust:"Ajuste la posición y orientación de la flecha, y luego",
markeradjust:"Ajuste la posición del marcador y luego",
savemarker:"guardar marcador",
savearrow:"guardar flecha",
audiodesc:"Descripción de audio:",
clicktochangelan:"Haz clic para cambiar el idioma.",
getarmarkers:"obtener marcadores de realidad aumentada",
contributeh2:"Contribuir aparato ... para eso basta una pausa de café!",
contributeh3_1:"¿Cómo funciona?",
contributeh3_2:"Listo? Empieza aqui...",
contributeli1:"<b> Usted </b> carga ~ 30 fotos del aparato experimental que está documentando. Intente tomar fotografías de manera que cada punto del objeto se vea en 3-6 fotografías desde diferentes ángulos. ¡Más fotos es mejor que menos fotos!",
contributeli2:"<b> Creamos un modelo 3D a partir de sus fotos </b>, utilizando un software de fotogrametría, y lo ponemos en línea en ResearchX3D",
contributeli3:"<b> Todos </b> pueden explorar, anotar, hacer preguntas y compartir el modelo 3D reconstruido una vez que esté en línea. Usted, como propietario, recibirá la primera invitación para agregar una anotación y una historia, que será resaltada como anotación original.",
contributep1:"Eso es todo, el patrimonio de la investigación está disponible en todo el mundo, para otros estudiantes, educadores e investigadores.",
contributep2:"Por el momento, aceptamos contribuciones solo de usuarios con correos electrónicos académicos. En caso de que no tenga correo electrónico académico pero quisiera contribuir, por favor <input type=\"button\" onclick=\"openBoard('aboutProject');\" value=\"contáctenos\" />.",
contributestart:"Iniciar carga de foto de objeto",
newuserh3:"Registro de nuevo usuario",
newuseri1:"Nombre",
newuseri1l:" Su nombre y apellido aparecerán junto a los objetos que cargue / anote.",
newuseri2:"Apellido",
newuseri3:"Institución y pais",
newuseri3l:" Su afiliación y país de ubicación.",
newuseri4:"correo electrónico",
newuseri4l:" Nota: solo se aceptan correos electrónicos académicos. Recibirá un enlace de confirmación.",
newuseri5:"Introducir la contraseña",
newuseri5l:" Mínimo de 8 caracteres.",
newuseri6:"repite la contraseña",
newuseri6l:" Solo para verificar que no hay errores tipográficos.",
newusersubmit:"Registrar un nuevo usuario",
uploadedobjects:"Objetos cargados existentes:",
nameobject:"Nombra tu nuevo objeto",
enterobjectname:"ingrese un nuevo nombre de objeto",
and:"y",
cratephotospace:"crear espacio para fotografías",
photolisting:"Listado de fotografías de",
nophotolist:"Aún no has subido fotos de ningún objeto. Por favor, suba las fotografías de los objetos a continuación.",
uploadnewphotos:"Sube nuevos archivos",
startupload:"Iniciar la subida",
metadataobject:"Metadatos en objeto fotografiado",
objtitle:"Título del objeto",
objtitlel:"Título del objeto",
objdetails:"Detalles del objeto",
objdetailsl:"descripción breve del objeto",
objlocation:"Ubicación original y actual del objeto",
objyear:"Año en que se realizó el objeto (estimación)",
objtags:"Etiquetas de objeto",
objsubmit:"Enviar foto para la reconstrucción de objetos en 3D",
newobjectspaceerror:"Se produjo un error al crear su espacio de objetos:",
newobjectspacesuccess:"Espacio creado con éxito para fotografías de un nuevo objeto.",
objsubmerr1:"ERROR: ¡Necesita agregar algunas <b> etiquetas de objeto </b> antes de enviarlas!",
objsubmerr2:"ERROR: el nombre del objeto debe tener al menos 3 caracteres de longitud",
objsubmerr3:"ERROR: Ingrese al menos 10 caracteres para la descripción del objeto.",
objsubmerr4:"ERROR: Ingrese la ubicación del objeto (histórica, presente o compañía en la que está disponible).",
objsubmerr5:"ERROR: Ingrese el año de creación del objeto (estimado).",
delete:"Eliminar",
question:"Pregunta",
answers:"Respuestas",
addeditanswer:"Agregue o edite su respuesta",
clickdownvotel:"haga clic para votar hacia abajo pregunta o respuesta",
clickupvotel:"haga clic para votar hacia arriba pregunta o respuesta",
yourquestion:"Tu pregunta:",
questiondesc:"Agregue anotaciones en el objeto y describa textualmente los detalles de la pregunta.",
submitquestion:"Enviar pregunta",
tooltipmainm:"Haga clic para abrir el menú principal",
meniobject:"Objeto",
questiontitle:"Título de la pregunta",
aboutfunding:"Fondos",
about15:"Proyecto apoyado por la Ciencia y Sociedad de La Diagonale Paris-Saclay.",
size:"Talla",
color:"color",
red:"rojo",
green:"verde",
blue:"azul",
orange:"naranja",
magenta:"magenta",
selectlicense:"Seleccione la licencia para los archivos cargados (el modelo reconstruido se lanzará bajo la misma licencia)",
read:"leer",
licensetext:"licencia",
translated:"Traducido",
transsee:"ver traducción en",
transsource:"Texto original",
transseesource:"ver original en",
transimprove:"mejorar la traducción",
"fr":"francés",
"en":"Inglés",
"es":"Español",
"pt":"portugués",
"de":"alemán",
"zh":"chino",
"ru":"ruso",
"ar":"árabe",
"sv":"sueco",
"nl":"holandés",
"it":"italiano",
"ja":"japonés",
"sr":"serbio",
"cs":"checo",
"da":"danés",
"sw":"swahili",
"hi":"hindi",
"tr":"turco",
"vi":"vietnamita",
"th":"tailandés",
"ko":"coreano",
"fa":"farsi",
"id":"indonesio",
"cy":"galés",
"el":"griego",
"ro":"rumano",
"hu":"húngaro",
"pl":"polaco",
transimprovetitle:"Mejora la traducción",
transnote:"La traducción es unir esfuerzos de traducción automática y retroalimentación humana. Gracias por tomarse el tiempo para contribuir.",
transorigin:"Original en",
transsuggest:"Traducción en",
transsubmit:"Enviar traducción",
press:"Toque",
forillustration:"por ilustracion",
storylang:"Escrito en lenguaje:",
footer0:"Sobre ResearchX3D",
footer1:"Buscar objetos, historias y preguntas",
footer2:"Preguntar sobre el objeto",
footer3:"Realidad aumentada",
footer4:"Enviar objeto",
footer5:"Enviar historia",
footer_title1:"ENLACES RÁPIDOS",
footer_title2:"VÍNCULOS SOCIALES",
navigation:"Navegación",
rotation:"rotar",
move:"moverse o",
zoom:"acercar el objeto",
clickForStory:"Haga clic aquí para ver la historia del objeto.",
latexAdd:"o agregar al documento LaTeX",
latexPDF:"descargar imagen PDF aquí",
latexCode:"y agregue el código a continuación.",
latexCaption1:"Escanee el código QR o ingrese",
latexCaption2:"para abrir objeto.",
contributeHeader:"CONVIÉRTETE EN CONTRIBUYENTE",
contribute1:"Vea un breve video sobre la motivación detrás de ResearchX3D ...",
contribute2:"... o vea solo una introducción de ResearchX3D de 4 minutos.",
contribute3:"ResearchX3D crea modelos 3D a partir de sus fotografías ...",
contribute4:"... pero también puede cargar objetos 3D ya creados, por ejemplo, desde un software CAD.",
contribute5:"Cada objeto tiene muchas historias que contar. Al crear diferentes tipos de historias, puede:",
contribute6:"Explicar una función y un diseño; o",
contribute7:"Pon a prueba tus conocimientos con una prueba; o",
contribute8:"Comparta habilidades y procedimientos.",
contribute9:"Así es como el editor de ResearchX3D le ayuda a crear una historia.",
clickvideo:"Haga clic aquí para ver el video.",
clickexample:"Haga clic aquí para ver un ejemplo",
openstory:"Abre esta historia",
allsbj:"todas las áreas temáticas",
showall:"mostrar todo",
graphic:"gráfico",
figclick:"Encuentra historias y anotaciones sobre este objeto.",
openar:"abierto en Realidad Aumentada",
meniagora:"Debates comunitarios - Agora",
r3dsummary:"<b> ¿Qué es ResearchX3D? </b> Una plataforma comunitaria abierta para compartir el patrimonio científico y desbloquear el valor creativo para el futuro.",
agoraad:"<b> Sugiera y discuta </b> ideas sobre el proyecto ResearchX3D y obtenga ayuda en nuestro Agora <img class = 'link' src = '/link.png'> para debates comunitarios."
};
