const lang_ko ={close:"닫기",
loadingmodel:"모델로드",
menistartpage:"홈페이지",
menifind:"대상, 이야기 및 질문 찾기",
meniadd:"객체 스토리 추가 또는 편집",
meniask:"물체에 관한 질문",
meniupload:"3D 모델 용 객체 사진 업로드",
menishare:"대상 또는 이야기 공유",
meniar:"증강 현실...",
meniaron:"AR 모드를 켭니다",
menimarker:"AR 마커 인쇄",
menisupport:"연락처 지원",
meniabout:"ResearchX3D 정보",
menilogin:"로그인",
menilogout:"로그 아웃",
headfind:"검색",
headfindt:"실험 장치 검색",
headcontribute:"기부",
headcontributet:"우리가 사물 컬렉션을 키울 수 있도록 도와주세요!",
headaron:"AR ON",
headaront:"증강 현실을 켜려면 클릭하십시오",
headaroff:"아칸소 OFF",
headarofft:"AR을 끄려면 클릭",
meni0_0:"학생들을 위해",
meni0_1:"검색. 역사적 실험에서 미세 조정 나사에 이르기까지 모든 것이 있습니다.",
meni0_2:"영감을 얻으십시오. 다양한 디자인 가능성에 대해 생각하여 자신 만의 창의적인 공간을 확장하십시오.",
meni1_0:"교육자",
meni1_1:"사용하다. 프리젠 테이션 및 코스에 표시합니다.",
meni1_2:"창조하다. 자신의 설명으로 개체에 주석을 달고 이에 대한 이야기를 공유하십시오.",
meni2_0:"연구원",
meni2_1:"기부하십시오. 매일 지나가는 기기를 전 세계 사람들과 공유하려면 한 번의 커피 브레이크가 필요합니다.",
meni2_2:"탐색하십시오. 디자인 아이디어 개발을 추적합니다.",
aboutheader:"ResearchX3D.com 정보",
aboutteam:"팀",
aboutcontact:"고정",
about0:"과학적 유산을 공유하여 미래를위한 창조적 인 가치를 실현하십시오! 실험 장치는 과학 연구의 핵심 요소입니다. 역사적인 실험과 현대적인 디자인은 모두 귀중한 유산입니다. 이러한 개체가 공유되면 유용한 리소스가되어 전 세계 사람들의 창의력을 자극합니다. 이제 커피 휴식 시간 동안 실험기구를 공유 할 수 있습니다!",
about1:"ResearchX3D.com은 무엇을합니까?",
about2:"실험실, 대학 복도 및 사무실 선반에서 과학 장비의 <b> 사용자가 업로드 한 사진 </ b>을 기반으로합니다 ...",
about3:"... 웹 브라우저 사용자라면 누구나 탐색 할 수있는 <b> 3D 모델을 생성 </ b>합니다.",
about4:"ResearchX3D.com은 문화 유산의 영향을 강화하고 장치에 대한 지식을 축적 할 수 있도록합니다.",
about5:"3D 공간에 마커와 화살표가있는 개체의 <b> 3D 라벨링 </ b>은 온라인 편집기를 통해 쉽게 수행 할 수 있습니다. 주석에는 <b> 텍스트 및 오디오 설명 </ b>이 수반 될 수 있습니다.",
about6:"라벨 그룹은 객체에 대한 이야기를 만듭니다. 사용자는 <b> 지식 수준에 따라 스토리를 찾을 수 있습니다 </ b>. 초등 및 고등학교 교육에서 대학 수준의 자세한 설명을 통해 박사 / 연구 수준의 아파트 디자인에 대한 고급 토론에 이르기까지 다양한 범위의 사용자가 다룹니다.",
about7:"누구나 질문을 할 수 있습니다. <b> 질문과 답변 </ b>은 <b> \"지점 및 설명\"설명 </ b>에 3D 라벨을 사용합니다. 최상의 답변은 사용자에 의해 상향 조정됩니다.",
about8:"<b> 증강 현실 </ b>에서 물체를 볼 수 있으므로 모든 사람이 책상에서 실험 장치를 볼 수 있습니다.",
about9:"모든 기능은 웹 인터페이스 (설치없이, 플랫폼 독립적)를 통해 제공되므로 동료 및 친구에게 링크를 보내어 오브젝트와 스토리를 <b> 쉽게 공유 </ b> 할 수 있습니다.",
about10:"ResearchX3D.com 플랫폼 목표",
about12:"물리학 자, 현재 Marie Curie 박사후 연구원은 <a href=\"https://www.institutoptique.fr/\"> 프랑스 Palaiseau 연구소 d' Optique </a>에 있습니다.",
about13:"<a href='mailto:contact@researchx3d.com?subject=Feedback'> contact@researchx3d.com </a>으로 문의하세요.",
aboutli0:"과학 및 기술 유산의 객체 모델을 보존합니다.",
aboutli1:"미래의 설계 아이디어와 트릭을 보호하기 위해 연구원의 설계 설명을 기록합니다.",
aboutli2:"교육에서 연구 수준에 이르기까지 스펙트럼을 가로 질러 관객의 창조적 공간을 고무하고 확장하는 방식으로 유산을 제시하십시오. 과",
aboutli3:"소수의 운이 좋은 사람들에게만 접근 할 수있는 것을 가지고 전 세계에 공유함으로써 실험 장치 설계에 대한 접근을 민주화하십시오.",
findobject:"객체 검색 ...",
findstory:"... 그리고 이야기 / 주석을 선택하십시오",
findquestion:"... 또는 질문과 답변을 참조하십시오",
filtersubject:"주제 영역으로 필터링 :",
filterknowledgelevel:"지식 수준별로 필터링 :",
shareqr:"직접 링크 또는 QR 코드로 실험 장치 및 스토리 공유",
click2copy:"링크를 클릭하여 복사",
saveqr:"QR 코드 이미지 저장",
askquestion:"물어보다",
share:"공유",
addmodifystory:"스토리 추가 / 수정",
depositedby:"에 의해 입금",
logoutsuccess:"성공적으로 로그 아웃되었습니다!",
objectannotation:"객체 주석 :",
objectannotationt:"다른 주석을 선택하려면 클릭",
by:"으로, ~에 의하여",
location:"위치",
details:"세부",
tags:"태그",
forthisobject:"이 객체를 위해",
object:"목적",
previousm:"이전 섹션",
nextm:"다음 섹션",
or:"또는",
moto:"과학적 유산을 공유하여 미래를위한 창의적인 가치를 실현합니다.",
pleaselogin:"계속하려면 로그인하십시오",
enteremail:"이메일을 입력",
enterpassword:"암호를 입력",
login:"로그인",
forgotpassword:"비밀번호를 잊으 셨나요?",
cancel:"취소",
newuser:"새로운 사용자?",
loginnote1:"객체, 주석을 추가하고 질문하고 질문에 응답하려면 로그인해야합니다.",
loginnote2:"변경 사항을 저장하려면 먼저 신원을 확인한 다음 '저장'을 누르십시오.",
add:"더하다",
remove:"없애다",
finally:"드디어",
annotation:"스토리 세그먼트",
savestory:"이야기를 저장",
level1:"초등학교",
level2:"고등학교",
level3:"대학 (학부)",
level4:"박사 / 연구",
addmarker:"마커 추가",
addarrow:"화살표 추가",
textual:"텍스트",
audio:"오디오",
addexp:"더하다",
explanation:"이 주석에 대한 설명",
marker:"채점자",
arrow:"화살",
at:"...에서",
angle:"각도",
arintro:"카메라 뷰에 <a href=\"/print_marker.pdf\"><img src = \"\\ar_marker_small.png\"align = \"middle\"si></a> 마커를 넣습니다. <br/> 스토리를 탐색하려면 왼쪽 및 오른쪽 화살표를 클릭하십시오.",
noexistingaudio:"기존 오디오 설명이 없습니다.",
newupload:"새로운 업로드",
newrecording:"새로운 녹음",
recordsound:"녹화 시작",
stopbutton:"녹화 중지",
storytitle:"이야기 제목",
storydesc:"이 객체 스토리의 간단한 요약 ...",
adddesc:"이 주석에 대한 설명 추가 ...",
arrowadjust:"화살표 위치와 방향을 조정 한 다음",
markeradjust:"마커 위치를 조정 한 다음",
savemarker:"마커 저장",
savearrow:"저장 화살표",
audiodesc:"오디오 설명 :",
clicktochangelan:"언어를 변경하려면 클릭",
getarmarkers:"증강 현실 마커 얻기",
contributeh2:"기고 장치 ... 커피 한잔이 걸립니다!",
contributeh3_1:"어떻게 작동합니까?",
contributeh3_2:"준비된? 여기서 시작하십시오 ...",
contributeli1:"<b> 귀하가 </ b> 문서화중인 실험기구의 사진을 최대 30 장 업로드하십시오. 물체의 각 점이 다른 각도에서 3-6 장의 사진으로 보이도록 사진을 찍어보십시오. 사진이 많을수록 사진이 적을수록 좋습니다!",
contributeli2:"<b> 사진 측량 소프트웨어를 사용하여 사진으로 3D 모델을 제작 </ b>하여 ResearchX3D에서 온라인으로 전환",
contributeli3:"<b> 모든 사용자 </ b>는 온라인 상태가되면 탐색, 주석 달기, 질문 및 재구성 된 3D 모델을 공유 할 수 있습니다. 소유자는 주석과 스토리를 추가하라는 첫 번째 초대를 받게되며 원래 주석으로 강조 표시됩니다.",
contributep1:"그게 전부입니다. 다른 문화 유산은 다른 학생들, 교육자 및 연구원들에게 전 세계적으로 놀라 울 수 있습니다.",
contributep2:"현재 학술 이메일을 사용하는 사용자의 기여 만 허용됩니다. 학술 이메일이 없지만 공헌하고 싶은 경우 <input type = \"button\"onclick = \"openBoard ( 'aboutProject');\" value = \"문의\"/>.",
contributestart:"객체 사진 업로드 시작",
newuserh3:"신규 사용자 등록",
newuseri1:"이름",
newuseri1l:" 귀하의 이름과 성은 업로드 / 주석 한 객체 옆에 나타납니다.",
newuseri2:"성",
newuseri3:"기관 및 국가",
newuseri3l:" 귀하의 소속 및 위치 국가.",
newuseri4:"이메일",
newuseri4l:" 참고 : 전자 메일 만 허용됩니다. 확인 링크가 나타납니다.",
newuseri5:"암호를 입력",
newuseri5l:" 최소 8 자",
newuseri6:"비밀번호 반복",
newuseri6l:" 오타가 없는지 확인하십시오.",
newusersubmit:"새로운 사용자 등록",
uploadedobjects:"기존 업로드 된 객체 :",
nameobject:"새 개체의 이름을 지정하십시오.",
enterobjectname:"새 개체 이름을 입력하십시오",
and:"과",
cratephotospace:"사진을위한 공간 만들기",
photolisting:"사진 목록",
nophotolist:"객체에 대한 사진을 아직 업로드하지 않았습니다. 아래에 대상 사진을 업로드하십시오.",
uploadnewphotos:"새 파일 업로드",
startupload:"업로드 시작",
metadataobject:"촬영 된 개체의 메타 데이터",
objtitle:"개체 제목",
objtitlel:"개체 제목",
objdetails:"객체 세부 사항",
objdetailsl:"짧은 객체 설명",
objlocation:"객체의 원본 및 현재 위치",
objyear:"대상이 작성된 연도 (추정)",
objtags:"객체 태그",
objsubmit:"3D 객체 재구성을위한 사진 제출",
newobjectspaceerror:"오브젝트 공간을 작성하는 중에 오류가 발생했습니다.",
newobjectspacesuccess:"새 물체 사진을위한 공간을 만들었습니다.",
objsubmerr1:"오류 : 제출하기 전에 <b> 개체 태그 </ b>를 추가해야합니다!",
objsubmerr2:"오류 : 개체 이름의 길이는 3 자 이상이어야합니다",
objsubmerr3:"오류 : 개체 설명으로 10 자 이상을 입력하십시오.",
objsubmerr4:"오류 : 개체의 위치 (기록, 현재 또는 사용 가능한 회사)를 입력하십시오.",
objsubmerr5:"오류 : 개체 생성 연도를 입력하십시오 (예상).",
delete:"지우다",
question:"질문",
answers:"답변",
addeditanswer:"답변 추가 또는 수정",
clickdownvotel:"질문이나 답변을 공감하려면 클릭하십시오",
clickupvotel:"질문이나 답변을 올리려면 클릭하세요",
yourquestion:"당신의 질문 :",
questiondesc:"객체에 주석을 추가하고 질문의 텍스트 세부 사항을 설명하십시오.",
submitquestion:"질문 제출",
tooltipmainm:"메인 메뉴를 열려면 클릭하십시오",
meniobject:"목적",
questiontitle:"질문 제목",
aboutfunding:"자금 조달",
about15:"La Diagonale Paris-Saclay 과학 및 사회 지원 프로젝트.",
size:"크기",
color:"색깔",
red:"빨간",
green:"초록",
blue:"푸른",
orange:"주황색",
magenta:"마젠타",
selectlicense:"업로드 된 파일에 대한 라이센스를 선택하십시오 (재구성 된 모델은 동일한 라이센스로 릴리스 됨)",
read:"읽다",
licensetext:"특허",
translated:"번역",
transsee:"번역을 참조하십시오",
transsource:"원문",
transseesource:"원본을 참조하십시오",
transimprove:"번역 향상",
"fr":"프랑스 국민",
"en":"영어",
"es":"스페인의",
"pt":"포르투갈어",
"de":"독일 사람",
"zh":"중국말",
"ru":"러시아인",
"ar":"아라비아 말",
"sv":"스웨덴어",
"nl":"네덜란드 사람",
"it":"이탈리아 사람",
"ja":"일본어",
"sr":"세르비아 사람",
"cs":"체코 사람",
"da":"덴마크 말",
"sw":"스와힐리어",
"hi":"힌디 어",
"tr":"터키어",
"vi":"베트남어",
"th":"타이",
"ko":"한국어",
"fa":"파시",
"id":"인도네시아 인",
"cy":"웨일스 말",
"el":"그리스 어",
"ro":"루마니아 사람",
"hu":"헝가리 인",
"pl":"광택",
transimprovetitle:"번역 향상",
transnote:"번역은 기계 번역과 인간이 기여한 피드백의 결합 노력입니다. 시간을내어 기여해 주셔서 감사합니다.",
transorigin:"원본",
transsuggest:"번역",
transsubmit:"번역 제출",
press:"접촉",
forillustration:"설명을 위해",
storylang:"언어로 작성 :",
footer0:"ResearchX3D 정보",
footer1:"대상, 이야기 및 질문 검색",
footer2:"물체에 대한 물음",
footer3:"증강 현실",
footer4:"객체 제출",
footer5:"스토리 제출",
footer_title1:"빠른 링크",
footer_title2:"소셜 링크",
navigation:"항해",
rotation:"회전",
move:"이동하거나",
zoom:"객체를 확대",
clickForStory:"물체의 이야기를 보려면 여기를 클릭하십시오.",
latexAdd:"또는 LaTeX 문서에 추가",
latexPDF:"여기에서 PDF 이미지를 다운로드하십시오",
latexCode:"아래 코드를 추가하십시오.",
latexCaption1:"QR 코드를 스캔하거나 입력",
latexCaption2:"개체를 열기 위해.",
contributeHeader:"기여자가 되십시오",
contribute1:"ResearchX3D의 동기 부여에 대한 짧은 동영상보기 ...",
contribute2:"... 또는 4 분 ResearchX3D 소개를 참조하십시오.",
contribute3:"ResearchX3D는 사진에서 3D 모델을 만듭니다 ...",
contribute4:"...하지만 이미 생성 된 3D 개체 (예 : CAD 소프트웨어)를 업로드 할 수도 있습니다.",
contribute5:"모든 물건에는 이야기 할 이야기가 많습니다. 다양한 유형의 스토리를 생성하여 다음을 수행 할 수 있습니다.",
contribute6:"기능과 디자인을 설명하십시오. 또는",
contribute7:"퀴즈로 지식을 테스트하십시오. 또는",
contribute8:"기술과 절차를 공유하십시오.",
contribute9:"ResearchX3D 편집기를 사용하여 스토리를 만드는 방법은 다음과 같습니다.",
clickvideo:"비디오를 보려면 여기를 클릭하십시오.",
clickexample:"예를 보려면 여기를 클릭하십시오",
openstory:"이 이야기 열기",
allsbj:"모든 주제 영역",
showall:"모두 표",
graphic:"그래픽",
figclick:"이 개체에 대한 이야기 및 주석 찾기",
openar:"증강 현실에서 열기",
meniagora:"커뮤니티 토론-아고라",
r3dsummary:"<b> ResearchX3D 란 무엇입니까? </ b> 과학 유산을 공유하여 미래를위한 창의적인 가치를 발휘할 수있는 개방형 커뮤니티 플랫폼입니다.",
agoraad:"ResearchX3D 프로젝트에 대한 아이디어를 <b> 제안 및 토론 </ b>하고 커뮤니티 토론을위한 Agora <img class = 'link'src = '/link.png'>에서 도움을 받으세요."
};
