const lang_pl = {
close:"Zamknij",
loadingmodel:"Ładowanie modelu 3D",
menistartpage:"Strona główna",
menifind:"Znajdź przedmioty, historie i pytania",
meniadd:"Dodaj lub edytuj historię",
meniask:"Zadaj pytanie na temat przedmiotu",
meniupload:"Prześlij zdjęcia do modelu 3D",
menishare:"Udostępnij przedmiot lub historię",
meniar:"Rozszerzona Rzeczywistość...",
meniaron:"Włącz tryb AR",
menimarker:"Drukuj znaczniki AR",
menisupport:"Kontakt i wsparcie",
meniabout:"Informacje o ResearchX3D",
menilogin:"Zaloguj sie",
menilogout:"Wyloguj",
headfind:"Szukaj",
headfindt:"Poszukaj aparatury eksperymentalnej",
headcontribute:"Przyczynić się",
headcontributet:"Pomóż nam rozwijać naszą kolekcję obiektów!",
headaron:"AR ON",
headaront:"Kliknij, aby włączyć Augmented Reality",
headaroff:"AR OFF",
headarofft:"Kliknij, aby wyłączyć AR",
meni0_0:"DLA UCZNIÓW",
meni0_1:"Odnaleźć. Wszystko od historycznych eksperymentów po precyzyjne śruby regulacyjne.",
meni0_2:"Zainspirować się. Poszerz swoją własną przestrzeń twórczą, myśląc o różnych możliwościach projektowych.",
meni1_0:"DLA EDUKATORÓW",
meni1_1:"Posługiwać się. Pokaż w prezentacjach i udostępnij notatki z wykładów.",
meni1_2:"Stwórz. Dodawaj adnotacje do obiektów według własnego opisu i podziel się swoją historią o nich.",
meni2_0:"DLA NAUKOWCÓW",
meni2_1:"Przyczynić się. Wystarczy jedna przerwa na kawę, aby podzielić się z całym światem aparatem, który mijasz każdego dnia.",
meni2_2:"Badać. Śledź rozwój pomysłów projektowych.",
aboutheader:"O ResearchX3D.com",
aboutteam:"Kontakt i zespół projektowy",
about0:"Podzielmy się naszym naukowym dziedzictwem, aby uwolnić nasz twórczy potencjał na przyszłość! Aparatura doświadczalna jest kluczowym elementem badań naukowych. Cennym dziedzictwem są zarówno eksperymenty historyczne, jak i nowoczesne projekty. Gdy te obiekty zostaną udostępnione, stają się użytecznymi zasobami, stymulującymi kreatywność ludzi na całym świecie. A teraz można podzielić się eksperymentalnym aparatem podczas przerwy na kawę!",
about1:"Czym zajmuje się ResearchX3D.com?",
about2:"Na podstawie <b> przesłanych przez użytkownika zdjęć </b> aparatury naukowej z ich laboratoriów, korytarzy uniwersyteckich i półek biurowych ...",
about3:"... <b> tworzymy modele 3D </b>, które każdy może przeglądać w przeglądarce internetowej.",
about4:"ResearchX3D.com pozwala następnie wzmocnić wpływ naszego dziedzictwa naukowego i gromadzić wiedzę na temat aparatury:",
about5:"<b> Etykietowanie 3D </b> obiektów ze znacznikami i strzałkami w przestrzeni 3D można łatwo wykonać za pomocą naszego edytora online. Adnotacjom mogą towarzyszyć <b> opisy tekstowe, graficzne i / lub dźwiękowe </b>;",
about6:"Grupy etykiet tworzą historie o przedmiotach. Użytkownicy mogą <b> wyszukiwać historie na podstawie swojego poziomu wiedzy </b>. Obejmuje pełne spektrum użytkowników: od nauczania w szkole podstawowej i średniej, przez szczegółowe opisy na poziomie uniwersyteckim, po zaawansowane dyskusje na temat projektowania aparatów na poziomie doktoranckim / badawczym. ResearchX3D i wybrane historie są <b> dostępne w 25 językach </b>.",
about7:"Każdy może zadać pytanie. Zarówno <b> pytania, jak i odpowiedzi </b> używają etykiet 3D do <b> opisów typu „wskaż i powiedz” </b>. Użytkownicy głosują za najlepszymi odpowiedziami;",
about8:"Obiekty można oglądać w <b> rzeczywistości rozszerzonej </b>, dzięki czemu każdy może zobaczyć eksperymentalne urządzenia na swoim biurku;",
about9:"Wszystkie funkcje działają za pośrednictwem interfejsu internetowego (bez instalacji, niezależnie od platformy), umożliwiając <b> łatwe udostępnianie </b> obiektów i historii poprzez wysyłanie linków do kolegów i przyjaciół.",
about10:"Platforma ResearchX3D.com ma na celu",
about12:"Fizycy, obecnie stypendyści Marie Curie w <a href=\"https://www.institutoptique.fr/\"> Institute d'Optique, Palaiseau, Francja </a>.",
about13:"Skontaktuj się z nami pod adresem <a href='mailto:contact@researchx3d.com?subject=Feedback'> contact@researchx3d.com </a>.",
aboutli0:"Ochrona modeli obiektów dziedzictwa naukowego i technicznego;",
aboutli1:"Zapisuj opisy projektów przez badaczy, aby chronić pomysły i sztuczki projektowe na przyszłość;",
aboutli2:"Przedstaw dziedzictwo naukowe w sposób, który inspiruje i poszerza kreatywne myślenie wśród publiczności z całego spektrum, od nauczania po poziom badań; i",
aboutli3:"Zdemokratyzuj dostęp do eksperymentalnego projektowania aparatury, biorąc coś, co wcześniej było dostępne tylko dla nielicznych szczęśliwców i udostępniając to całemu światu.",
findobject:"Szukaj obiektu ...",
findstory:"... a następnie wybierz historię / adnotację",
findquestion:"... lub zobacz pytania i odpowiedzi",
filtersubject:"Filtruj według tematu:",
filterknowledgelevel:"Filtruj według poziomu wiedzy:",
shareqr:"Udostępnij eksperymentalną aparaturę i historię za pomocą bezpośredniego łącza lub kodu QR",
click2copy:"kliknij, aby skopiować link",
saveqr:"Zapisz obraz kodu QR",
askquestion:"Zadaj pytanie",
share:"dzielić",
addmodifystory:"Dodaj / zmodyfikuj swoją historię",
depositedby:"Wpłacony przez",
logoutsuccess:"Wylogowałeś się poprawnie!",
objectannotation:"Opis obiektu",
objectannotationt:"Kliknij, aby wybrać inną adnotację",
by:"przez",
location:"Lokalizacja",
details:"Detale",
tags:"Tagi",
forthisobject:"dla tego obiektu",
object:"obiekt",
previousm:"Poprzednia sekcja",
nextm:"Następna sekcja",
or:"lub",
moto:"Dzielenie się dziedzictwem naukowym w celu odblokowania twórczej wartości na przyszłość.",
pleaselogin:"Aby kontynuować, zaloguj się",
enteremail:"Wprowadź e-mail",
enterpassword:"Wprowadź hasło",
login:"Zaloguj sie",
forgotpassword:"Zapomniałeś hasła?",
cancel:"anulować",
newuser:"Nowy użytkownik?",
loginnote1:"Aby dodawać obiekty, adnotacje i zadawać / odpowiadać na pytania, musisz się zalogować.",
loginnote2:"Aby zapisać zmiany, musisz najpierw potwierdzić swoją tożsamość, a następnie nacisnąć „Zapisz”.",
add:"Dodaj",
remove:"usunąć",
finally:"Wreszcie",
annotation:"segment opowieści",
savestory:"zapisz historię",
level1:"Szkoła Podstawowa",
level2:"Liceum",
level3:"uniwersytet (licencjat)",
level4:"Doktor / badania",
addmarker:"Dodaj znacznik",
addarrow:"dodaj strzałkę",
textual:"tekstowy",
audio:"audio",
addexp:"Dodaj",
explanation:"opis tej adnotacji",
marker:"znacznik",
arrow:"strzałka",
at:"w",
angle:"kąt",
arintro:"Umieść znacznik <a href=\"/print_marker.pdf\"><img alt = \"R3D\" src = \"\\ar_marker_small.png\" align = \"middle\" si></a> w widoku kamery. <br/> Aby poruszać się po historii, klikaj strzałki w lewo i w prawo.",
noexistingaudio:"Brak istniejących opisów dźwiękowych.",
newupload:"Nowe przesłanie",
newrecording:"Nowe nagranie",
recordsound:"Rozpocznij nagrywanie",
stopbutton:"Zatrzymaj nagrywanie",
storytitle:"Tytuł opowieści",
storydesc:"Krótkie podsumowanie tej historii obiektu ...",
adddesc:"Dodaj opis do tej adnotacji ...",
arrowadjust:"Dostosuj położenie i orientację strzałki, a następnie",
markeradjust:"Dostosuj położenie znacznika, a następnie",
savemarker:"zapisz marker",
savearrow:"zapisz strzałkę",
audiodesc:"Audiodeskrypcja:",
clicktochangelan:"Kliknij, aby zmienić język",
getarmarkers:"uzyskać znaczniki rzeczywistości rozszerzonej",
contributeh2:"Wesprzyj aparat ... to zajmie jedna przerwa na kawę!",
contributeh3_1:"Jak to działa?",
contributeh3_2:"Gotowy? Zacznij tutaj...",
contributeli1:"<b> Przesyłasz </b> ~ 30 zdjęć aparatu doświadczalnego, który dokumentujesz. Spróbuj zrobić zdjęcia w taki sposób, aby każdy punkt obiektu był widoczny na 3-6 zdjęciach pod różnymi kątami. Więcej zdjęć to lepsze niż mniej zdjęć!",
contributeli2:"<b> Tworzymy model 3D z Twoich zdjęć </b>, korzystając z oprogramowania do fotogrametrii i umieszczamy go online na ResearchX3D",
contributeli3:"<b> Każdy </b> może przeglądać, dodawać adnotacje, zadawać pytania i udostępniać zrekonstruowane modele 3D, gdy są one online. Jako właściciel otrzymasz pierwsze zaproszenie do dodania adnotacji i historii, które zostaną wyróżnione jako oryginalna adnotacja.",
contributep1:"To wszystko, dziedzictwo badawcze jest dostępne na całym świecie dla innych studentów, nauczycieli i badaczy.",
contributep2:"W tej chwili przyjmujemy tylko wkłady od użytkowników z e-mailami akademickimi. Jeśli nie masz e-maila akademickiego, ale chcesz wnieść swój wkład, <input type = \"button\" onclick = \"openBoard ('aboutProject');\" value = \"skontaktuj się z nami\" />.",
contributestart:"Rozpocznij przesyłanie zdjęcia obiektu",
newuserh3:"Rejestracja nowego użytkownika",
newuseri1:"Nazwa",
newuseri1l:" Twoje imię i nazwisko pojawią się obok obiektów, które prześlesz / oznaczysz.",
newuseri2:"Nazwisko",
newuseri3:"Instytucja i kraj",
newuseri3l:" Twoja przynależność i kraj lokalizacji.",
newuseri4:"e-mail",
newuseri4l:" Uwaga: akceptowane są tylko e-maile akademickie. Otrzymasz link potwierdzający.",
newuseri5:"Wprowadź hasło",
newuseri5l:" Minimum 8 znaków.",
newuseri6:"Powtórz hasło",
newuseri6l:" Po prostu sprawdź, czy nie ma literówek.",
newusersubmit:"Zarejestruj nowego użytkownika",
uploadedobjects:"Istniejące przesłane obiekty:",
nameobject:"Nazwij swój nowy obiekt",
enterobjectname:"wprowadź nową nazwę obiektu",
and:"i",
cratephotospace:"stworzyć przestrzeń na zdjęcia",
photolisting:"Lista zdjęć",
nophotolist:"Nie przesłałeś jeszcze zdjęć żadnego obiektu. Proszę przesłać zdjęcia poniżej.",
uploadnewphotos:"Prześlij nowe pliki",
startupload:"Zacznij przesyłać",
metadataobject:"Metadane dotyczące fotografowanego obiektu",
objtitle:"Tytuł obiektu",
objtitlel:"Tytuł obiektu",
objdetails:"Szczegóły obiektu",
objdetailsl:"krótki opis obiektu",
objlocation:"Oryginalna i aktualna lokalizacja obiektu",
objlocationl:"na przykład CERN (obecnie na University of ...)",
objyear:"Rok wykonania przedmiotu (oszacowanie)",
objtags:"Tagi obiektów",
objsubmit:"Prześlij zdjęcie do rekonstrukcji obiektu 3D",
newobjectspaceerror:"Wystąpił błąd podczas tworzenia przestrzeni obiektów:",
newobjectspacesuccess:"Pomyślnie stworzono przestrzeń na zdjęcia nowego obiektu.",
objsubmerr1:"BŁĄD: przed przesłaniem musisz dodać kilka <b> tagów obiektów </b>!",
objsubmerr2:"BŁĄD: nazwa obiektu musi mieć co najmniej 3 znaki",
objsubmerr3:"BŁĄD: wprowadź co najmniej 10 znaków w opisie obiektu.",
objsubmerr4:"BŁĄD: Proszę podać lokalizację obiektu (historyczna, obecna lub firma, z której jest dostępny).",
objsubmerr5:"BŁĄD: Proszę podać rok utworzenia obiektu (szacowany).",
delete:"usunąć",
question:"Pytanie",
answers:"Odpowiedzi",
addeditanswer:"Dodaj lub edytuj swoją odpowiedź",
clickdownvotel:"kliknij, aby zagłosować przeciw pytaniu lub odpowiedzi",
clickupvotel:"kliknij, aby zagłosować na pytanie lub odpowiedź",
yourquestion:"Twoje pytanie:",
questiondesc:"Dodaj adnotację do obiektu i odpowiedz tekstowo na pytanie.",
submitquestion:"Prześlij pytanie",
tooltipmainm:"Kliknij, aby otworzyć menu główne",
meniobject:"Obiekt",
questiontitle:"Tytuł pytania",
aboutfunding:"Finansowanie",
about15:"Projekt jest wspierany przez Science and Society of La Diagonale Paris-Saclay.",
size:"rozmiar",
color:"kolor",
red:"czerwony",
green:"Zielony",
blue:"niebieski",
orange:"Pomarańczowy",
magenta:"magenta",
selectlicense:"Wybierz licencję na przesyłane pliki (zrekonstruowany model zostanie wydany na tej samej licencji)",
read:"czytać",
licensetext:"licencja",
translated:"Przetłumaczony",
transsee:"zobacz tłumaczenie w",
transsource:"Oryginalny tekst",
transseesource:"zobacz oryginał w",
transimprove:"poprawić tłumaczenie",
"fr":"Francuski",
"en":"język angielski",
"es":"hiszpański",
"pt":"Portugalski",
"de":"Niemiecki",
"zh":"chiński",
"ru":"Rosyjski",
"ar":"arabski",
"sv":"szwedzki",
"nl":"holenderski",
"it":"Włoski",
"ja":"język japoński",
"sr":"serbski",
"cs":"Czech",
"da":"duński",
"sw":"Suahili",
"hi":"hinduski",
"tr":"turecki",
"vi":"wietnamski",
"th":"tajski",
"ko":"koreański",
"fa":"Perski",
"id":"indonezyjski",
"cy":"walijski",
"el":"grecki",
"ro":"rumuński",
"hu":"język węgierski",
"pl":"Polskie",
transimprovetitle:"Popraw tłumaczenie",
transnote:"Tłumaczenie to wspólny wysiłek tłumaczenia maszynowego i informacji zwrotnej od ludzi. Dziękuję za poświęcenie czasu.",
transorigin:"Oryginał w formacie",
transsuggest:"Tłumaczenie w",
transsubmit:"Prześlij tłumaczenie",
press:"naciśnij",
forillustration:"dla ilustracji",
storylang:"Napisane w języku:",
footer0:"Informacje o ResearchX3D",
footer1:"Szukaj obiektów, historii i pytań",
footer2:"Zadaj pytanie na temat obiektu",
footer3:"Rozszerzona Rzeczywistość",
footer4:"Prześlij obiekt",
footer5:"Prześlij historię",
footer_title1:"SZYBKIE LINKI",
footer_title2:"LINKI SPOŁECZNE",
navigation:"Nawigacja",
rotation:"obrócić",
move:"przenieść lub",
zoom:"powiększyć obiekt",
clickForStory:"Kliknij tutaj, aby zobaczyć historię obiektu.",
latexAdd:"lub dodaj do dokumentu LaTeX",
latexPDF:"pobierz obraz PDF tutaj",
latexCode:"i dodaj kod poniżej.",
latexCaption1:"Zeskanuj kod QR lub wprowadź",
latexCaption2:"w celu otwarcia obiektu.",
contributeHeader:"ZOSTAŃ WSPÓŁPRACOWCĄ",
contribute1:"Obejrzyj krótki film o motywacji stojącej za ResearchX3D ...",
contribute2:"... lub zobacz tylko 4-minutowe wprowadzenie do ResearchX3D.",
contribute3:"ResearchX3D tworzy modele 3D z Twoich zdjęć ...",
contribute4:"... ale możesz także przesłać już utworzone obiekty 3D, na przykład z oprogramowania CAD.",
contribute5:"Każdy przedmiot ma do opowiedzenia wiele historii. Tworząc różne typy historii, możesz:",
contribute6:"Wyjaśnij funkcję i projekt; lub",
contribute7:"Sprawdź wiedzę za pomocą quizu; lub",
contribute8:"Dziel się umiejętnościami i procedurami.",
contribute9:"Oto, jak edytor ResearchX3D pomaga w tworzeniu historii.",
clickvideo:"Kliknij, aby zobaczyć wideo.",
clickexample:"Kliknij, aby zobaczyć przykład.",
openstory:"Otwórz tę historię",
allsbj:"wszystkie obszary tematyczne",
showall:"Pokaż wszystko",
graphic:"graficzny",
figclick:"Znajdź historie i adnotacje dotyczące tego obiekt",
openar:"otwarte w rzeczywistości rozszerzonej",
meniagora:"Dyskusje społecznościowe - Agora",
r3dsummary:"<b> Co to jest ResearchX3D? </b> Otwarta platforma społecznościowa do dzielenia się dziedzictwem naukowym w celu odblokowania twórczej wartości na przyszłość.",
agoraad:"<b> Zaproponuj i przedyskutuj </b> pomysły dotyczące projektu ResearchX3D i uzyskaj pomoc na naszej Agorze <img class = 'link' src = '/link.png'> do dyskusji społeczności."
};
