const lang_cy ={close:"Caewch",
loadingmodel:"Model llwytho",
menistartpage:"Tudalen hafan",
menifind:"Dewch o hyd i wrthrychau, straeon a chwestiynau",
meniadd:"Ychwanegu neu olygu stori wrthrych",
meniask:"Gofynnwch gwestiwn ar wrthrych",
meniupload:"Llwythwch i fyny luniau gwrthrych ar gyfer model 3D",
menishare:"Rhannwch wrthrych neu stori",
meniar:"Realiti estynedig ...",
meniaron:"Trowch ymlaen modd AR",
menimarker:"Argraffu marcwyr AR",
menisupport:"Cyswllt a chefnogaeth",
meniabout:"Ynglŷn ag ResearchX3D",
menilogin:"Mewngofnodi",
menilogout:"Allgofnodi",
headfind:"Dewch o hyd i",
headfindt:"Chwilio am gyfarpar arbrofol",
headcontribute:"Cyfrannu",
headcontributet:"Helpwch ni i dyfu casgliad o wrthrychau!",
headaron:"AR ON",
headaront:"Cliciwch i droi Realiti Estynedig ymlaen",
headaroff:"AR ODDI",
headarofft:"Cliciwch i ddiffodd AR",
meni0_0:"AR GYFER MYFYRWYR",
meni0_1:"Dewch o hyd i. Popeth o arbrofion hanesyddol, i sgriwiau addasu cain.",
meni0_2:"Cael eich ysbrydoli. Ehangwch eich gofod creadigol eich hun trwy feddwl am wahanol bosibiliadau dylunio.",
meni1_0:"AR GYFER ADDYSGWYR",
meni1_1:"Defnyddiwch. Sioe mewn cyflwyniadau a chyrsiau.",
meni1_2:"Creu. Anodi gwrthrychau yn ôl eich disgrifiad eich hun, a rhannu eich stori amdanynt.",
meni2_0:"AR GYFER YMCHWILWYR",
meni2_1:"Cyfrannu. Mae'n cymryd un egwyl goffi i rannu'r cyfarpar hwnnw rydych chi'n mynd heibio iddo bob dydd gyda byd cyfan.",
meni2_2:"Archwilio. Trac datblygiad syniadau dylunio.",
aboutheader:"Ynglŷn â'r ResearchX3D.com",
aboutteam:"Tîm",
aboutcontact:"Contant",
about0:"Gadewch i ni rannu treftadaeth wyddonol i ddatgloi gwerth creadigol ar gyfer y dyfodol! Mae cyfarpar arbrofol yn elfen allweddol mewn ymchwil wyddonol. Mae arbrofion hanesyddol a dyluniadau modern yn dreftadaeth werthfawr. Ar ôl rhannu'r gwrthrychau hyn, dônt yn adnodd defnyddiol, gan ysgogi creadigrwydd pobl ledled y byd. Ac yn awr mae'n bosib rhannu appparatus arbrofol yn ystod yr egwyl coffi!",
about1:"Beth mae ResearchX3D.com yn ei wneud?",
about2:"Yn seiliedig ar <b> ffotograffau wedi'u llwytho i fyny gan ddefnyddwyr o offer gwyddonol o'u labordai, coridorau prifysgol, a silffoedd swyddfa ...",
about3:"... rydym <b> yn creu modelau 3D </b> y gall unrhyw un yn eu porwr gwe eu harchwilio.",
about4:"Yna mae ResearchX3D.com yn caniatáu i un wella effaith treftadaeth ac yn cronni gwybodaeth am gyfarpar:",
about5:"Mae'n hawdd gwneud <b> labelu 3D </b> o wrthrychau gyda marcwyr a saethau mewn gofod 3D trwy olygydd ar-lein. Gellir cyd-fynd ag anodiadau â <b> disgrifiadau testunol a sain </b>;",
about6:"Mae grwpiau o labeli yn gwneud straeon am y gwrthrychau. Gall defnyddwyr <b> ddod o hyd i straeon yn seiliedig ar lefel eu gwybodaeth </b>. Ymdrinnir â defnyddwyr ar draws y sbectrwm: o addysgu ysgolion cynradd ac ysgol uwchradd, trwy ddisgrifiadau manwl ar lefel prifysgol, i drafodaethau uwch ar ddylunio appartws ar gyfer lefel PhD / ymchwil;",
about7:"Gall pawb ofyn cwestiwn. Mae <b> cwestiwn ac ateb </b> yn defnyddio labeli 3D ar gyfer disgrifiadau <b> \"pwynt-a-dweud\" </b>. Mae'r atebion gorau yn cael eu huwchraddio gan y defnyddwyr;",
about8:"Gellir gweld gwrthrychau mewn <b> realiti estynedig </b>, sy'n caniatáu i bawb weld cyfarpar arbrofol ar eu desg;",
about9:"Mae'r holl ymarferoldeb yn cael ei ddwyn trwy'r rhyngwyneb gwe (dim gosodiad, platfform yn annibynnol), gan ganiatáu <b> rhannu hawdd </b> o wrthrychau a straeon trwy anfon dolenni at gydweithwyr a ffrindiau.",
about10:"Nod platfform ResearchX3D.com yw",
about12:"Ffisegwyr, cymrodyr ôl-ddoethurol Marie Curie ar hyn o bryd yn <a href=\"https://www.institutoptique.fr/\"> Institute d'Optique, Palaiseau, Ffrainc </a>.",
about13:"Cysylltwch â ni yn <a href='mailto:contact@researchx3d.com?subject=Feedback'> contact@researchx3d.com </a>.",
aboutli0:"Cadw modelau gwrthrychau o dreftadaeth wyddonol a thechnegol;",
aboutli1:"Cofnodi disgrifiadau dylunio gan ymchwilwyr i ddiogelu syniadau a thriciau dylunio ar gyfer y dyfodol;",
aboutli2:"Cyflwyno treftadaeth mewn ffordd sy'n ysbrydoli ac yn ehangu gofod creadigol mewn cynulleidfaoedd ar draws y sbectra, o addysgu i lefel ymchwil; a",
aboutli3:"Democratiaethwch fynediad i ddylunio cyfarpar arbrofol, trwy fynd â rhywbeth a oedd yn hygyrch o'r blaen i ddim ond ychydig o rai lwcus a'i rannu â'r byd i gyd.",
findobject:"Chwilio am wrthrych ...",
findstory:"... ac yna dewis stori / anodiad",
findquestion:"... neu weld cwestiynau ac atebion",
filtersubject:"Hidlo yn ôl maes pwnc:",
filterknowledgelevel:"Hidlo yn ôl lefel gwybodaeth:",
shareqr:"Rhannwch offer a stori arbrofol gyda dolen uniongyrchol neu god QR",
click2copy:"cliciwch i gopïo'r ddolen",
saveqr:"Cadw delwedd cod QR",
askquestion:"Gofynnwch gwestiwn",
share:"rhannu",
addmodifystory:"Ychwanegwch / addaswch eich stori",
depositedby:"Adneuwyd gan",
logoutsuccess:"Rydych chi wedi allgofnodi'n llwyddiannus!",
objectannotation:"Anodi gwrthrych:",
objectannotationt:"cliciwch i ddewis anodi gwahanol",
by:"gan",
location:"Lleoliad",
details:"Manylion",
tags:"Tagiau",
forthisobject:"ar gyfer y gwrthrych hwn",
object:"gwrthrych",
previousm:"Adran flaenorol",
nextm:"Adran nesaf",
or:"neu",
moto:"Rhannu treftadaeth wyddonol i ddatgloi gwerth creadigol ar gyfer y dyfodol.",
pleaselogin:"I symud ymlaen, mewngofnodwch",
enteremail:"Rhowch e-bost",
enterpassword:"Rhowch Gyfrinair",
login:"Mewngofnodi",
forgotpassword:"Wedi anghofio cyfrinair?",
cancel:"Canslo",
newuser:"Defnyddiwr newydd?",
loginnote1:"I ychwanegu gwrthrychau, anodiadau a gofyn ac ymateb i gwestiynau mae angen i chi fewngofnodi.",
loginnote2:"I arbed newidiadau mae angen i chi gadarnhau pwy ydych chi yn gyntaf ac yna pwyswch 'Save'.",
add:"Ychwanegu",
remove:"tynnu",
finally:"O'r diwedd",
annotation:"segment stori",
savestory:"arbed stori",
level1:"ysgol Gynradd",
level2:"ysgol Uwchradd",
level3:"prifysgol (israddedig)",
level4:"PhD / ymchwil",
addmarker:"Ychwanegu marciwr",
addarrow:"ychwanegu saeth",
textual:"testunol",
audio:"sain",
addexp:"Ychwanegu",
explanation:"disgrifiad ar gyfer yr anodiad hwn",
marker:"marciwr",
arrow:"saeth",
at:"yn",
angle:"ongl",
arintro:"Rhowch y marciwr <a href=\"/print_marker.pdf\"><img alt = \"R3D\" src = \"\\ar_marker_small.png\" align = \"middle\" si></a> yng ngolwg y camera. <br/> I lywio'r stori, cliciwch ar saethau chwith a dde.",
noexistingaudio:"Dim disgrifiadau sain yn bodoli.",
newupload:"Llwythiad newydd",
newrecording:"Recordiad newydd",
recordsound:"Dechreuwch recordio",
stopbutton:"Stopiwch recordio",
storytitle:"Teitl y stori",
storydesc:"Crynodeb byr o'r stori wrthrych hon ...",
adddesc:"Ychwanegwch ddisgrifiad ar gyfer yr anodiad hwn ...",
arrowadjust:"Addasu safle a chyfeiriadedd saeth, ac yna",
markeradjust:"Addasu safle marciwr ac yna",
savemarker:"arbed marciwr",
savearrow:"arbed saeth",
audiodesc:"Disgrifiad sain:",
clicktochangelan:"Cliciwch i newid iaith",
getarmarkers:"cael marcwyr realiti estynedig",
contributeh2:"Cyfrannu cyfarpar ... mae'n cymryd un egwyl goffi!",
contributeh3_1:"Sut mae'n gweithio?",
contributeh3_2:"Yn barod? Dechreuwch yma ...",
contributeli1:"<b> Rydych chi </b> yn uwchlwytho ~ 30 llun o'r cyfarpar arbrofol rydych chi'n ei ddogfennu. Ceisiwch dynnu lluniau fel bod pob pwynt ar wrthrych i'w weld ar 3-6 ffotograff o wahanol onglau. Mae mwy o luniau yn well na llai o luniau!",
contributeli2:"<b> Rydym yn adeiladu model 3D o'ch lluniau </b>, gan ddefnyddio meddalwedd ffotogrametreg, a'i roi ar-lein ar yr ResearchX3D",
contributeli3:"Gall <b> Pawb </b> archwilio, anodi, gofyn cwestiynau a rhannu model 3D wedi'i ailadeiladu unwaith y bydd ar-lein. Byddwch chi fel perchennog yn derbyn gwahoddiad cyntaf i ychwanegu anodiad a stori, a fydd yn cael ei amlygu fel anodiad gwreiddiol.",
contributep1:"Dyna i gyd, mae'r dreftadaeth ymchwil ar gael ledled y byd, ar gyfer myfyrwyr eraill, addysgwyr ac ymchwilwyr.",
contributep2:"Ar hyn o bryd rydym yn derbyn cyfraniadau yn unig gan ddefnyddwyr sydd ag e-byst academaidd. Rhag ofn nad oes gennych e-bost academaidd ond yr hoffech gyfrannu, os gwelwch yn dda <input type = \"button\" onclick = \"openBoard ('aboutProject');\" value = \"cysylltwch â ni\" />.",
contributestart:"Dechreuwch uwchlwytho lluniau gwrthrych",
newuserh3:"Cofrestriad defnyddiwr newydd",
newuseri1:"Enw",
newuseri1l:" Bydd eich enw a'ch cyfenw yn ymddangos wrth ymyl gwrthrychau rydych chi'n eu huwchlwytho / eu hanodi.",
newuseri2:"Cyfenw",
newuseri3:"Sefydliad a gwlad",
newuseri3l:" Eich cysylltiad a'ch gwlad lleoliad.",
newuseri4:"e-bost",
newuseri4l:" Sylwch: dim ond e-byst academaidd sy'n cael eu derbyn. Byddwch yn derbyn dolen gadarnhau.",
newuseri5:"Rhowch gyfrinair",
newuseri5l:" Lleiafswm o 8 nod.",
newuseri6:"Ailadrodd cyfrinair",
newuseri6l:" Dim ond i wirio nad oes typos.",
newusersubmit:"Cofrestrwch ddefnyddiwr newydd",
uploadedobjects:"Gwrthrychau sydd wedi'u llwytho i fyny eisoes:",
nameobject:"Enwch eich gwrthrych newydd",
enterobjectname:"rhowch enw gwrthrych newydd",
and:"a",
cratephotospace:"creu lle ar gyfer ffotograffau",
photolisting:"Rhestr o ffotograffau o",
nophotolist:"Nid ydych wedi uwchlwytho lluniau ar gyfer unrhyw wrthrych eto. Llwythwch ffotograffau gwrthrych isod.",
uploadnewphotos:"Llwythwch ffeiliau newydd i fyny",
startupload:"Dechreuwch uwchlwytho",
metadataobject:"Metadata ar wrthrych y tynnwyd llun ohono",
objtitle:"Teitl y gwrthrych",
objtitlel:"Teitl y gwrthrych",
objdetails:"Manylion gwrthrych",
objdetailsl:"disgrifiad gwrthrych byr",
objlocation:"Lleoliad gwreiddiol a phresennol y gwrthrych",
objyear:"Blwyddyn pan wnaed gwrthrych (amcangyfrif)",
objtags:"Tagiau gwrthrych",
objsubmit:"Cyflwyno llun ar gyfer ailadeiladu gwrthrychau 3D",
newobjectspaceerror:"Roedd gwall wrth greu eich gofod gwrthrych:",
newobjectspacesuccess:"Wedi creu lle yn llwyddiannus ar gyfer ffotograffau o wrthrych newydd.",
objsubmerr1:"GWALL: Mae angen ichi ychwanegu rhai <b> tagiau Gwrthrych </b> cyn eu cyflwyno!",
objsubmerr2:"GWALL: Rhaid i enw gwrthrych fod â hyd o leiaf 3 nod",
objsubmerr3:"GWALL: Rhowch o leiaf 10 nod ar gyfer disgrifiad o'r gwrthrych.",
objsubmerr4:"GWALL: Rhowch leoliad y gwrthrych (hanesyddol, presennol neu gwmni y mae ar gael ohono).",
objsubmerr5:"GWALL: Rhowch flwyddyn creu gwrthrychau (amcangyfrif).",
delete:"dileu",
question:"Cwestiwn",
answers:"Atebion",
addeditanswer:"Ychwanegwch neu Golygwch eich ateb",
clickdownvotel:"cliciwch i ostwng cwestiwn neu ateb",
clickupvotel:"cliciwch i uwchraddio cwestiwn neu ateb",
yourquestion:"Eich cwestiwn:",
questiondesc:"Ychwanegwch anodi ar wrthrych a disgrifiwch fanylion testunol y cwestiwn.",
submitquestion:"Cyflwyno cwestiwn",
tooltipmainm:"Cliciwch i agor y brif ddewislen",
meniobject:"Gwrthrych",
questiontitle:"Cwestiwn titl",
aboutfunding:"Cyllid",
about15:"Prosiect wedi'i gefnogi gan Wyddoniaeth a Chymdeithas La Diagonale Paris-Saclay.",
size:"maint",
color:"lliw",
red:"Coch",
green:"gwyrdd",
blue:"glas",
orange:"oren",
magenta:"magenta",
selectlicense:"Dewiswch drwydded ar gyfer ffeiliau a uwchlwythwyd (bydd y model wedi'i ailadeiladu yn cael ei ryddhau o dan yr un drwydded)",
read:"darllen",
licensetext:"trwydded",
translated:"Cyfieithwyd",
transsee:"gweler cyfieithu yn",
transsource:"Testun gwreiddiol",
transseesource:"gweler y gwreiddiol yn",
transimprove:"gwella cyfieithu",
"fr":"Ffrangeg",
"en":"Saesneg",
"es":"Sbaeneg",
"pt":"Portugese",
"de":"Almaeneg",
"zh":"Tseiniaidd",
"ru":"Rwseg",
"ar":"Arabeg",
"sv":"Sweden",
"nl":"Iseldireg",
"it":"Eidaleg",
"ja":"Japaneaidd",
"sr":"Serbeg",
"cs":"Tsiec",
"da":"Daneg",
"sw":"Swahili",
"hi":"Hindi",
"tr":"Twrceg",
"vi":"Fietnam",
"th":"Thai",
"ko":"Corea",
"fa":"Farsi",
"id":"Indonesia",
"cy":"Cymraeg",
"el":"Groeg",
"ro":"Rwmaneg",
"hu":"Hwngari",
"pl":"Pwyleg",
transimprovetitle:"Gwella cyfieithu",
transnote:"Mae cyfieithu yn ymuno ag ymdrech cyfieithu peirianyddol ac adborth a gyfrannwyd gan bobl. Diolch am gymryd amser i gyfrannu.",
transorigin:"Gwreiddiol yn",
transsuggest:"Cyfieithiad yn",
transsubmit:"Cyflwyno cyfieithu",
press:"Cyffwrdd",
forillustration:"er enghraifft",
storylang:"Ysgrifennwyd mewn iaith:",
footer0:"Ynglŷn ag ResearchX3D",
footer1:"Chwilio gwrthrychau, straeon a chwestiynau",
footer2:"Gofynnwch gwestiwn ar wrthrych",
footer3:"Realiti estynedig",
footer4:"Cyflwyno gwrthrych",
footer5:"Cyflwyno stori",
footer_title1:"CYSYLLTIADAU CYFLYM",
footer_title2:"CYSYLLTIADAU CYMDEITHASOL",
navigation:"Llywio",
rotation:"i gylchdroi",
move:"symud, neu",
zoom:"chwyddo'r gwrthrych",
clickForStory:"Cliciwch yma i weld stori'r gwrthrych.",
latexAdd:"neu ychwanegu at ddogfen LaTeX",
latexPDF:"lawrlwythwch ddelwedd PDF yma",
latexCode:"ac ychwanegu cod isod.",
latexCaption1:"Sganiwch god QR neu nodwch",
latexCaption2:"er mwyn agor gwrthrych.",
contributeHeader:"OHERWYDD CYFRANOGWR",
contribute1:"Gwyliwch fideo byr am gymhelliant y tu ôl i ResearchX3D ...",
contribute2:"... neu gwelwch gyflwyniad ResearchX3D 4 munud yn unig.",
contribute3:"Mae ResearchX3D yn creu modelau 3D o'ch ffotograffau ...",
contribute4:"... ond gallwch hefyd uwchlwytho gwrthrychau 3D sydd eisoes wedi'u creu, er enghraifft o feddalwedd CAD.",
contribute5:"Mae gan bob gwrthrych lawer o straeon i'w hadrodd. Trwy greu gwahanol fathau o straeon gallwch:",
contribute6:"Esboniwch swyddogaeth a dyluniad; neu",
contribute7:"Profwch wybodaeth gyda chwis; neu",
contribute8:"Rhannu sgiliau a gweithdrefnau.",
contribute9:"Dyma sut mae golygydd ResearchX3D yn eich helpu chi i greu stori.",
clickvideo:"Cliciwch yma i weld y fideo.",
clickexample:"Cliciwch yma i weld enghraifft",
openstory:"Agorwch y stori hon",
allsbj:"pob maes pwnc",
showall:"dangos y cyfa",
graphic:"graffi",
figclick:"Dewch o hyd i straeon ac anodiadau am y gwrthrych hwn",
openar:"ar agor yn Augmented Reality",
meniagora:"Trafodaethau cymunedol - Agora",
r3dsummary:"<b> Beth yw ResearchX3D? </b> Llwyfan cymunedol agored ar gyfer rhannu treftadaeth wyddonol i ddatgloi gwerth creadigol ar gyfer y dyfodol.",
agoraad:"<b> Awgrymu a thrafod </b> syniadau am brosiect ResearchX3D, a chael help ar ein Agora <img class = 'link' src = '/link.png'> ar gyfer Trafodaethau Cymunedol."
};
