const lang_cs ={close:"Zavřít",
loadingmodel:"Načítání modelu",
menistartpage:"Domovská stránka",
menifind:"Hledejte objekty, příběhy, dotazy",
meniadd:"Přidejte a upravte příběh k objektu",
meniask:"Zeptejte se na objekt",
meniupload:"Nahrajte fotografie objektu pro 3D model",
menishare:"Sdílejte objekt nebo příběh",
meniar:"Rozšířená realita ...",
meniaron:"Zapněte režim AR",
menimarker:"Tisk AR značek",
menisupport:"Kontaktujte podporu",
meniabout:"O ResearchX3D",
menilogin:"Přihlásit se",
menilogout:"Odhlásit se",
headfind:"Hledat",
headfindt:"Hledání experimentálních přístrojů",
headcontribute:"Přidat",
headcontributet:"Pomozte nám rozšířit sbírku předmětů!",
headaron:"AR ON",
headaront:"Klepnutím zapnete rozšířenou realitu",
headaroff:"AR OFF",
headarofft:"Klepnutím vypnete AR",
meni0_0:"PRO STUDENTY",
meni0_1:"Najděte. Vše od historických experimentů až po jemné seřizovací šrouby.",
meni0_2:"Inspirujte se. Rozšiřte svůj vlastní kreativní prostor. Přemýšlejte o různých možnostech designu.",
meni1_0:"PRO PEDAGOGY",
meni1_1:"Používejte. Zobrazte objekty v prezentacích a poznámkách.",
meni1_2:"Tvořte. Přidejte k objektům vlastní popisky a příběhy.",
meni2_0:"PRO VĚDCE",
meni2_1:"Přidejte přístroj. Během jediné pauzy na kávu se můžete podělit s celým světem o ten přístroj okolo kterého každý den procházíte.",
meni2_2:"Prozkoumejte. Sledujte vývoj nápadů na design.",
aboutheader:"O ResearchX3D.com",
aboutteam:"Kontakt a tým projektu",
aboutcontact:"Obsah",
about0:"Podělme se o vědecké dědictví a uvolníme kreativní hodnotu pro budoucnost! Experimentální aparát je klíčovým prvkem vědeckého výzkumu. Historické experimenty i moderní designy jsou cenným dědictvím. Jakmile jsou tyto objekty sdíleny, stávají se užitečným zdrojem stimulujícím tvořivost lidí po celém světě. A nyní je možné během přestávky na kávu sdílet experimentální přístroje!",
about1:"Co ResearchX3D.com dělá?",
about2:"Na základě <b> uživatelem nahraných fotografií </b> vědeckých přístrojů z jejich laboratoří, univerzitních chodeb a kancelářských polic ...",
about3:"... <b>vytváříme 3D modely</b>, které si ve webovém prohlížeči může prohlížet kdokoliv",
about4:"ResearchX3D.com tak umožňuje lidem posílit význam dědictví shromažďováním znalostí o přístrojích:",
about5:"<b> 3D označování </b> objektů pomocí značek a šipek ve 3D prostoru lze snadno provést pomocí online editoru. Anotace mohou být doplněny <b> textovými a zvukovými popisy </b>;",
about6:"Skupiny štítků vytváří příběhy o objektech. Jednotlivé příběhy jsou rozděleny na <b>základě úrovně znalostí</b> a umožňují tak uživatelům vyhledávat informace dle jejich náročnosti.  Úrovně pokrývají celé uživatelské spektrum: od základní a středoškolské výuky, přes  detailní popisy na univerzitní úrovni, až po odborné diskuze na velmi pokročilé vědecké úrovni. ResearchX3D a vybrané příběhy jsou dostupné v 25 jazycích.",
about7:"Kdokoliv může pokládat otázky. <b>Otázky a odpovědi</b> jsou speciálně označeny 3D štítky pro <b>popisy 'point-and-tell'</b>. Uživatelé mohou dát hlas nejlepším odpovědím.",
about8:"Objekty si lze zobrazit v <b>rozšířené realitě</b>, což umožní komukoliv prohlédnout si experimntální přístroj přímo na  jeho stole.;",
about9:"Veškerá funkčnost je zajišťována prostřednictvím webového rozhraní (bez instalace, nezávisle na platformě), což umožňuje <b>snadné sdílení</b> objektů a příběhů zasláním odkazů kolegům a přátelům.",
about10:"Cílem platformy ResearchX3D.com je",
about12:"Fyzici, v současné době postdoktorandi Marie Curie na <a href=\"https://www.institutoptique.fr/\"> Institut d'Optique, Palaiseau, Francie </a>.",
about13:"Můžete nás kontaktovat na <a href='mailto:contact@researchx3d.com?subject=Feedback'> contact@researchx3d.com </a>.",
aboutli0:"Vytvořit a uchovat modely objektů vědeckého a technického dědictví;",
aboutli1:"Zaznamenat a cenné poznámky výzkumnků o designech objektů a zachovat je pro případné budoucí využití;",
aboutli2:"Prezentovat dědictví způsobem, který inspiruje a rozšiřuje tvůrčí prostor v publiku napříč spektry, od výuky po výzkumnou úroveň; a",
aboutli3:"Demokratizujte přístup k návrhu experimentálních přístrojů tím, že vezmete něco, co bylo dříve přístupné pouze několika málo šťastným, a sdílíte jej po celém světě.",
findobject:"Vyhledat objekt ...",
findstory:"... a poté zvolte příběh / anotaci",
findquestion:"... nebo se podívejte na otázky a odpovědi",
filtersubject:"Filtrovat podle oblasti předmětu:",
filterknowledgelevel:"Filtrovat podle úrovně znalostí:",
shareqr:"Sdílejte experimentální aparát a příběh s přímým odkazem nebo QR kódem",
click2copy:"kliknutím zkopírujte odkaz",
saveqr:"Uložte obrázek QR kódu",
askquestion:"Zeptat se na otázku",
share:"podíl",
addmodifystory:"Přidejte / upravte svůj příběh",
depositedby:"Uloženo",
logoutsuccess:"Byl jste úspěšně odhlášen!",
objectannotation:"Anotace objektu:",
objectannotationt:"Kliknutím vyberte jinou anotaci",
by:"podle",
location:"Umístění",
details:"Podrobnosti",
tags:"Značky",
forthisobject:"pro tento objekt",
object:"objekt",
previousm:"Předchozí část",
nextm:"Další část",
or:"nebo",
moto:"Sdílení vědeckého dědictví pro uvolnění tvůrčí hodnoty pro budoucnost.",
pleaselogin:"Chcete-li pokračovat, přihlaste se",
enteremail:"Zadejte email",
enterpassword:"Zadejte heslo",
login:"Přihlásit se",
forgotpassword:"Zapomenuté heslo?",
cancel:"Zrušit",
newuser:"Nový uživatel?",
loginnote1:"Chcete-li přidat objekty, anotace a zeptat se a odpovídat na otázky, které potřebujete k přihlášení.",
loginnote2:"Chcete-li uložit změny, musíte nejprve potvrdit svou totožnost a poté stiskněte tlačítko „Uložit“.",
add:"Přidat",
remove:"odstranit",
finally:"Konečně",
annotation:"segment příběhu",
savestory:"zachránit příběh",
level1:"základní škola",
level2:"střední škola",
level3:"univerzita (vysokoškolský)",
level4:"PhD / výzkum",
addmarker:"Přidat značku",
addarrow:"přidat šipku",
textual:"textový",
audio:"zvukový",
addexp:"Přidat",
explanation:"popis této anotace",
marker:"značka",
arrow:"Šíp",
at:"na",
angle:"úhel",
arintro:"Do zobrazení kamery vložte značku <a href=\"/print_marker.pdf\"><img src = \"\\ar_marker_small.png\" align = \"middle\" si></a>. <br/> Chcete-li procházet příběh, použijte šipky doleva a doprava.",
noexistingaudio:"Žádné existující zvukové popisy.",
newupload:"Nové nahrávání",
newrecording:"Nová nahrávka",
recordsound:"Začít nahrávat",
stopbutton:"Zastavte nahrávání",
storytitle:"Název příběhu",
storydesc:"Stručné shrnutí tohoto příběhu o objektu ...",
adddesc:"Přidat popis této anotace ...",
arrowadjust:"Upravte polohu a orientaci šipky a poté",
markeradjust:"Upravte polohu značky a poté",
savemarker:"uložit značku",
savearrow:"uložit šipku",
audiodesc:"Zvukový popis:",
clicktochangelan:"Klepnutím změníte jazyk",
getarmarkers:"získejte značky rozšířené reality",
contributeh2:"Přispěj aparát ... to trvá jednu přestávku na kávu!",
contributeh3_1:"Jak to funguje?",
contributeh3_2:"Jste připraveni? Začněte zde ...",
contributeli1:"<b>Vi</b> nahrajete cca 30 fotek experimentálního přístroje, který dokumentujete. Pokuste se každý bod na objektu zachytit alespoň 3-6 fotografiemi z různých úhlů. Je lepší použít více fotografií než méně.",
contributeli2:"<b>My</b> sestavíme 3D model z vašich fotografií pomocí fotogramatického softwaru a nahrajeme na ResearchX3D.",
contributeli3:"<b>Kdokoliv</b> může nahraný 3D model prozkoumávat, komentovat, sdílet a klást k němu otázky. Jako vlastník obdržíte pozvání k přidání první anotace k příběhu, která bude zvýrazněna jako původní.",
contributep1:"To je vše, výzkumné dědictví je celosvětově dostupné pro ostatní studenty, pedagogy a výzkumné pracovníky.",
contributep2:"V současné době přijímáme příspěvky pouze od uživatelů s akademickými e-maily. V případě, že nemáte akademický e-mail, ale chtěli byste přispět, prosím, <input type=\"button\" onclick=\"openBoard('aboutProject');\" value=\"kontaktujte nás\" />.",
contributestart:"Zahájit nahrávání fotografie objektu",
newuserh3:"Registrace nového uživatele",
newuseri1:"název",
newuseri1l:" Vaše jméno a příjmení se objeví vedle objektů, které nahrajete / přidáte.",
newuseri2:"Příjmení",
newuseri3:"Instituce a země",
newuseri3l:" Vaše přidružení a země, ve které se nacházíte.",
newuseri4:"e-mailem",
newuseri4l:" Poznámka: jsou přijímány pouze akademické e-maily. Obdržíte potvrzovací odkaz.",
newuseri5:"Zadejte heslo",
newuseri5l:" Minimálně 8 znaků.",
newuseri6:"Zopakovat heslo",
newuseri6l:" Jen zkontrolovat, zda nejsou překlepy.",
newusersubmit:"Zaregistrujte nového uživatele",
uploadedobjects:"Existující nahrané objekty:",
nameobject:"Název nového objektu",
enterobjectname:"zadejte nový název objektu",
and:"a",
cratephotospace:"vytvořit prostor pro fotografie",
photolisting:"Výpis fotografií",
nophotolist:"Zatím jste nenahráli fotografie pro žádný objekt. Vložte prosím fotografie objektů níže.",
uploadnewphotos:"Nahrajte nové soubory",
startupload:"Zahajte nahrávání",
metadataobject:"Metadata na fotografovaném objektu",
objtitle:"Název objektu",
objtitlel:"Název objektu",
objdetails:"Detaily objektu",
objdetailsl:"krátký popis objektu",
objlocation:"Původní a současné umístění objektu",
objyear:"Rok výroby objektu (odhad)",
objtags:"Značky objektů",
objsubmit:"Odeslat fotografii pro rekonstrukci 3D objektu",
newobjectspaceerror:"Při vytváření prostoru objektů došlo k chybě:",
newobjectspacesuccess:"Úspěšně vytvořený prostor pro fotografie nového objektu.",
objsubmerr1:"CHYBA: Před odesláním musíte přidat nějaké <b> tagy objektů </b>!",
objsubmerr2:"CHYBA: Název objektu musí mít délku alespoň 3 znaky",
objsubmerr3:"CHYBA: Zadejte alespoň 10 znaků pro popis objektu.",
objsubmerr4:"CHYBA: Zadejte umístění objektu (historický, současný nebo společnost, ze které je k dispozici).",
objsubmerr5:"CHYBA: Zadejte rok vytvoření objektu (odhad).",
delete:"odstranit",
question:"Otázka",
answers:"Odpovědi",
addeditanswer:"Přidejte nebo upravte svou odpověď",
clickdownvotel:"kliknutím snížíte otázku nebo odpověď",
clickupvotel:"kliknutím vyvoláte dotaz nebo odpověď",
yourquestion:"Vaše otázka:",
questiondesc:"Přidejte anotaci k objektu a textově popište detaily Vaší otázky",
submitquestion:"Odeslat otázku",
tooltipmainm:"Klepnutím otevřete hlavní nabídku",
meniobject:"Objekt",
questiontitle:"Název otázky",
aboutfunding:"Financování",
about15:"Projekt je podporován  La Diagonale Paris-Saclay.",
size:"velikost",
color:"barva",
red:"Červené",
green:"zelený",
blue:"modrý",
orange:"oranžový",
magenta:"purpurová",
selectlicense:"Vyberte licenci pro nahrané soubory (rekonstruovaný model bude vydán pod stejnou licencí)",
read:"číst",
licensetext:"licence",
translated:"Přeloženo",
transsee:"viz překlad v",
transsource:"Původní text",
transseesource:"vidět originál v",
transimprove:"zlepšit překlad",
"fr":"francouzština",
"en":"Angličtina",
"es":"španělština",
"pt":"Portugalština",
"de":"Němec",
"zh":"čínština",
"ru":"ruština",
"ar":"arabština",
"sv":"švédský",
"nl":"holandský",
"it":"italština",
"ja":"japonský",
"sr":"srbština",
"cs":"čeština",
"da":"dánský",
"sw":"Svahilsky",
"hi":"hindština",
"tr":"turečtina",
"vi":"vietnamština",
"th":"Thajské",
"ko":"korejština",
"fa":"Farsi",
"id":"indonéština",
"cy":"velština",
"el":"řecký",
"ro":"rumunština",
"hu":"maďarský",
"pl":"polština",
transimprovetitle:"Vylepšete překlad",
transnote:"Překlad je spojení úsilí strojového překladu a zpětné vazby od člověka. Děkujeme, že jste si udělali čas a přispěli.",
transorigin:"Původní v",
transsuggest:"Překlad v",
transsubmit:"Odeslat translatio",
press:"Dotek",
forillustration:"pro ilustraci",
storylang:"Psané v jazyce:",
footer0:"O společnosti ResearchX3D",
footer1:"Prohledávání objektů, příběhy a dotazy",
footer2:"Zeptejte se na objekt",
footer3:"Rozšířená realita",
footer4:"Odeslat objekt",
footer5:"Odeslat příběh",
footer_title1:"RYCHLÉ ODKAZY",
footer_title2:"SOCIÁLNÍ ODKAZY",
navigation:"Navigace",
rotation:"otočit",
move:"přesunout, nebo",
zoom:"přiblížit objekt",
clickForStory:"Klepnutím sem zobrazíte příběh objektu.",
latexAdd:"nebo přidat do dokumentu LaTeX",
latexPDF:"stáhnout PDF obrázek zde",
latexCode:"a přidejte kód níže.",
latexCaption1:"Naskenujte QR kód nebo zadejte",
latexCaption2:"za účelem otevření objektu.",
contributeHeader:"STAŇTE SE PŘISPĚVATELI",
contribute1:"Podívejte se na krátké video o motivaci k projektu Research X3D ...",
contribute2:"... případně shlédněte 4minutové shrnující video o projektu Research X3D.",
contribute3:"ResearchX3D vytváří 3D modely z vašich fotografií ...",
contribute4:"... ale můžete také nahrát již vytvořené 3D objekty, například z CAD softwaru.",
contribute5:"Každý objekt má mnoho příběhů. Přidáváním různých typů příběhů můžete:",
contribute6:"Vysvětlit funkci a design;",
contribute7:"Otestovat své znalosti pomocí kvízu;",
contribute8:"Sdílet dovednosti a postupy.",
contribute9:"Zde je způsob, jak vám editor ResearchX3D pomůže vytvořit příběh.",
clickvideo:"Kliknutím sem zobrazíte video.",
clickexample:"Kliknutím sem zobrazíte příklad",
openstory:"Otevřete tento příběh",
allsbj:"všechny tematické oblasti",
showall:"ukázat vš",
graphic:"grafický",
figclick:"Najděte příběhy a poznámky o tomto objektu",
openar:"otevřeno v rozšířené realitě",
meniagora:"Komunitní diskuse - Agora",
r3dsummary:"<b> Co je ResearchX3D? </b> Otevřená komunitní platforma pro sdílení vědeckého dědictví, která vám odemkne tvůrčí hodnotu pro budoucnost.",
agoraad:"<b>b>Navrhujte a sdílejte </b> nápady týkající se projektu (name of your project) a získejte pomoc na diskuzním fóru Agora <img class = 'link' src = '/link.png'>."
};
