const lang_id ={close:"Dekat",
loadingmodel:"Memuat model",
menistartpage:"Beranda",
menifind:"Temukan benda, cerita, dan pertanyaan",
meniadd:"Tambah atau edit cerita objek",
meniask:"Ajukan pertanyaan tentang objek",
meniupload:"Unggah foto objek untuk model 3D",
menishare:"Bagikan objek atau cerita",
meniar:"Augmented reality ...",
meniaron:"Aktifkan mode AR",
menimarker:"Cetak penanda AR",
menisupport:"Kontak & dukungan",
meniabout:"Tentang ResearchX3D",
menilogin:"Gabung",
menilogout:"Keluar",
headfind:"Temukan",
headfindt:"Cari peralatan eksperimental",
headcontribute:"Menyumbang",
headcontributet:"Bantu kami menumbuhkan koleksi benda!",
headaron:"AR ON",
headaront:"Klik untuk mengaktifkan Augmented Reality",
headaroff:"MATI",
headarofft:"Klik untuk mematikan AR",
meni0_0:"UNTUK SISWA",
meni0_1:"Temukan. Semuanya dari eksperimen historis, hingga sekrup penyesuaian halus.",
meni0_2:"Terinspirasi. Perluas ruang kreatif Anda sendiri dengan memikirkan kemungkinan desain yang berbeda.",
meni1_0:"UNTUK PENDIDIK",
meni1_1:"Menggunakan. Perlihatkan dalam presentasi dan kursus.",
meni1_2:"Membuat. Beri anotasi objek dengan deskripsi Anda sendiri, dan bagikan kisah Anda tentangnya.",
meni2_0:"UNTUK PENELITI",
meni2_1:"Menyumbang. Perlu satu rehat kopi untuk membagikan peralatan yang Anda lewati setiap hari dengan seluruh dunia.",
meni2_2:"Jelajahi. Lacak pengembangan ide-ide desain.",
aboutheader:"Tentang ResearchX3D.com",
aboutteam:"Tim",
aboutcontact:"Kontan",
about0:"Mari berbagi warisan ilmiah untuk membuka nilai kreatif masa depan! Aparat eksperimental adalah elemen kunci dalam penelitian ilmiah. Eksperimen sejarah dan desain modern merupakan warisan berharga. Begitu benda-benda ini dibagikan, mereka menjadi sumber daya yang berguna, merangsang kreativitas orang di seluruh dunia. Dan sekarang mungkin untuk berbagi peralatan eksperimental selama istirahat kopi!",
about1:"Apa yang dilakukan oleh ResearchX3D.com?",
about2:"Berdasarkan <b> foto yang diunggah pengguna </b> dari peralatan ilmiah dari lab, koridor universitas, dan rak kantor ...",
about3:"... kami <b> membuat model 3D </b> dieksplorasi oleh siapa pun di browser web.",
about4:"ResearchX3D.com kemudian memungkinkan seseorang untuk meningkatkan dampak warisan dan mengumpulkan pengetahuan tentang peralatan:",
about5:"<b> Pelabelan 3D </b> objek dengan spidol dan panah di ruang 3D mudah dilakukan melalui editor online. Anotasi dapat disertai dengan <b> deskripsi teks dan audio </b>;",
about6:"Kelompok label membuat cerita tentang objek. Pengguna dapat <b> menemukan cerita berdasarkan tingkat pengetahuan mereka </b>. Para pengguna di seluruh spektrum dicakup: mulai dari pengajaran sekolah dasar dan sekolah menengah, hingga deskripsi terperinci tingkat universitas, hingga diskusi lanjutan tentang desain appartus untuk tingkat PhD / penelitian;",
about7:"Setiap orang dapat mengajukan pertanyaan. Baik <b> pertanyaan maupun jawaban </b> menggunakan label 3D untuk deskripsi <b> \"point-and-tell\" </b>. Jawaban terbaik diputuskan oleh pengguna;",
about8:"Objek dapat dilihat di <b> augmented reality </b>, memungkinkan semua orang untuk melihat peralatan eksperimental di meja mereka;",
about9:"Semua fungsionalitas dibawa melalui antarmuka web (tanpa instalasi, platform independen), memungkinkan <b> berbagi mudah </b> dengan objek dan cerita dengan mengirimkan tautan ke kolega dan teman.",
about10:"Platform ResearchX3D.com bertujuan untuk",
about12:"Fisikawan, saat ini rekan postdoctoral Marie Curie di <a href=\"https://www.institutoptique.fr/\"> Institute d'Optique, Palaiseau, Prancis </a>.",
about13:"Hubungi kami di <a href='mailto:contact@researchx3d.com?subject=Feedback'> contact@researchx3d.com </a>.",
aboutli0:"Pertahankan model objek warisan ilmiah dan teknis;",
aboutli1:"Rekam deskripsi desain oleh para peneliti untuk melindungi ide dan trik desain untuk masa depan;",
aboutli2:"Sajikan warisan dengan cara yang menginspirasi dan memperluas ruang kreatif di khalayak di seluruh spektrum, dari mengajar hingga tingkat penelitian; dan",
aboutli3:"Mendemokratiskan akses ke desain peralatan eksperimental, dengan mengambil sesuatu yang sebelumnya hanya dapat diakses oleh beberapa yang beruntung dan membagikannya ke seluruh dunia.",
findobject:"Cari objek ...",
findstory:"... dan kemudian pilih cerita / anotasi",
findquestion:"... atau lihat pertanyaan dan jawaban",
filtersubject:"Saring berdasarkan bidang subjek:",
filterknowledgelevel:"Filter menurut tingkat pengetahuan:",
shareqr:"Bagikan peralatan dan cerita eksperimental dengan tautan langsung atau kode QR",
click2copy:"klik untuk menyalin tautan",
saveqr:"Simpan gambar kode QR",
askquestion:"Bertanya",
share:"Bagikan",
addmodifystory:"Tambahkan / modifikasi cerita Anda",
depositedby:"Diendapkan oleh",
logoutsuccess:"Anda telah berhasil keluar!",
objectannotation:"Anotasi objek:",
objectannotationt:"klik untuk memilih anotasi yang berbeda",
by:"oleh",
location:"Lokasi",
details:"Detail",
tags:"Tag",
forthisobject:"untuk objek ini",
object:"obyek",
previousm:"Bagian sebelumnya",
nextm:"Bagian selanjutnya",
or:"atau",
moto:"Berbagi warisan ilmiah untuk membuka nilai kreatif masa depan.",
pleaselogin:"Untuk melanjutkan, silakan login",
enteremail:"Masukan email",
enterpassword:"Masukkan kata kunci",
login:"Gabung",
forgotpassword:"Lupa kata sandi?",
cancel:"Membatalkan",
newuser:"Pengguna baru?",
loginnote1:"Untuk menambahkan objek, anotasi dan tanyakan serta jawab pertanyaan yang perlu Anda masuk.",
loginnote2:"Untuk menyimpan perubahan, Anda perlu mengkonfirmasi identitas Anda terlebih dahulu dan kemudian tekan 'Simpan'.",
add:"Menambahkan",
remove:"menghapus",
finally:"Akhirnya",
annotation:"segmen cerita",
savestory:"simpan cerita",
level1:"sekolah dasar",
level2:"SMA",
level3:"universitas (sarjana)",
level4:"PhD / penelitian",
addmarker:"Tambahkan penanda",
addarrow:"tambahkan panah",
textual:"tekstual",
audio:"audio",
addexp:"Menambahkan",
explanation:"deskripsi untuk anotasi ini",
marker:"penanda",
arrow:"panah",
at:"di",
angle:"sudut",
arintro:"Letakkan penanda <a href=\"/print_marker.pdf\"><img src = \"\\ar_marker_small.png\" align = \"middle\" si></a> di tampilan kamera. <br/> Untuk menavigasi cerita, klik panah kiri dan kanan.",
noexistingaudio:"Tidak ada deskripsi audio yang ada.",
newupload:"Unggahan baru",
newrecording:"Rekaman baru",
recordsound:"Mulai merekam",
stopbutton:"Hentikan rekaman",
storytitle:"Judul cerita",
storydesc:"Ringkasan singkat dari cerita objek ini ...",
adddesc:"Tambahkan deskripsi untuk anotasi ini ...",
arrowadjust:"Sesuaikan posisi panah dan orientasi, lalu",
markeradjust:"Sesuaikan posisi marker lalu",
savemarker:"simpan penanda",
savearrow:"simpan panah",
audiodesc:"Deskripsi audio:",
clicktochangelan:"Klik untuk mengubah bahasa",
getarmarkers:"dapatkan penanda augmented reality",
contributeh2:"Kontribusi aparatur ... diperlukan satu kali rehat kopi!",
contributeh3_1:"Bagaimana itu bekerja?",
contributeh3_2:"Siap? Mulai di sini...",
contributeli1:"<b> Anda </b> mengunggah ~ 30 foto peralatan percobaan yang Anda dokumentasikan. Cobalah mengambil foto sedemikian rupa sehingga setiap titik pada objek terlihat pada 3-6 foto dari sudut yang berbeda. Lebih banyak foto lebih baik daripada lebih sedikit foto!",
contributeli2:"<b> Kami membuat model 3D dari foto Anda </b>, menggunakan perangkat lunak fotogrametri, dan menaruhnya online di ResearchX3D",
contributeli3:"<b> Semua orang </b> dapat menjelajahi, membuat anotasi, mengajukan pertanyaan, dan berbagi model 3D yang direkonstruksi setelah online. Anda sebagai pemilik akan menerima undangan pertama untuk menambahkan anotasi dan cerita, yang akan disorot sebagai anotasi asli.",
contributep1:"Itu saja, warisan penelitian tersedia di seluruh dunia, untuk siswa lain, pendidik, dan peneliti.",
contributep2:"Saat ini kami hanya menerima kontribusi dari pengguna dengan email akademis. Jika Anda tidak memiliki email akademis tetapi ingin berkontribusi silakan <input type = \"button\" onclick = \"openBoard ('aboutProject');\" value = \"hubungi kami\" />.",
contributestart:"Mulai unggah foto objek",
newuserh3:"Pendaftaran pengguna baru",
newuseri1:"Nama",
newuseri1l:" Nama dan nama keluarga Anda akan muncul di sebelah objek yang Anda unggah / anotasi.",
newuseri2:"Nama keluarga",
newuseri3:"Institusi dan negara",
newuseri3l:" Afiliasi Anda dan negara lokasi.",
newuseri4:"surel",
newuseri4l:" Catatan: hanya email akademik yang diterima. Anda akan menerima tautan konfirmasi.",
newuseri5:"Masukkan kata kunci",
newuseri5l:" Minimal 8 karakter.",
newuseri6:"Masukkan kata kunci kembali",
newuseri6l:" Hanya untuk memeriksa tidak ada kesalahan ketik.",
newusersubmit:"Daftarkan pengguna baru",
uploadedobjects:"Objek yang diunggah yang ada:",
nameobject:"Beri nama objek baru Anda",
enterobjectname:"masukkan nama objek baru",
and:"dan",
cratephotospace:"buat ruang untuk foto",
photolisting:"Daftar foto-foto",
nophotolist:"Anda belum mengunggah foto untuk objek apa pun. Unggah foto-foto objek di bawah ini.",
uploadnewphotos:"Unggah file baru",
startupload:"Mulai mengunggah",
metadataobject:"Metadata pada objek yang difoto",
objtitle:"Judul objek",
objtitlel:"Judul objek",
objdetails:"Rincian objek",
objdetailsl:"deskripsi objek pendek",
objlocation:"Lokasi objek asli dan sekarang",
objyear:"Tahun ketika objek dibuat (perkiraan)",
objtags:"Tag objek",
objsubmit:"Kirim foto untuk rekonstruksi objek 3D",
newobjectspaceerror:"Ada kesalahan saat membuat ruang objek Anda:",
newobjectspacesuccess:"Berhasil menciptakan ruang untuk foto-foto objek baru.",
objsubmerr1:"GALAT: Anda perlu menambahkan beberapa <b> Tag objek </b> sebelum dikirim!",
objsubmerr2:"GALAT: Nama objek harus memiliki panjang minimal 3 karakter",
objsubmerr3:"GALAT: Masukkan setidaknya 10 karakter untuk deskripsi objek.",
objsubmerr4:"GALAT: Silakan masukkan lokasi objek (historis, sekarang, atau perusahaan dari mana tersedia).",
objsubmerr5:"GALAT: Silakan masukkan tahun pembuatan objek (diperkirakan).",
delete:"menghapus",
question:"Pertanyaan",
answers:"Jawaban",
addeditanswer:"Tambahkan atau Edit jawaban Anda",
clickdownvotel:"klik untuk membatalkan pertanyaan atau jawaban",
clickupvotel:"klik untuk mengunggah pertanyaan atau jawab",
yourquestion:"Pertanyaanmu:",
questiondesc:"Tambahkan anotasi pada objek dan jelaskan detail pertanyaan yang tekstual.",
submitquestion:"Kirim pertanyaan",
tooltipmainm:"Klik untuk membuka menu utama",
meniobject:"Obyek",
questiontitle:"Judul pertanyaan",
aboutfunding:"Pendanaan",
about15:"Proyek yang didukung oleh Sains dan Masyarakat La Diagonale Paris-Saclay.",
size:"ukuran",
color:"warna",
red:"merah",
green:"hijau",
blue:"biru",
orange:"jeruk",
magenta:"magenta",
selectlicense:"Pilih lisensi untuk file yang diunggah (model yang direkonstruksi akan dirilis di bawah lisensi yang sama)",
read:"Baca",
licensetext:"lisensi",
translated:"Diterjemahkan",
transsee:"lihat terjemahan di",
transsource:"Teks asli",
transseesource:"lihat aslinya",
transimprove:"tingkatkan terjemahan",
"fr":"Perancis",
"en":"Inggris",
"es":"Orang Spanyol",
"pt":"portugese",
"de":"Jerman",
"zh":"Cina",
"ru":"Rusia",
"ar":"Arab",
"sv":"Orang Swedia",
"nl":"Belanda",
"it":"Italia",
"ja":"Jepang",
"sr":"Orang Serbia",
"cs":"Ceko",
"da":"Orang Denmark",
"sw":"swahili",
"hi":"Hindi",
"tr":"Turki",
"vi":"Orang Vietnam",
"th":"Thai",
"ko":"Korea",
"fa":"farsi",
"id":"bahasa Indonesia",
"cy":"welsh",
"el":"Yunani",
"ro":"Rumania",
"hu":"Hongaria",
"pl":"Polandia",
transimprovetitle:"Tingkatkan terjemahan",
transnote:"Terjemahan adalah upaya gabungan dari terjemahan mesin dan umpan balik kontribusi manusia Terima kasih telah meluangkan waktu untuk berkontribusi.",
transorigin:"Asli dalam",
transsuggest:"Terjemahan dalam",
transsubmit:"Kirim terjemahan",
press:"Sentuh",
forillustration:"untuk ilustrasi",
storylang:"Ditulis dalam bahasa:",
footer0:"Tentang ResearchX3D",
footer1:"Cari benda, cerita, dan pertanyaan",
footer2:"Tanyakan pertanyaan pada objek",
footer3:"Augmented reality",
footer4:"Kirim objek",
footer5:"Kirim cerita",
footer_title1:"TAUTAN LANGSUNG",
footer_title2:"TAUTAN SOSIAL",
navigation:"Navigasi",
rotation:"untuk memutar",
move:"bergerak, atau",
zoom:"memperbesar objek",
clickForStory:"Klik di sini untuk melihat cerita objek.",
latexAdd:"atau tambahkan ke dokumen LaTeX",
latexPDF:"unduh gambar PDF di sini",
latexCode:"dan tambahkan kode di bawah ini.",
latexCaption1:"Pindai kode QR atau masukkan",
latexCaption2:"untuk membuka objek.",
contributeHeader:"MENJADI KONTRIBUTOR",
contribute1:"Tonton video singkat tentang motivasi di balik ResearchX3D ...",
contribute2:"... atau lihat saja pengantar ResearchX3D 4 menit.",
contribute3:"ResearchX3D membuat model 3D dari foto Anda ...",
contribute4:"... tetapi Anda juga dapat mengunggah objek 3D yang sudah dibuat, misalnya dari perangkat lunak CAD.",
contribute5:"Setiap objek memiliki banyak cerita untuk diceritakan. Dengan membuat berbagai jenis cerita, Anda dapat:",
contribute6:"Jelaskan fungsi dan desain; atau",
contribute7:"Uji pengetahuan dengan kuis; atau",
contribute8:"Bagikan keterampilan dan prosedur.",
contribute9:"Berikut adalah cara editor ResearchX3D membantu Anda membuat cerita.",
clickvideo:"Klik di sini untuk melihat videonya.",
clickexample:"Klik di sini untuk melihat contohnya",
openstory:"Buka cerita ini",
allsbj:"semua bidang studi",
showall:"tunjukkan semu",
graphic:"grafis",
figclick:"Temukan cerita dan anotasi tentang objek ini",
openar:"buka di Augmented Reality",
meniagora:"Diskusi komunitas - Agora",
r3dsummary:"<b> Apa itu ResearchX3D? </b> Sebuah platform komunitas terbuka untuk berbagi warisan ilmiah guna membuka nilai kreatif untuk masa depan.",
agoraad:"<b> Sarankan dan diskusikan </b> ide-ide tentang proyek ResearchX3D, dan dapatkan bantuan di Agora <img class = 'link' src = '/link.png'> kami untuk Diskusi Komunitas."
};
