const lang_sv ={close:"Stänga",
loadingmodel:"Laddar modell",
menistartpage:"Hemsida",
menifind:"Hitta objekt, berättelser och frågor",
meniadd:"Lägg till eller redigera objekthistoria",
meniask:"Ställ fråga om objekt",
meniupload:"Ladda upp objektfoton för 3D-modell",
menishare:"Dela objekt eller berättelse",
meniar:"Förstärkt verklighet ...",
meniaron:"Slå på AR-läge",
menimarker:"Skriv ut AR-markörer",
menisupport:"Kontakta supporten",
meniabout:"Handla om ResearchX3D",
menilogin:"Logga in",
menilogout:"Logga ut",
headfind:"Hitta",
headfindt:"Sök efter experimentella apparater",
headcontribute:"Bidra",
headcontributet:"Hjälp oss att odla samling av föremål!",
headaron:"AR PÅ",
headaront:"Klicka för att aktivera Augmented Reality",
headaroff:"AR AV",
headarofft:"Klicka för att stänga av AR",
meni0_0:"FÖR STUDENTER",
meni0_1:"Hitta. Allt från historiska experiment till fina justeringsskruvar.",
meni0_2:"Bli inspirerad. Utöka ditt eget kreativa utrymme genom att tänka på olika designmöjligheter.",
meni1_0:"FÖR LÄRARE",
meni1_1:"Använda sig av. Visa i presentationer och kurser.",
meni1_2:"Skapa. Kommentera objekt med din egen beskrivning och dela din berättelse om dem.",
meni2_0:"FÖR FORSKARE",
meni2_1:"Bidra. Det tar en kaffepaus att dela den apparaten du passerar varje dag med en hel värld.",
meni2_2:"Utforska. Spåra utvecklingen av designidéer.",
aboutheader:"Om ResearchX3D.com",
aboutteam:"Team",
aboutcontact:"Contant",
about0:"Låt oss dela vetenskapligt arv för att låsa upp kreativt värde för framtiden! Experimentella apparater är nyckelelement i vetenskaplig forskning. Både historiska experiment och modern design är värdefullt arv. När dessa objekt har delats, blir de användbara resurser och stimulerar kreativiteten hos människor runt om i världen. Och nu är det möjligt att dela experimentell appparatus under kaffepausen!",
about1:"Vad gör ResearchX3D.com?",
about2:"Baserat på <b> användaruppladdade foton </b> av vetenskapliga apparater från sina labb, universitetskorridorer och kontorshyllor ...",
about3:"... vi <b> skapar 3D-modeller </b> som kan utforskas av vem som helst i webbläsaren.",
about4:"ResearchX3D.com tillåter sedan en att förbättra effekterna av arv och samlar kunskap om apparater:",
about5:"<b> 3D-märkning </b> av objekt med markörer och pilar i 3D-utrymme görs enkelt i online redigeraren. Annoteringar kan åtföljas av <b> text- och ljudbeskrivningar </b>;",
about6:"Grupper av etiketter gör historier om föremålen. Användare kan <b> hitta berättelser baserade på deras kunskapsnivå </b>. Användare över hela spektrumet omfattas: från grundskola och gymnasieundervisning, genom detaljerade beskrivningar på universitetsnivå, till avancerade diskussioner om appartusdesign för doktorand / forskningsnivå;",
about7:"Alla kan ställa en fråga. Både <b> frågor och svar </b> använder 3D-etiketter för <b> \"pek-och-berätta\" -beskrivningar </b>. Användarna svarar för de bästa svaren;",
about8:"Objekt kan ses i <b> augmented reality </b>, vilket gör att alla kan se experimentella apparater på sitt skrivbord;",
about9:"All funktionalitet kommer via webbgränssnittet (ingen installation, oberoende plattform), vilket tillåter <b> enkel delning </b> av objekt och berättelser genom att skicka länkar till kollegor och vänner.",
about10:"ResearchX3D.com-plattformen syftar till",
about12:"Fysiker, för närvarande Marie Curie doktorander vid <a href=\"https://www.institutoptique.fr/\"> Institute d'Optique, Palaiseau, Frankrike </a>.",
about13:"Kontakta oss på <a href='mailto:contact@researchx3d.com?subject=Feedback'> contact@researchx3d.com </a>.",
aboutli0:"Bevara objektmodeller av vetenskapligt och tekniskt arv;",
aboutli1:"Spela in designbeskrivningar av forskare för att skydda designidéer och tricks för framtiden;",
aboutli2:"Nuvarande arv på ett sätt som inspirerar och utökar kreativt utrymme inom publiken över spektra, från undervisning till forskningsnivå; och",
aboutli3:"Demokratisera tillgången till design av experimentell apparatur genom att ta något som tidigare varit tillgängligt endast för få lyckliga och dela det med hela världen.",
findobject:"Sök efter objekt ...",
findstory:"... och välj sedan berättelse / kommentar",
findquestion:"... eller se frågor och svar",
filtersubject:"Filtrera efter ämnesområde:",
filterknowledgelevel:"Filtrera efter kunskapsnivå:",
shareqr:"Dela experimentella apparater och berättelser med direktlänk eller QR-kod",
click2copy:"Klicka för att kopiera länken",
saveqr:"Spara QR-kodbild",
askquestion:"Frågar frågan",
share:"dela med sig",
addmodifystory:"Lägg till / ändra din berättelse",
depositedby:"Insatt av",
logoutsuccess:"Du har loggats ut!",
objectannotation:"Objektanteckning:",
objectannotationt:"Klicka för att välja annotering",
by:"förbi",
location:"Plats",
details:"detaljer",
tags:"Tags",
forthisobject:"för detta objekt",
object:"objekt",
previousm:"Föregående avsnitt",
nextm:"Nästa avsnitt",
or:"eller",
moto:"Dela vetenskapligt arv för att låsa upp kreativt värde för framtiden.",
pleaselogin:"För att fortsätta, logga in",
enteremail:"Skriv in e-mail",
enterpassword:"Skriv in lösenord",
login:"Logga in",
forgotpassword:"Glömt ditt lösenord?",
cancel:"Avbryt",
newuser:"Ny användare?",
loginnote1:"För att lägga till objekt, kommentarer och ställa och svara på frågor du behöver logga in.",
loginnote2:"För att spara ändringar måste du först bekräfta din identitet och sedan trycka på \"Spara\".",
add:"Lägg till",
remove:"ta bort",
finally:"Till sist",
annotation:"berättelse segment",
savestory:"spara historien",
level1:"grundskola",
level2:"gymnasium",
level3:"universitet (grundutbildning)",
level4:"PhD / forskning",
addmarker:"Lägg till markör",
addarrow:"lägg till pil",
textual:"text-",
audio:"audio",
addexp:"Lägg till",
explanation:"beskrivning för denna kommentar",
marker:"markör",
arrow:"pil",
at:"på",
angle:"vinkel",
arintro:"Sätt markören <a href=\"/print_marker.pdf\"><img src = \"\\ar_marker_small.png\" align = \"middle\" si></a> i kameravyn. <br/> Klicka på pilarna till vänster och höger för att navigera i berättelsen.",
noexistingaudio:"Inga befintliga ljudbeskrivningar.",
newupload:"Ny uppladdning",
newrecording:"Ny inspelning",
recordsound:"Börja filma",
stopbutton:"Sluta inspelningen",
storytitle:"Berättelsetitel",
storydesc:"Kort sammanfattning av den här historien ...",
adddesc:"Lägg till beskrivning för den här kommentaren ...",
arrowadjust:"Justera pilens position och riktning och sedan",
markeradjust:"Justera markörens position och sedan",
savemarker:"spara markör",
savearrow:"spara pilen",
audiodesc:"Ljudbeskrivning:",
clicktochangelan:"Klicka för att ändra språk",
getarmarkers:"få förstärkta verklighetsmarkörer",
contributeh2:"Bidra med apparater ... det tar en kaffepaus!",
contributeh3_1:"Hur det fungerar?",
contributeh3_2:"Redo? Börja här...",
contributeli1:"<b> Du </b> laddar upp ~ 30 foton från den experimentella apparaten du dokumenterar. Försök att ta fotografier så att varje punkt på objekt syns på 3-6 fotografier från olika vinklar. Fler bilder är bättre än mindre foton!",
contributeli2:"<b> Vi bygger 3D-modell från dina foton </b> med fotogrammetri-programvara och lägger den online på ResearchX3D",
contributeli3:"<b> Alla </b> kan utforska, kommentera, ställa frågor och dela rekonstruerad 3D-modell när den är online. Du som ägare kommer att få den första inbjudan att lägga till kommentarer och berättelser, som kommer att markeras som originalanteckning.",
contributep1:"Det är allt, forskningsarvet är tillgängligt över hela världen för andra studenter, lärare och forskare.",
contributep2:"För tillfället accepterar vi bidrag endast från användare med akademiska e-postmeddelanden. Om du inte har akademisk e-post men vill bidra, vänligen <input type=\"button\" onclick=\"openBoard('aboutProject');\" value=\"Kontakta oss\" />.",
contributestart:"Starta uppladdning av objektfoto",
newuserh3:"Ny användarregistrering",
newuseri1:"namn",
newuseri1l:" Ditt namn och efternamn visas bredvid objekt du laddar upp / kommenterar.",
newuseri2:"Efternamn",
newuseri3:"Institution och land",
newuseri3l:" Din anslutning och land där du bor.",
newuseri4:"e-post",
newuseri4l:" Obs: endast academiska e-postmeddelanden accepteras. Du kommer att få en bekräftelselänk.",
newuseri5:"Skriv in lösenord",
newuseri5l:" Minst 8 tecken.",
newuseri6:"repetera lösenord",
newuseri6l:" Bara för att kontrollera att det inte finns några skrivfel.",
newusersubmit:"Registrera en ny användare",
uploadedobjects:"Befintliga uppladdade objekt:",
nameobject:"Namnge ditt nya objekt",
enterobjectname:"ange nytt objektnamn",
and:"och",
cratephotospace:"skapa utrymme för fotografier",
photolisting:"Lista över fotografier av",
nophotolist:"Du har inte laddat upp bilder för något objekt ännu. Ladda upp objektfotografier nedan.",
uploadnewphotos:"Ladda upp nya filer",
startupload:"Börja ladda upp",
metadataobject:"Metadata på det fotograferade objektet",
objtitle:"Objektets titel",
objtitlel:"Objektets titel",
objdetails:"Objektdetaljer",
objdetailsl:"kort objektbeskrivning",
objlocation:"Objektets ursprungliga och nuvarande plats",
objyear:"År då objekt gjordes (uppskattning)",
objtags:"Objekttaggar",
objsubmit:"Skicka foto för rekonstruktion av 3D-objekt",
newobjectspaceerror:"Det gick inte att skapa ditt objektutrymme:",
newobjectspacesuccess:"Skapat utrymme för fotografier av ett nytt objekt.",
objsubmerr1:"FEL: Du måste lägga till några <b> Objekttaggar </b> innan du skickar in det!",
objsubmerr2:"FEL: Objektnamnet måste ha en längd på minst 3 tecken",
objsubmerr3:"FEL: Ange minst 10 tecken för objektbeskrivning.",
objsubmerr4:"FEL: Ange objektets placering (historiskt, nuvarande eller företag från vilket det är tillgängligt).",
objsubmerr5:"FEL: Ange år för objektskapning (uppskattad).",
delete:"radera",
question:"Fråga",
answers:"svar",
addeditanswer:"Lägg till eller redigera ditt svar",
clickdownvotel:"Klicka för att stämma ner frågan eller svaret",
clickupvotel:"klicka för att skriva om frågan eller svaret",
yourquestion:"Din fråga:",
questiondesc:"Lägg till en kommentar på objektet och beskriv textinformation om frågan.",
submitquestion:"Skicka fråga",
tooltipmainm:"Klicka för att öppna huvudmenyn",
meniobject:"Objekt",
questiontitle:"Frågestitel",
aboutfunding:"finansiering",
about15:"Projekt stött av Science and Society of La Diagonale Paris-Saclay.",
size:"storlek",
color:"Färg",
red:"röd",
green:"grön",
blue:"blå",
orange:"orange",
magenta:"magenta",
selectlicense:"Välj licens för uppladdade filer (den rekonstruerade modellen släpps under samma licens)",
read:"läsa",
licensetext:"licens",
translated:"översatt",
transsee:"se översättning i",
transsource:"Original text",
transseesource:"se original i",
transimprove:"förbättra översättningen",
"fr":"franska",
"en":"engelsk",
"es":"spanska",
"pt":"portugese",
"de":"tysk",
"zh":"kinesisk",
"ru":"ryska",
"ar":"arabicum",
"sv":"svenska",
"nl":"dutch",
"it":"italiensk",
"ja":"japansk",
"sr":"serbian",
"cs":"tjeck",
"da":"dansk",
"sw":"swahili",
"hi":"hindi",
"tr":"turkiska",
"vi":"vietnamese",
"th":"thai",
"ko":"koreanska",
"fa":"Persiska",
"id":"indonesiska",
"cy":"welsh",
"el":"grekisk",
"ro":"rumänska",
"hu":"Ungerska",
"pl":"putsa",
transimprovetitle:"Förbättra översättningen",
transnote:"Översättning är en del av maskinöversättningen och feedback från människor. Tack för att du tog dig tid att bidra.",
transorigin:"Original i",
transsuggest:"Översättning i",
transsubmit:"Skicka översättning",
press:"Rör",
forillustration:"för illustration",
storylang:"Skrivet på språk:",
footer0:"Om ResearchX3D",
footer1:"Sök efter objekt, berättelser och frågor",
footer2:"Fråga fråga om objekt",
footer3:"Förstärkt verklighet",
footer4:"Skicka objekt",
footer5:"Skicka in berättelsen",
footer_title1:"SNABBLÄNKAR",
footer_title2:"Sociala länkar",
navigation:"Navigering",
rotation:"att rotera",
move:"flytta, eller",
zoom:"zooma på objektet",
clickForStory:"Klicka här för att se objektets historia.",
latexAdd:"eller lägg till i LaTeX-dokument",
latexPDF:"ladda ner PDF-bild här",
latexCode:"och lägg till kod nedan.",
latexCaption1:"Skanna QR-kod eller ange",
latexCaption2:"för att öppna objekt.",
contributeHeader:"BLI EN BIDRAG",
contribute1:"Se en kort video om motivation bakom ResearchX3D ...",
contribute2:"... eller se bara en introduktion till ResearchX3D på 4 minuter.",
contribute3:"ResearchX3D skapar 3D-modeller från dina fotografier ...",
contribute4:"... men du kan också ladda upp redan skapade 3D-objekt, till exempel från ett CAD-program.",
contribute5:"Varje objekt har många historier att berätta. Genom att skapa olika typer av berättelser kan du:",
contribute6:"Förklara en funktion och en design; eller",
contribute7:"Testa kunskap med ett frågesport; eller",
contribute8:"Dela färdigheter och procedurer.",
contribute9:"Så här hjälper ResearchX3D-redigeraren dig att skapa en historia.",
clickvideo:"Klicka här för att se videon.",
clickexample:"Klicka här för att se ett exempel",
openstory:"Öppna den här historien",
allsbj:"alla ämnesområden",
showall:"visa all",
graphic:"grafisk",
figclick:"Pata hadithi na ufafanuzi juu ya kitu hiki",
openar:"öppet i Augmented Reality",
meniagora:"Gemenskapsdiskussioner - Agora",
r3dsummary:"<b> Vad är ResearchX3D? </b> En öppen community-plattform för att dela vetenskapligt arv för att låsa upp kreativt värde för framtiden.",
agoraad:"<b> Föreslå och diskutera </b> idéer om ResearchX3D-projektet och få hjälp med vårt Agora <img class = 'link' src = '/link.png'> för diskussioner i gemenskapen."
};
