const lang_sr ={close:"Zatvori",
loadingmodel:"Učitavanje modela",
menistartpage:"Početna stranica",
menifind:"Pronađite objekte, priče i pitanja",
meniadd:"Dodavanje ili uređivanje priče o objektima",
meniask:"Postavite pitanje o objektu",
meniupload:"Pošaljite fotografije predmeta za 3D model",
menishare:"Podelite predmeta ili priče",
meniar:"Povećana stvarnost ...",
meniaron:"Uključite AR režim",
menimarker:"Štampajte AR markere",
menisupport:"Kontakt i podrška",
meniabout:"O ResearchX3D",
menilogin:"Prijavite se",
menilogout:"Odjavite se",
headfind:"Pronađi",
headfindt:"Potražite eksperimentalni aparat",
headcontribute:"Doprinesi",
headcontributet:"Pomozite nam da povećamo kolekciju predmeta!",
headaron:"AR ON",
headaront:"Kliknite da biste uključili uvećanu stvarnost",
headaroff:"AR OFF",
headarofft:"Kliknite da biste isključili AR",
meni0_0:"ZA STUDENTE",
meni0_1:"Pronađite. Sve, od istorijskih eksperimenata, do finog vijka za podešavanje.",
meni0_2:"Dobijte inspiraciju. Proširite svoj kreativni prostor razmišljajući o različitim mogućnostima dizajna.",
meni1_0:"ZA PREDAVAČE",
meni1_1:"Upotrebite. Pokažite u prezentacijama i kursevima.",
meni1_2:"Kreirajte. Označite predmete sa vašim komentarima i podelite vašu priču o njima.",
meni2_0:"ZA ISTRAŽIVAČE",
meni2_1:"Doprinesite. Potrebna je jedna pauza za kafu da biste podeliti sa celim svetom tu aparaturu pored koje svakodnevno prolazite.",
meni2_2:"Istražite. Pratite razvoj ideja za dizajn.",
aboutheader:"O ResearchX3D.com",
aboutteam:"Tim",
aboutcontact:"Kontakt",
about0:"Delimo naučno nasleđe kako bismo otključali stvaralačku vrednost za budućnost! Eksperimentalni aparature su ključni elementi naučnog istraživanja. I istorijski eksperimenti i moderni dizajni su dragocena baština. Jednom kada se ovi objekti podele, oni postaju koristan resurs, podstičući kreativnost ljudi širom sveta. A sada je moguće podeliti eksperimentalne aparate tokom jedne pauze za kafu!",
about1:"Šta radi ResearchX3D.com?",
about2:"Na osnovu <b> vaših dostavljenih fotografija</b> naučnih aparata iz vaših laboratorija, univerzitetskih hodnika i uredskih polica ...",
about3:"... <b>mi stvaramo 3D modele </b> koje može istražiti bilo ko u veb pretraživaču.",
about4:"ResearchX3D.com tada omogućava da se poveća uticaj nasleđa i akumulira znanje o aparaturama:",
about5:"<b> 3D označavanje </b> objekata sa markerima i strelicama u 3D prostoru lako se vrši putem ResearchX3D mrežnog uređivača. Napomene mogu biti popraćene <b> tekstualnim i zvučnim opisima </b>;",
about6:"Grupe etiketa čine priče o objektima. Korisnici mogu <b> pronaći priče na osnovu nivoa svog znanja </b>. Obuhvaćeni su korisnici iz čitavog spektra: od nastave u osnovnoj i srednjoj školi, preko detaljnih opisa na univerzitetskom nivou, do naprednih diskusija o dizajnu prodmeta za na nivou doktorata / istraživanja;",
about7:"Svako može postaviti pitanje. I <b> pitanja i odgovori </b> koriste 3D nalepnice za <b> \"pokaži\" i objasni \"opise </b>. Korisnici najbolje odgovore izglasavaju;",
about8:"Predmeti se mogu videti u <b> proširenoj stvarnosti </b>, omogućavajući svima da vide eksperimentalnu aparaturu na svom stolu;",
about9:"Sva funkcionalnost je omogućana kroz web interfejs (bez instalacije, nezavisne od platforme), omogućavajući <b> lako deljenje </b> objekata i priča slanjem linkova kolegama i prijateljima.",
about10:"Platforma ResearchX3D.com ima za cilj",
about12:"Fizičari, trenutno na postdoktorskom finansiranju Marie Curie na <a href=\"https://vvv.institutoptique.fr/\"> Institute d'Optique, Palaiseau, Francuska </a>.",
about13:"Kontaktirajte nas na <a href='mailto:contact@researchx3d.com?subject=Feedback'> contact@researchx3d.com </a>.",
aboutli0:"Očuvanje modela naučne i tehničke baštine;",
aboutli1:"Beleženje dizajnerskih opisa istraživača i inženjera kako bi zaštitili ideje i trikove za budućnost;",
aboutli2:"Predstavljanje naučnog i industrijskog nasleđa na način koji inspiriše i proširuje kreativni prostor u publici širom spektra, od nastave do nivoa istraživanja; i",
aboutli3:"Demokratizacija pristupa eksperimentalnom dizajnu aparata tako što nešto prethodno dostupno samo nekolicini sretnika i delimo sa celim svetom.",
findobject:"Traženje objekta ...",
findstory:"... a zatim izaberite priču / napomenu",
findquestion:"... ili pogledajte pitanja i odgovore",
filtersubject:"Filtriraj prema predmetnoj oblasti:",
filterknowledgelevel:"Filtriraj po nivou znanja:",
shareqr:"Podelite eksperimentalni aparat i priču direktnom vezom ili QR kodom",
click2copy:"kliknite da biste kopirali vezu",
saveqr:"Sačuvaj sliku QR koda",
askquestion:"Postavi pitanje",
share:"Objavi",
addmodifystory:"Dodajte / izmenite svoju priču",
depositedby:"Izložio",
logoutsuccess:"Uspešno ste odjavljeni!",
objectannotation:"Napomena o objektu",
objectannotationt:"kliknite da biste izabrali različite napomene",
by:"od strane",
location:"Lokacija",
details:"Detalji",
tags:"Oznake",
forthisobject:"za ovaj objekt",
object:"objekta",
previousm:"Prethodni odeljak",
nextm:"Sledeći odeljak",
or:"ili",
moto:"Deljenje naučnog nasleđa radi otključavanja kreativne vrednosti za budućnost.",
pleaselogin:"Da biste nastavili, prijavite se",
enteremail:"Unesite adresu e-pošte",
enterpassword:"Unesite lozinku",
login:"Prijavite se",
forgotpassword:"Zaboravili ste lozinku?",
cancel:"Otkaži",
newuser:"Novi korisnik?",
loginnote1:"Da biste dodali predmete, napomene i pitali i odgovarali na pitanja, morate da se prijavite.",
loginnote2:"Da biste uneli izmene, prvo morate da potvrdite svoj identitet, a zatim pritisnite 'Sačuvaj'.",
add:"Dodati",
remove:"Ukloni",
finally:"Konačno",
annotation:"segment priče",
savestory:"sačuvaj priču",
level1:"osnovna škola",
level2:"srednja škola",
level3:"univerzitet (do-diplomski)",
level4:"Doktorat / istraživanja",
addmarker:"Dodajte marker",
addarrow:"dodajte strelicu",
textual:"tekstualni",
audio:"audio",
addexp:"Dodati",
explanation:"opis za ovu napomenu",
marker:"marker",
arrow:"strelaca",
at:"u",
angle:"ugao",
arintro:"Stavite marker <a href=\"/print_marker.pdf\"><img src = \"\\ar_marker_small.png\" align = \"middle\" ></a> u prikaz kamere. <br/> Da biste se kretali po priči, kliknite na strelice levo i desno.",
noexistingaudio:"Nema postojećih audio opisa.",
newupload:"Novo otpremanje",
newrecording:"Novo snimanje",
recordsound:"Počeli sa snimanjem",
stopbutton:"Zaustavi snimanje",
storytitle:"Naslov priče",
storydesc:"Kratak rezime ove priče o objektima ...",
adddesc:"Dodajte opis za ovu napomenu ...",
arrowadjust:"Podesite položaj i orijentaciju strelice, a zatim",
markeradjust:"Podesite položaj markera, a zatim",
savemarker:"zapamti marker",
savearrow:"zapamti strelicu",
audiodesc:"Audio opis:",
clicktochangelan:"Kliknite da biste promenili jezik",
getarmarkers:"dobiti oznake proširene stvarnosti",
contributeh2:"Doprinesite eksperimentalnu aparaturu ... potrebna je jedna pauza za kafu!",
contributeh3_1:"Kako ovo radi?",
contributeh3_2:"Spremni? Počnite ovde...",
contributeli1:"<b> Vi</b> dodate ~ 30 fotografija eksperimentalnog aparata koji dokumentujete. Pokušajte snimiti fotografije tako da se svaka tačka na objektu vidi na 3-6 fotografija iz različitih uglova. Više fotografija je bolje nego manje fotografija!",
contributeli2:"<b> Mi </b> potom izradimo 3D model na osnovu vaših fotografija, koristeći softver za fotogrametriju, i postavimo ga na mreži na platformi ResearchX3D",
contributeli3:"<b> Svi </b> mogu tada da proučavaju objekat, označavaju priče na njemu, postavljaju pitanja i dele rekonstruisani 3D model putem interneta. Vi kao vlasnik dobićete prvu pozivnicu za dodavanje komentara i priče, koja će biti istaknuta kao originalna priča.",
contributep1:"To je sve, istraživačko nasleđe je dostupno širom sveta za ostale studente, predavače i istraživače.",
contributep2:"Trenutno prihvatamo priloge samo od korisnika koji imaju akademsku poštu. U slučaju da nemate akademski email, ali želite da date svoj doprinos, molimo <input type=\"button\" onclick=\"openBoard('aboutProject');\" value=\"kontaktirajte nas\" />.",
contributestart:"Pocnite ovde!",
newuserh3:"Nova registracija korisnika",
newuseri1:"Ime",
newuseri1l:" Vaše ime i prezime će se pojaviti pored objekata koje prenosite / napominjete.",
newuseri2:"Prezime",
newuseri3:"Institucija i zemlja",
newuseri3l:" Vaša institucionalna afiliacija i zemlja lokacije.",
newuseri4:"email",
newuseri4l:" Napomena: prihvataju se samo akademske adrese e-pošte. Dobićete vezu za potvrdu.",
newuseri5:"Unesite lozinku",
newuseri5l:" Minimum 8 znakova.",
newuseri6:"Ponovite lozinku",
newuseri6l:" Samo da proverim da nema grešaka pri upisu.",
newusersubmit:"Registrujte novog korisnika",
uploadedobjects:"Postojeći dodati objekti:",
nameobject:"Dajte naziv svom novom objektu",
enterobjectname:"unesite novo ime objekta",
and:"i",
cratephotospace:"stvorite prostor za fotografije",
photolisting:"Spisak fotografija",
nophotolist:"Još niste otpremili fotografije za nijedan objekat. Molimo pošaljite dole fotografije objekta.",
uploadnewphotos:"Otpremite nove datoteke",
startupload:"Započni slanje",
metadataobject:"Metapodaci o fotografisanom objektu",
objtitle:"Naslov objekta",
objtitlel:"Naslov objekta",
objdetails:"Detalji o objektu",
objdetailsl:"kratak opis predmeta",
objlocation:"Izvorna i sadašnja lokacija objekta",
objyear:"Godina kada je predmet napravljen (procena)",
objtags:"Oznake objekta",
objsubmit:"Pošaljite fotografiju za rekonstrukciju 3D objekta",
newobjectspaceerror:"Došlo je do greške prilikom pravljenja prostora vašeg objekta:",
newobjectspacesuccess:"Uspešno stvoren prostor za fotografije novog objekta.",
objsubmerr1:"GREŠKA: Pre slanja morate da dodate neke <b> oznake objekta </b>!",
objsubmerr2:"GREŠKA: Ime objekta mora biti dužine od najmanje 3 slova",
objsubmerr3:"GREŠKA: Unesite najmanje 10 slova za opis objekta.",
objsubmerr4:"GREŠKA: Molimo unesite lokaciju objekta (istorijsku, sadašnju ili kompaniju od koje je dostupan).",
objsubmerr5:"GREŠKA: Unesite godinu izrade objekta (procenjeno).",
delete:"izbriši",
question:"Pitanje",
answers:"Odgovori",
addeditanswer:"Dodajte ili izmenite odgovor",
clickdownvotel:"kliknite da biste opozvali pitanje ili odgovor",
clickupvotel:"kliknite da biste ponovili pitanje ili odgovor",
yourquestion:"Tvoje pitanje:",
questiondesc:"Dodajte napomenu na objekt i opišite tekstualne detalje pitanja.",
submitquestion:"Pošaljite pitanje",
tooltipmainm:"Kliknite da biste otvorili glavni meni",
meniobject:"Objekat",
questiontitle:"Naslov pitanja",
aboutfunding:"Finansiranje",
about15:"Projekat podržao Nauka i društvo La Diagonale Paris-Saclay.",
size:"veličina",
color:"boja",
red:"crvena",
green:"zelena",
blue:"plava",
orange:"narandžasta",
magenta:"magenta",
selectlicense:"Odaberite licencu za učitane datoteke (rekonstruisani model će biti objavljen pod istom licencom)",
read:"čitati",
licensetext:"licence",
translated:"Prevedeno",
transsee:"vidite prevod na ",
transsource:"Original tekst",
transseesource:"vidite original na ",
transimprove:"unapredite prevod",
"fr":"francuskom",
"en":"engleskom",
"es":"spanskom",
"pt":"portugalskom",
"de":"nemačkom",
"zh":"kineskom",
"ru":"ruskom",
"ar":"arapskom",
"sv":"svedskom",
"nl":"holandskom",
"it":"italijanskom",
"ja":"japanskom",
"sr":"srpski",
"cs":"ceškom",
"da":"danskom",
"sw":"svahiliju",
"hi":"hindi",
"tr":"turskom",
"vi":"vijetnamskom",
"th":"tailandskom",
"ko":"koreanskom",
"fa":"farsiju",
"id":"indonežanskom",
"cy":"velškom",
"el":"grčkom",
"ro":"rumunskom",
"hu":"madjarskom",
"pl":"poljskom",
transimprovetitle:"Unapredi prevod",
transnote:"Prevod nastaje združenim snagama mašinskog prevodjenja i ljudski unetih ispravki. Hvala Vam što ulažete vreme u unapredjenje!",
transorigin:"Tekst originala na ",
transsuggest:"Prevod na ",
transsubmit:"Posaljite prevod",
press:"Pritisni",
forillustration:"za ilustraciju",
storylang:"Pisano na jeziku:",
footer0:"O nama - ResearchX3D",
footer1:"Pretražite predmete, priče i pitanja",
footer2:"Pitajte pitanje o objektu",
footer3:"Povećana stvarnost",
footer4:"Pošaljite objekt",
footer5:"Pošaljite priču",
footer_title1:"BRZI LINKOVI",
footer_title2:"DRUŠTVENE VEZE",
navigation:"Navigacija",
rotation:"da rotirate",
move:"pomerite, ili",
zoom:"uvećate objekat",
clickForStory:"Kliknite ovde da vidite priču o objektu.",
latexAdd:"ili dodajte u LaTeX dokument",
latexPDF:"preuzmite PDF sliku ovde",
latexCode:"i dodajte kod u nastavku.",
latexCaption1:"Skenirajte QR kod ili unesite",
latexCaption2:"da otvorite objekat.",
contributeHeader:"DOPRINESITE",
contribute1:"Pogledajte kratki video o motivaciji za ResearchX3D ...",
contribute2:"... ili pogledajte samo 4-minutni uvod ResearchX3D.",
contribute3:"ResearchX3D kreira 3D modele od vaših fotografija ...",
contribute4:"... ali takođe možete otpremiti već stvorene 3D objekte, na primer iz CAD softvera.",
contribute5:"Svaki predmet ima mnogo priča. Stvaranjem različitih vrsta priča možete:",
contribute6:"Objasniti funkciju i dizajn; ili",
contribute7:"Proveriti znanje pomoću kviza; ili",
contribute8:"Podeliti veštine i procedure.",
contribute9:"Evo kako vam urednik ResearchX3D pomaže u stvaranju priče.",
clickvideo:"Kliknite ovde da biste videli video.",
clickexample:"Kliknite ovde da biste videli primer.",
openstory:"Otvori ovu priču",
allsbj:"sva predmetna područja",
showall:"pokaži sve",
graphic:"grafički",
figclick:"Pronađite priče i oznake o ovom objektu",
openar:"otvorite u uvećanoj realnosti",
meniagora:"Diskusije u zajednici - Agora",
r3dsummary:"<b>Šta je ResearchX3D? </b> Otvorevna platforma zajednice za razmenu naučnog nasledja kako bi se otključala kreativna vrednost za budućnost.",
agoraad:"<b>Predložite i diskutujte</b> ideje o projektu ResearchX3D i potražite pomoć na našoj Agori <img class= 'link' src = '/link.png'> za diskusiju u zajednici."
};
