const lang_en = {
  close:"Close",
  loadingmodel:"Loading 3D model of ",
  menistartpage:"Homepage",
  menifind:"Find objects, stories and questions",
  meniadd:"Add or edit story",
  meniask:"Ask a question on an object",
  meniupload:"Upload photos for 3D model",
  menishare:"Share object or story",
  meniar:"Augmented reality...",
  meniaron:"Turn on AR mode",
  menimarker:"Print AR markers",
  menisupport:"Contact & support",
  meniabout:"About ResearchX3D",
  menilogin:"Login",
  menilogout:"Logout",
  headfind:"Search",
  headfindt:"Search for experimental apparatus",
  headcontribute:"Contribute",
  headcontributet:"Help us to grow our collection of objects!",
  headaron:"AR ON",
  headaront:"Click to turn on Augmented Reality",
  headaroff:"AR OFF",
  headarofft:"Click to turn AR off",
  meni0_0:"FOR STUDENTS",
  meni0_1:"Find. Everything from historical experiments, to fine adjustment screws.",
  meni0_2:"Get inspired. Expand your own creative space by thinking about different design possibilities.",
  meni1_0:"FOR EDUCATORS",
  meni1_1:"Use. Show in presentations and share in lecture notes.",
  meni1_2:"Create. Annotate objects by your own description, and share your story about them.",
  meni2_0:"FOR RESEARCHERS",
  meni2_1:"Contribute. It takes one coffee break to share with the whole world that apparatus you are passing by every day.",
  meni2_2:"Explore. Track the development of design ideas.",
  aboutheader:"About the ResearchX3D.com",
  aboutteam:"Contact & project team",
  about0:"Let's share our scientific heritage to unlock our creative potential for the future! An experimental apparatus is a key element in scientific research. Both historical experiments and modern designs are a valuable heritage. Once these objects are shared, they become useful resources, stimulating creativity of people around the world. And now it's possible to share experimental apparatus during a coffee break!",
  about1:"What does ResearchX3D.com do?",
  about2:"Based on <b>user uploaded photographs</b> of scientific apparatus from their labs, university corridors, and office shelves... ",
  about3:"...we <b>create 3D models</b> explorable by anyone in web browser.",
  about4:"ResearchX3D.com then allows one to enhance the impact of our scientific heritage and accumulates knowledge on apparatus:",
  about5:"<b>3D labeling</b> of objects with markers and arrows in 3D space is easily done through our online editor. Annotations can be accompanied with <b>textual, graphical and/or audio descriptions</b>;",
  about6:"Groups of labels make stories about the objects. Users can <b>find stories based on their knowledge level</b>. The full user spectrum is covered: from primary school and high school teaching, through university-level detailed descriptions, to advanced discussions on apparatus design for PhD/research level. ResearchX3D and selected stories are <b>available in 25 languages</b>.",
  about7:"Everyone can ask a question. Both <b>questions and answers</b> use 3D labels for <b>\"point-and-tell\" descriptions</b>. The best answers are upvoted by the users;",
  about8:"Objects can be seen in <b>augmented reality</b>, allowing everyone to see experimental apparatus on their desk;",
  about9:"All functionalities work through the web interface (no installation, platform independent), allowing <b>easy sharing</b> of objects and stories by sending links to colleagues and friends.",
  about10:"ResearchX3D.com platform aims to",
  about12:"Physicists, currently Marie Curie postdoctoral fellows at <a href=\"https://www.institutoptique.fr/\">Institute d'Optique, Palaiseau, France</a>.",
  about13:"Reach us at <a href='mailto:contact@researchx3d.com?subject=Feedback'>contact@researchx3d.com</a>.",
  aboutli0:"Preserve object models of scientific and technical heritage;",
  aboutli1:"Record design descriptions by researchers to safeguard design ideas and tricks for the future;",
  aboutli2:"Present the scientific heritage in a way that inspires and expands creative thinking in audiences across the spectrum, from teaching to research level; and",
  aboutli3:"Democratize access to experimental apparatus design, by taking something previously accessible only to a lucky few and sharing it with the whole world.",
  findobject:"Search for object...",
  findstory:"...and then choose story/annotation",
  findquestion:"...or see questions and answers",
  filtersubject:"Filter by subject area:",
  filterknowledgelevel:"Filter by knowledge level:",
shareqr:"Share experimental apparatus and story with direct link or QR code",
click2copy:"click to copy link",
saveqr:"Save QR code image",
askquestion:"Ask question",
share:"share",
addmodifystory:"Add/modify your story",
depositedby:"Deposited by",
logoutsuccess:"You have been successfully logged out!",
objectannotation:"Object annotation",
objectannotationt:"Click to select different annotation",
by:"by",
location:"Location",
details:"Details",
tags:"Tags",
forthisobject:"for this object",
object:"object",
previousm:"Previous section",
nextm:"Next section",
or:"or",
moto:"Sharing scientific heritage to unlock creative value for future.",
pleaselogin:"To proceed please login",
enteremail:"Enter email",
enterpassword:"Enter Password",
login:"Login",
forgotpassword:"Forgot password?",
cancel:"Cancel",
newuser:"New user?",
loginnote1:"To add objects, annotations and ask/respond to questions you need to login.",
loginnote2:"To save changes you need first to confirm your identity and then press 'Save'.",
add:"Add",
remove:"remove",
finally:"Finally",
annotation:"story segment",
savestory:"save story",
level1:"primary school",
level2:"highschool",
level3:"university (undergraduate)",
level4:"PhD/research",
addmarker:"Add marker",
addarrow:"add arrow",
textual:"textual",
audio:"audio",
addexp:"Add",
explanation:"description for this annotation",
marker:"marker",
arrow:"arrow",
at:"at ",
angle:"angle",
arintro:"Put the <a href=\"/print_marker.pdf\"><img alt=\"R3D\" src=\"\\ar_marker_small.png\" align=\"middle\" si></a> marker in the camera view.<br/>  To navigate story, click on arrows left and        right. ",
noexistingaudio:"No existing audio descriptions.",
newupload:"New upload ",
newrecording:"New recording ",
recordsound:"Start recording",
stopbutton:"Stop recording",
storytitle:"Story title",
storydesc:"Short summary of this object story...",
adddesc:"Add a description for this annotation ...",
arrowadjust:"Adjust arrow position and orientation, and then ",
markeradjust:"Adjust marker position and then ",
savemarker:"save marker",
savearrow:"save arrow",
audiodesc:"Audio description: ",
clicktochangelan:"Click to change language",
getarmarkers:"get augmented reality markers",
contributeh2:"Contribute an apparatus... it takes one coffee break!",
contributeh3_1:"How does it work?",
contributeh3_2:"Ready? Start here...",
contributeli1:"<b>You</b> upload ~30 photos of the experimental apparatus you are documenting. Try taking photographs such that each point on the object is seen on 3-6 photographs from different angles. More photos is better than less photos!",
contributeli2:"<b>We build 3D model from your photos</b>, using photogrammetry softwares, and put it online on the ResearchX3D",
contributeli3:"<b>Everyone</b> can explore, annotate, ask questions and share reconstructed 3D models once it's online. You as owner will receive first invitation to add annotation and story, that will be highlighted as original annotation.",
contributep1:"That's all, the research heritage is available world-wide, for  other students, educators and researchers.",
contributep2:"At the moment we only accept contributions from users with academic emails. If you don't have an academic email but would like to contribute, please <input type=\"button\" onclick=\"openBoard('aboutProject');\" value=\"contact us\"/>.",
contributestart:"Start object photo upload",
newuserh3:"New user registration",
newuseri1:"Name",
newuseri1l:" Your name and surname will appear next to objects you upload/annotate.",
newuseri2:"Surname",
newuseri3:"Institution and country",
newuseri3l:" Your affiliation and country of location.",
newuseri4:"email",
newuseri4l:" Note: only academic emails are accepted. You will receive a confirmation link.",
newuseri5:"Enter password",
newuseri5l:" Minimum of 8 characters.",
newuseri6:"Repeat password",
newuseri6l:" Just to check there is no typos.",
newusersubmit:"Register a new user",
uploadedobjects:"Existing uploaded objects:",
nameobject:"Name your new object ",
enterobjectname:"enter new object name",
and:"and",
cratephotospace:"create a space for photographs",
photolisting:"Listing of photographs of",
nophotolist:"You have not uploaded photos for any  object yet. Please upload photographs below.",
uploadnewphotos:"Upload new files",
startupload:"Start upload",
metadataobject:"Metadata on photographed object",
objtitle:"Object title",
objtitlel:"Object title",
objdetails:"Object details",
objdetailsl:"short object description",
objlocation:"Original and present location of object",
objlocationl:"e.g. CERN (currently at University of ...)",
objyear:"Year when object was made (estimate)",
objtags:"Object tags",
objsubmit:"Submit photo for 3D object reconstruction",
newobjectspaceerror:"There was an error creating your object space: ",
newobjectspacesuccess:"Successfully created space for photographs of a new object.",
objsubmerr1:"ERROR: You need to add some <b>Object tags</b> before submission!",
objsubmerr2:"ERROR: Object name has to have length of at least 3 characters",
objsubmerr3:"ERROR: Enter at least 10 characters for the object description.",
objsubmerr4:"ERROR: Please enter the object location (historical, present, or company from which it is available).",
objsubmerr5:"ERROR: Please enter year of object creation (estimated).",
delete:"delete",
question:"Question",
answers:"Answers",
addeditanswer:"Add or Edit your answer",
clickdownvotel:"click to downvote question or answer",
clickupvotel:"click to upvote question or answer",
yourquestion:"Your question:",
questiondesc:"Add annotation on object and answer textually a questiion.",
submitquestion:"Submit question",
tooltipmainm:"Click to open main menu",
meniobject:"Object",
questiontitle:"Question title",
aboutfunding:"Funding",
about15:"This project is supported by the Science and Society of La Diagonale Paris-Saclay.",
size:"size",
color:"color",
red:"red",
green:"green",
blue:"blue",
orange:"orange",
magenta:"magenta",
selectlicense:"Select license for uploaded files (the reconstructed model will be released under the same license)",
read:"read",
licensetext:"license",
translated:"Translated",
transsee:"see translation in ",
transsource:"Original text",
transseesource:"see original in ",
transimprove:"improve translation",
"fr":"French",
"en":"English",
"es":"Spanish",
"pt":"Portugese",
"de":"German",
"zh":"Chinese",
"ru":"Russian",
"ar":"Arabic",
"sv":"Swedish",
"nl":"Dutch",
"it":"Italian",
"ja":"Japanese",
"sr":"Serbian",
"cs":"Czech",
"da":"Danish",
"sw":"Swahili",
"hi":"Hindi",
"tr":"Turkish",
"vi":"Vietnamese",
"th":"Thai",
"ko":"Korean",
"fa":"Farsi",
"id":"Indonesian",
"cy":"Welsh",
"el":"Greek",
"ro":"Romanian",
"hu":"Hungarian",
"pl":"Polish",
transimprovetitle:"Improve translation",
transnote:"Translation is a joint effort of machine translation and human contributed feedback. Thank you for taking time to contribute.",
transorigin:"Original in ",
transsuggest:"Translation in ",
transsubmit:"Submit translation",
press:"Press",
forillustration:"for illustration",
storylang:"Written in language:",
footer0:"About ResearchX3D",
footer1:"Search objects, stories and questions",
footer2:"Ask a question on object",
footer3:"Augmented reality",
footer4:"Submit object",
footer5:"Submit story",
footer_title1:"QUICK LINKS",
footer_title2:"SOCIAL LINKS",
navigation:"Navigation",
rotation:"to rotate",
move:"move, or",
zoom:"zoom the object",
clickForStory:"Click here to see the object story.",
latexAdd:"or add to LaTeX document",
latexPDF:"download PDF image here",
latexCode:"and add code below.",
latexCaption1:"Scan QR code or enter",
latexCaption2:"in order to open object.",
contributeHeader:"BECOME A CONTRIBUTOR",
contribute1:"Watch a short video about motivation behind ResearchX3D...",
contribute2:"...or see just a 4-min ResearchX3D introduction.",
contribute3:"ResearchX3D creates 3D models from your photographs...",
contribute4:"...but you can also upload already created 3D objects, for example from a CAD software.",
contribute5:"Every object has many stories to tell. By creating different types of stories you can:",
contribute6:"Explain a function and a design; or",
contribute7:"Test knowledge with a quiz; or",
contribute8:"Share skills and procedures.",
contribute9:"Here is how the ResearchX3D editor helps you to create a story.",
clickvideo:"Click to see the video.",
clickexample:"Click to see an example.",
openstory:"Open this story",
allsbj:"all subject areas",
showall:"show all",
graphic:"graphic",
figclick:"Find stories and annotations about this object",
openar:"open in Augmented Reality",
meniagora:"Community discussions - Agora",
r3dsummary:"<b>What is ResearchX3D?</b> An open community platform for sharing scientific heritage to unlock creative value for future.",
agoraad:"<b>Suggest and discuss</b> ideas about ResearchX3D project, and get help on our Agora <img class='link' src='/link.png'> for Community Discussions."
};
