const lang_da ={close:"Tæt",
loadingmodel:"Indlæser model",
menistartpage:"Hjemmeside",
menifind:"Find objekter, historier og spørgsmål",
meniadd:"Tilføj eller rediger objekthistorie",
meniask:"Stil spørgsmål om objekt",
meniupload:"Upload objektfotos til 3D-model",
menishare:"Del objekt eller historie",
meniar:"Forstørret virkelighed ...",
meniaron:"Tænd for AR-tilstand",
menimarker:"Udskriv AR-markører",
menisupport:"Kontakt support",
meniabout:"Om ResearchX3D",
menilogin:"Log på",
menilogout:"Log ud",
headfind:"Finde",
headfindt:"Søg efter eksperimentelt udstyr",
headcontribute:"Bidrage",
headcontributet:"Hjælp os med at dyrke samling af genstande!",
headaron:"AR TIL",
headaront:"Klik for at slå Augmented Reality til",
headaroff:"AR OFF",
headarofft:"Klik for at slå AR fra",
meni0_0:"FOR STUDERENDE",
meni0_1:"Finde. Alt fra historiske eksperimenter til fine justeringsskruer.",
meni0_2:"Blive inspireret. Udvid dit eget kreative rum ved at tænke over forskellige designmuligheder.",
meni1_0:"FOR UNDERVISERE",
meni1_1:"Brug. Vis i præsentationer og kurser.",
meni1_2:"Skab. Annotér objekter ved din egen beskrivelse, og del din historie om dem.",
meni2_0:"FOR FORSKERE",
meni2_1:"Bidrage. Det tager en kaffepause at dele det apparatur, du passerer hver dag med en hel verden.",
meni2_2:"Udforske. Spor udvikling af designideer.",
aboutheader:"Om ResearchX3D.com",
aboutteam:"Hold",
aboutcontact:"Contant",
about0:"Lad os dele videnskabelig arv for at åbne kreativ værdi for fremtiden! Eksperimentelt apparatur er nøgleelement i videnskabelig forskning. Både historiske eksperimenter og moderne design er værdifuld arv. Når disse objekter deles, bliver de nyttige ressourcer, hvilket stimulerer mennesker rundt om i verden. Og nu er det muligt at dele eksperimentel appparatus i kaffepausen!",
about1:"Hvad ResearchX3D.com gør?",
about2:"Baseret på <b> bruger uploadede fotos </b> af videnskabelige apparater fra deres laboratorier, universitetskorridorer og kontorhylder ...",
about3:"... vi <b> opretter 3D-modeller </b>, der kan udforskes af alle i webbrowser.",
about4:"ResearchX3D.com tillader derefter en at forbedre indflydelsen fra arv og akkumulerer viden om apparater:",
about5:"<b> 3D-mærkning </b> af objekter med markører og pile i 3D-rum kan let udføres via online editor. Bemærkninger kan ledsages af <b> tekst- og lydbeskrivelser </b>;",
about6:"Grupper af etiketter laver historier om objekterne. Brugere kan <b> finde historier baseret på deres videniveau </b>. Brugere på tværs af spektret er dækket: fra grundskole- og gymnasielære, gennem detaljerede beskrivelser på universitetsniveau, til avancerede diskussioner om appartusdesign til ph.d. / forskningsniveau;",
about7:"Alle kan stille et spørgsmål. Både <b> spørgsmål og svar </b> bruger 3D-mærker til <b> \"peg-og-fortæl\" -beskrivelser </b>. De bedste svar anbefales af brugerne;",
about8:"Objekter kan ses i <b> augmented reality </b>, så alle kan se eksperimentelle apparater på deres skrivebord;",
about9:"Al funktionalitet bringes via webgrænsefladen (ingen installation, platform uafhængig), hvilket tillader <b> nem deling </b> af objekter og historier ved at sende links til kolleger og venner.",
about10:"ResearchX3D.com-platformen sigter mod",
about12:"Fysikere, i øjeblikket Marie Curie-postdoktorale stipendiater på <a href=\"https://www.institutoptique.fr/\"> Institut d'Optique, Palaiseau, Frankrig </a>.",
about13:"Kontakt os på <a href='mailto:contact@researchx3d.com?subject=Feedback'> contact@researchx3d.com </a>.",
aboutli0:"Bevar objektmodeller for videnskabelig og teknisk arv;",
aboutli1:"Registrer designbeskrivelser fra forskere for at beskytte designideer og tricks for fremtiden;",
aboutli2:"Præsentere arv på en måde, der inspirerer og udvider kreativt rum i publikum på tværs af spektrene, fra undervisning til forskningsniveau; og",
aboutli3:"Demokratiserer adgangen til design af eksperimentelt apparatur ved at tage noget, der tidligere kun var tilgængeligt for få heldige, og dele det hele verden.",
findobject:"Søg efter objekt ...",
findstory:"... og vælg derefter historie / annotation",
findquestion:"... eller se spørgsmål og svar",
filtersubject:"Filtrer efter emneområde:",
filterknowledgelevel:"Filtrer efter videniveau:",
shareqr:"Del eksperimentelt apparatur og historie med direkte link eller QR-kode",
click2copy:"Klik for at kopiere linket",
saveqr:"Gem QR-kode billede",
askquestion:"Stil spørgsmål",
share:"del",
addmodifystory:"Tilføj / rediger din historie",
depositedby:"Indskudt af",
logoutsuccess:"Du er logget ud!",
objectannotation:"Objektnotering:",
objectannotationt:"Klik for at vælge anden annotation",
by:"ved",
location:"Beliggenhed",
details:"detaljer",
tags:"Tags",
forthisobject:"for dette objekt",
object:"objekt",
previousm:"Forrige afsnit",
nextm:"Næste afsnit",
or:"eller",
moto:"Deling af videnskabelig arv for at åbne kreativ værdi for fremtiden.",
pleaselogin:"For at fortsætte skal du logge ind",
enteremail:"Indtast e-mail",
enterpassword:"Indtast adgangskode",
login:"Log på",
forgotpassword:"glemt kodeord?",
cancel:"Afbestille",
newuser:"Ny bruger?",
loginnote1:"For at tilføje objekter, kommentarer og stille og svare på spørgsmål, du har brug for at logge ind.",
loginnote2:"For at gemme ændringer skal du først bekræfte din identitet og derefter trykke på 'Gem'.",
add:"Tilføje",
remove:"fjerne",
finally:"Endelig",
annotation:"historie segment",
savestory:"gem historien",
level1:"folkeskole",
level2:"Gymnasium",
level3:"universitet (studerende)",
level4:"Ph.d. / forskning",
addmarker:"Tilføj markør",
addarrow:"tilføj pil",
textual:"tekstmæssige",
audio:"lyd",
addexp:"Tilføje",
explanation:"beskrivelse af denne annotation",
marker:"markør",
arrow:"pil",
at:"på",
angle:"vinkel",
arintro:"Sæt markøren <a href=\"/print_marker.pdf\"><img src=\"\\ar_marker_small.png\" align=\"middle\" si></a> i kameravisningen. <br/> Klik på pilene til venstre og højre for at navigere i historien.",
noexistingaudio:"Ingen eksisterende lydbeskrivelser.",
newupload:"Ny upload",
newrecording:"Ny optagelse",
recordsound:"Start optagelse",
stopbutton:"Stop optagelse",
storytitle:"Historietitel",
storydesc:"Kort resume af denne objekthistorie ...",
adddesc:"Tilføj beskrivelse til denne kommentar ...",
arrowadjust:"Juster pilens position og retning, og derefter",
markeradjust:"Juster markørpositionen og derefter",
savemarker:"gem markør",
savearrow:"gem pil",
audiodesc:"Lydbeskrivelse:",
clicktochangelan:"Klik for at ændre sprog",
getarmarkers:"få augmented reality-markører",
contributeh2:"Bidrag apparater ... det tager en kaffepause!",
contributeh3_1:"Hvordan det virker?",
contributeh3_2:"Parat? Start her...",
contributeli1:"<b> Du </b> uploader ~ 30 fotos af det eksperimentelle apparat, du dokumenterer. Prøv at tage fotografier, så hvert punkt på objektet ses på 3-6 fotografier fra forskellige vinkler. Flere fotos er bedre end mindre fotos!",
contributeli2:"<b> Vi bygger 3D-model ud fra dine fotos </b> ved hjælp af fotogrammetri-software og sætter den online på ResearchX3D",
contributeli3:"<b> Alle </b> kan udforske, kommentere, stille spørgsmål og dele rekonstrueret 3D-model, når den er online. Du som ejer vil modtage den første invitation til at tilføje kommentar og historie, der vil blive fremhævet som original kommentar.",
contributep1:"Det er alt, forskningsarven er tilgængelig over hele verden for andre studerende, undervisere og forskere.",
contributep2:"I øjeblikket accepterer vi kun bidrag fra brugere med akademiske e-mails. Hvis du ikke har akademisk e-mail, men gerne vil bidrage, skal du <input type=\"button\" onclick=\"openBoard('aboutProject');\" value=\"Kontakt os\" />.",
contributestart:"Start upload af objektfoto",
newuserh3:"Ny brugerregistrering",
newuseri1:"Navn",
newuseri1l:" Dit navn og efternavn vises ved siden af ​​objekter, du uploader / kommenterer.",
newuseri2:"Efternavn",
newuseri3:"Institution og land",
newuseri3l:" Din tilknytning og dit land, hvor du befinder dig.",
newuseri4:"e-mail",
newuseri4l:" Bemærk: kun akademiske e-mails accepteres. Du modtager et bekræftelseslink.",
newuseri5:"Indtast adgangskode",
newuseri5l:" Minimum 8 tegn.",
newuseri6:"Gentag adgangskode",
newuseri6l:" Bare for at kontrollere, at der ikke er nogen skrivefejl.",
newusersubmit:"Registrer en ny bruger",
uploadedobjects:"Eksisterende uploadede objekter:",
nameobject:"Navngiv din nye genstand",
enterobjectname:"indtast nyt objektnavn",
and:"og",
cratephotospace:"skab plads til fotografier",
photolisting:"Liste over fotografier af",
nophotolist:"Du har ikke uploadet fotos endnu til noget objekt. Upload venligst objektfotografier nedenfor.",
uploadnewphotos:"Upload nye filer",
startupload:"Start upload",
metadataobject:"Metadata på det fotograferede objekt",
objtitle:"Objektets titel",
objtitlel:"Objektets titel",
objdetails:"Objektdetaljer",
objdetailsl:"kort objektbeskrivelse",
objlocation:"Objektets originale og nuværende placering",
objyear:"År, hvor objekt blev foretaget (estimering)",
objtags:"Objekt tags",
objsubmit:"Indsend foto til 3D-genopbygning",
newobjectspaceerror:"Der opstod en fejl ved oprettelse af dit objektplads:",
newobjectspacesuccess:"Oprettet vellykket plads til fotografier af et nyt objekt.",
objsubmerr1:"FEJL: Du skal tilføje nogle <b> Objekt tags </b> før indsendelse!",
objsubmerr2:"FEJL: Objektnavnet skal have en længde på mindst 3 tegn",
objsubmerr3:"FEJL: Indtast mindst 10 tegn til objektbeskrivelse.",
objsubmerr4:"FEJL: Indtast placeringen af ​​objektet (historisk, nuværende eller firma, hvorfra det er tilgængeligt).",
objsubmerr5:"FEJL: Indtast år for oprettelse af objekt (estimeret).",
delete:"slette",
question:"Spørgsmål",
answers:"svar",
addeditanswer:"Tilføj eller rediger dit svar",
clickdownvotel:"Klik for at downvote spørgsmål eller svar",
clickupvotel:"Klik for at upvote spørgsmål eller svar",
yourquestion:"Dit spørgsmål:",
questiondesc:"Tilføj kommentar på objektet og beskriv tekstlige detaljer om spørgsmål.",
submitquestion:"Indsend spørgsmål",
tooltipmainm:"Klik for at åbne hovedmenuen",
meniobject:"Objekt",
questiontitle:"Spørgsmålstitel",
aboutfunding:"Finansiering",
about15:"Projekt støttet af Science and Society of La Diagonale Paris-Saclay.",
size:"størrelse",
color:"farve",
red:"rød",
green:"grøn",
blue:"blå",
orange:"orange",
magenta:"magenta",
selectlicense:"Vælg licens for uploadede filer (den rekonstruerede model frigives under samme licens)",
read:"Læs",
licensetext:"licens",
translated:"oversat",
transsee:"se oversættelse i",
transsource:"Oprindelig tekst",
transseesource:"se original i",
transimprove:"forbedre oversættelse",
"fr":"fransk",
"en":"engelsk",
"es":"spansk",
"pt":"portugisisk",
"de":"tysk",
"zh":"kinesisk",
"ru":"Russisk",
"ar":"arabisk",
"sv":"Svensk",
"nl":"hollandske",
"it":"italiensk",
"ja":"japansk",
"sr":"serbisk",
"cs":"tjekkisk",
"da":"dansk",
"sw":"Swahili",
"hi":"Hindi",
"tr":"tyrkisk",
"vi":"Vietnamesisk",
"th":"Thai",
"ko":"Korean",
"fa":"Farsi",
"id":"Indonesisk",
"cy":"Welsh",
"el":"græsk",
"ro":"Rumænsk",
"hu":"Ungarsk",
"pl":"Polere",
transimprovetitle:"Forbedre oversættelse",
transnote:"Oversættelse er en del af maskinoversættelse og menneskelig bidrag. Tak for at du tog dig tid til at bidrage.",
transorigin:"Original i",
transsuggest:"Oversættelse i",
transsubmit:"Indsend oversættelse",
press:"Røre ved",
forillustration:"til illustration",
storylang:"Skrevet på sprog:",
footer0:"Om ResearchX3D",
footer1:"Søg efter objekter, historier og spørgsmål",
footer2:"Stil spørgsmål om objekt",
footer3:"Forstærket virkelighed",
footer4:"Indsend objekt",
footer5:"Indsend historie",
footer_title1:"HURTIGE LINKS",
footer_title2:"SOCIALE LINKS",
navigation:"Navigation",
rotation:"at rotere",
move:"flytte, eller",
zoom:"zoom objektet på",
clickForStory:"Klik her for at se objektets historie.",
latexAdd:"eller tilføj til LaTeX-dokument",
latexPDF:"download PDF-billede her",
latexCode:"og tilføj kode nedenfor.",
latexCaption1:"Scan QR-kode, eller indtast",
latexCaption2:"for at åbne objekt.",
contributeHeader:"BLIV EN BIDRAGER",
contribute1:"Se en kort video om motivation bag ResearchX3D ...",
contribute2:"... eller se bare en 4-minutters ResearchX3D introduktion.",
contribute3:"ResearchX3D opretter 3D-modeller ud fra dine fotografier ...",
contribute4:"... men du kan også uploade allerede oprettede 3D-objekter, for eksempel fra en CAD-software.",
contribute5:"Hvert objekt har mange historier at fortælle. Ved at oprette forskellige typer historier kan du:",
contribute6:"Forklar en funktion og et design; eller",
contribute7:"Test viden med en quiz; eller",
contribute8:"Del færdigheder og procedurer.",
contribute9:"Sådan hjælper ResearchX3D-editoren dig med at oprette en historie.",
clickvideo:"Klik her for at se videoen.",
clickexample:"Klik her for at se et eksempel",
openstory:"Åbn denne historie",
allsbj:"alle fagområder",
showall:"Vis al",
graphic:"grafis",
figclick:"Find historier og kommentarer om dette objekt",
openar:"åben i Augmented Reality",
meniagora:"Fællesskabsdiskussioner - Agora",
r3dsummary:"<b> Hvad er ResearchX3D? </b> En åben community-platform til deling af videnskabelig arv for at frigøre kreativ værdi for fremtiden.",
agoraad:"<b> Foreslå og diskutere </b> ideer om ResearchX3D-projektet, og få hjælp til vores Agora <img class = 'link' src = '/link.png'> til samfundsdiskussioner."
};
